package main

import (
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"exe.dev/execore"

	"github.com/stretchr/testify/require"
)

// TestGeneratedDocsUpToDate ensures that the generated documentation
// in docs/content/cli-*.md matches what would be generated by gendocs.
// If this test fails, run "go run ./cmd/gendocs" to update the docs.
func TestGeneratedDocsUpToDate(t *testing.T) {
	// Get project root (cmd/gendocs -> ../..)
	projectRoot, err := filepath.Abs(filepath.Join("..", ".."))
	require.NoError(t, err)

	// Generate what the docs should look like using the real command tree
	ss := &execore.SSHServer{}
	ct := execore.NewCommandTree(ss)

	var suborder int
	for _, cmd := range ct.Commands {
		if cmd.Hidden {
			continue
		}
		suborder++
		expected := generateCommandDoc(cmd, suborder)
		filename := fmt.Sprintf("cli-%s.md", cmd.Name)
		existingPath := filepath.Join(projectRoot, outputDir, filename)

		existingContent, err := os.ReadFile(existingPath)
		require.NoError(t, err, "%s should exist - run 'go run ./cmd/gencmddocs' to generate it", filename)

		require.Equal(t, expected, string(existingContent),
			"%s is out of date - run 'go run ./cmd/gencmddocs' to update it", filename)
	}
}
