// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: exe/compute/v1/compute.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ComputeService_CreateInstance_FullMethodName         = "/exe.compute.v1.ComputeService/CreateInstance"
	ComputeService_ListInstances_FullMethodName          = "/exe.compute.v1.ComputeService/ListInstances"
	ComputeService_GetInstance_FullMethodName            = "/exe.compute.v1.ComputeService/GetInstance"
	ComputeService_GetInstanceLogs_FullMethodName        = "/exe.compute.v1.ComputeService/GetInstanceLogs"
	ComputeService_StartInstance_FullMethodName          = "/exe.compute.v1.ComputeService/StartInstance"
	ComputeService_StopInstance_FullMethodName           = "/exe.compute.v1.ComputeService/StopInstance"
	ComputeService_UpdateInstance_FullMethodName         = "/exe.compute.v1.ComputeService/UpdateInstance"
	ComputeService_DeleteInstance_FullMethodName         = "/exe.compute.v1.ComputeService/DeleteInstance"
	ComputeService_SetInstanceGroup_FullMethodName       = "/exe.compute.v1.ComputeService/SetInstanceGroup"
	ComputeService_RenameInstance_FullMethodName         = "/exe.compute.v1.ComputeService/RenameInstance"
	ComputeService_GetSystemInfo_FullMethodName          = "/exe.compute.v1.ComputeService/GetSystemInfo"
	ComputeService_SendVM_FullMethodName                 = "/exe.compute.v1.ComputeService/SendVM"
	ComputeService_ReceiveVM_FullMethodName              = "/exe.compute.v1.ComputeService/ReceiveVM"
	ComputeService_GrowDisk_FullMethodName               = "/exe.compute.v1.ComputeService/GrowDisk"
	ComputeService_ResizeVM_FullMethodName               = "/exe.compute.v1.ComputeService/ResizeVM"
	ComputeService_CloneInstance_FullMethodName          = "/exe.compute.v1.ComputeService/CloneInstance"
	ComputeService_MigrateStorageTier_FullMethodName     = "/exe.compute.v1.ComputeService/MigrateStorageTier"
	ComputeService_GetTierMigrationStatus_FullMethodName = "/exe.compute.v1.ComputeService/GetTierMigrationStatus"
	ComputeService_ListStorageTiers_FullMethodName       = "/exe.compute.v1.ComputeService/ListStorageTiers"
	ComputeService_ClearTierMigrations_FullMethodName    = "/exe.compute.v1.ComputeService/ClearTierMigrations"
)

// ComputeServiceClient is the client API for ComputeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ComputeServiceClient interface {
	CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CreateInstanceResponse], error)
	ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListInstancesResponse], error)
	GetInstance(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*GetInstanceResponse, error)
	GetInstanceLogs(ctx context.Context, in *GetInstanceLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetInstanceLogsResponse], error)
	StartInstance(ctx context.Context, in *StartInstanceRequest, opts ...grpc.CallOption) (*StartInstanceResponse, error)
	StopInstance(ctx context.Context, in *StopInstanceRequest, opts ...grpc.CallOption) (*StopInstanceResponse, error)
	UpdateInstance(ctx context.Context, in *UpdateInstanceRequest, opts ...grpc.CallOption) (*UpdateInstanceResponse, error)
	DeleteInstance(ctx context.Context, in *DeleteInstanceRequest, opts ...grpc.CallOption) (*DeleteInstanceResponse, error)
	SetInstanceGroup(ctx context.Context, in *SetInstanceGroupRequest, opts ...grpc.CallOption) (*SetInstanceGroupResponse, error)
	RenameInstance(ctx context.Context, in *RenameInstanceRequest, opts ...grpc.CallOption) (*RenameInstanceResponse, error)
	GetSystemInfo(ctx context.Context, in *GetSystemInfoRequest, opts ...grpc.CallOption) (*GetSystemInfoResponse, error)
	// SendVM streams a stopped VM's disk and config to the caller for migration
	SendVM(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SendVMRequest, SendVMResponse], error)
	// ReceiveVM receives a VM from another exelet
	ReceiveVM(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ReceiveVMRequest, ReceiveVMResponse], error)
	// GrowDisk grows the disk of a running VM
	GrowDisk(ctx context.Context, in *GrowDiskRequest, opts ...grpc.CallOption) (*GrowDiskResponse, error)
	// ResizeVM resizes the memory and/or CPU allocation of a VM (requires restart)
	ResizeVM(ctx context.Context, in *ResizeVMRequest, opts ...grpc.CallOption) (*ResizeVMResponse, error)
	// CloneInstance clones an existing VM using ZFS copy-on-write snapshots
	CloneInstance(ctx context.Context, in *CloneInstanceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CloneInstanceResponse], error)
	// MigrateStorageTier migrates a VM's storage between local ZFS pools (async)
	MigrateStorageTier(ctx context.Context, in *MigrateStorageTierRequest, opts ...grpc.CallOption) (*MigrateStorageTierResponse, error)
	// GetTierMigrationStatus returns in-progress tier migration operations
	GetTierMigrationStatus(ctx context.Context, in *GetTierMigrationStatusRequest, opts ...grpc.CallOption) (*GetTierMigrationStatusResponse, error)
	// ListStorageTiers returns all configured storage tiers and their capacity
	ListStorageTiers(ctx context.Context, in *ListStorageTiersRequest, opts ...grpc.CallOption) (*ListStorageTiersResponse, error)
	// ClearTierMigrations removes completed and failed tier migration operations
	ClearTierMigrations(ctx context.Context, in *ClearTierMigrationsRequest, opts ...grpc.CallOption) (*ClearTierMigrationsResponse, error)
}

type computeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewComputeServiceClient(cc grpc.ClientConnInterface) ComputeServiceClient {
	return &computeServiceClient{cc}
}

func (c *computeServiceClient) CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CreateInstanceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ComputeService_ServiceDesc.Streams[0], ComputeService_CreateInstance_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CreateInstanceRequest, CreateInstanceResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ComputeService_CreateInstanceClient = grpc.ServerStreamingClient[CreateInstanceResponse]

func (c *computeServiceClient) ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListInstancesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ComputeService_ServiceDesc.Streams[1], ComputeService_ListInstances_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListInstancesRequest, ListInstancesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ComputeService_ListInstancesClient = grpc.ServerStreamingClient[ListInstancesResponse]

func (c *computeServiceClient) GetInstance(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*GetInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInstanceResponse)
	err := c.cc.Invoke(ctx, ComputeService_GetInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) GetInstanceLogs(ctx context.Context, in *GetInstanceLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetInstanceLogsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ComputeService_ServiceDesc.Streams[2], ComputeService_GetInstanceLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetInstanceLogsRequest, GetInstanceLogsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ComputeService_GetInstanceLogsClient = grpc.ServerStreamingClient[GetInstanceLogsResponse]

func (c *computeServiceClient) StartInstance(ctx context.Context, in *StartInstanceRequest, opts ...grpc.CallOption) (*StartInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartInstanceResponse)
	err := c.cc.Invoke(ctx, ComputeService_StartInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) StopInstance(ctx context.Context, in *StopInstanceRequest, opts ...grpc.CallOption) (*StopInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopInstanceResponse)
	err := c.cc.Invoke(ctx, ComputeService_StopInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) UpdateInstance(ctx context.Context, in *UpdateInstanceRequest, opts ...grpc.CallOption) (*UpdateInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateInstanceResponse)
	err := c.cc.Invoke(ctx, ComputeService_UpdateInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) DeleteInstance(ctx context.Context, in *DeleteInstanceRequest, opts ...grpc.CallOption) (*DeleteInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteInstanceResponse)
	err := c.cc.Invoke(ctx, ComputeService_DeleteInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) SetInstanceGroup(ctx context.Context, in *SetInstanceGroupRequest, opts ...grpc.CallOption) (*SetInstanceGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetInstanceGroupResponse)
	err := c.cc.Invoke(ctx, ComputeService_SetInstanceGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) RenameInstance(ctx context.Context, in *RenameInstanceRequest, opts ...grpc.CallOption) (*RenameInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenameInstanceResponse)
	err := c.cc.Invoke(ctx, ComputeService_RenameInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) GetSystemInfo(ctx context.Context, in *GetSystemInfoRequest, opts ...grpc.CallOption) (*GetSystemInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSystemInfoResponse)
	err := c.cc.Invoke(ctx, ComputeService_GetSystemInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) SendVM(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SendVMRequest, SendVMResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ComputeService_ServiceDesc.Streams[3], ComputeService_SendVM_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SendVMRequest, SendVMResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ComputeService_SendVMClient = grpc.BidiStreamingClient[SendVMRequest, SendVMResponse]

func (c *computeServiceClient) ReceiveVM(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ReceiveVMRequest, ReceiveVMResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ComputeService_ServiceDesc.Streams[4], ComputeService_ReceiveVM_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReceiveVMRequest, ReceiveVMResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ComputeService_ReceiveVMClient = grpc.BidiStreamingClient[ReceiveVMRequest, ReceiveVMResponse]

func (c *computeServiceClient) GrowDisk(ctx context.Context, in *GrowDiskRequest, opts ...grpc.CallOption) (*GrowDiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrowDiskResponse)
	err := c.cc.Invoke(ctx, ComputeService_GrowDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) ResizeVM(ctx context.Context, in *ResizeVMRequest, opts ...grpc.CallOption) (*ResizeVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResizeVMResponse)
	err := c.cc.Invoke(ctx, ComputeService_ResizeVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) CloneInstance(ctx context.Context, in *CloneInstanceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CloneInstanceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ComputeService_ServiceDesc.Streams[5], ComputeService_CloneInstance_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CloneInstanceRequest, CloneInstanceResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ComputeService_CloneInstanceClient = grpc.ServerStreamingClient[CloneInstanceResponse]

func (c *computeServiceClient) MigrateStorageTier(ctx context.Context, in *MigrateStorageTierRequest, opts ...grpc.CallOption) (*MigrateStorageTierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrateStorageTierResponse)
	err := c.cc.Invoke(ctx, ComputeService_MigrateStorageTier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) GetTierMigrationStatus(ctx context.Context, in *GetTierMigrationStatusRequest, opts ...grpc.CallOption) (*GetTierMigrationStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTierMigrationStatusResponse)
	err := c.cc.Invoke(ctx, ComputeService_GetTierMigrationStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) ListStorageTiers(ctx context.Context, in *ListStorageTiersRequest, opts ...grpc.CallOption) (*ListStorageTiersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStorageTiersResponse)
	err := c.cc.Invoke(ctx, ComputeService_ListStorageTiers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) ClearTierMigrations(ctx context.Context, in *ClearTierMigrationsRequest, opts ...grpc.CallOption) (*ClearTierMigrationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearTierMigrationsResponse)
	err := c.cc.Invoke(ctx, ComputeService_ClearTierMigrations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComputeServiceServer is the server API for ComputeService service.
// All implementations must embed UnimplementedComputeServiceServer
// for forward compatibility.
type ComputeServiceServer interface {
	CreateInstance(*CreateInstanceRequest, grpc.ServerStreamingServer[CreateInstanceResponse]) error
	ListInstances(*ListInstancesRequest, grpc.ServerStreamingServer[ListInstancesResponse]) error
	GetInstance(context.Context, *GetInstanceRequest) (*GetInstanceResponse, error)
	GetInstanceLogs(*GetInstanceLogsRequest, grpc.ServerStreamingServer[GetInstanceLogsResponse]) error
	StartInstance(context.Context, *StartInstanceRequest) (*StartInstanceResponse, error)
	StopInstance(context.Context, *StopInstanceRequest) (*StopInstanceResponse, error)
	UpdateInstance(context.Context, *UpdateInstanceRequest) (*UpdateInstanceResponse, error)
	DeleteInstance(context.Context, *DeleteInstanceRequest) (*DeleteInstanceResponse, error)
	SetInstanceGroup(context.Context, *SetInstanceGroupRequest) (*SetInstanceGroupResponse, error)
	RenameInstance(context.Context, *RenameInstanceRequest) (*RenameInstanceResponse, error)
	GetSystemInfo(context.Context, *GetSystemInfoRequest) (*GetSystemInfoResponse, error)
	// SendVM streams a stopped VM's disk and config to the caller for migration
	SendVM(grpc.BidiStreamingServer[SendVMRequest, SendVMResponse]) error
	// ReceiveVM receives a VM from another exelet
	ReceiveVM(grpc.BidiStreamingServer[ReceiveVMRequest, ReceiveVMResponse]) error
	// GrowDisk grows the disk of a running VM
	GrowDisk(context.Context, *GrowDiskRequest) (*GrowDiskResponse, error)
	// ResizeVM resizes the memory and/or CPU allocation of a VM (requires restart)
	ResizeVM(context.Context, *ResizeVMRequest) (*ResizeVMResponse, error)
	// CloneInstance clones an existing VM using ZFS copy-on-write snapshots
	CloneInstance(*CloneInstanceRequest, grpc.ServerStreamingServer[CloneInstanceResponse]) error
	// MigrateStorageTier migrates a VM's storage between local ZFS pools (async)
	MigrateStorageTier(context.Context, *MigrateStorageTierRequest) (*MigrateStorageTierResponse, error)
	// GetTierMigrationStatus returns in-progress tier migration operations
	GetTierMigrationStatus(context.Context, *GetTierMigrationStatusRequest) (*GetTierMigrationStatusResponse, error)
	// ListStorageTiers returns all configured storage tiers and their capacity
	ListStorageTiers(context.Context, *ListStorageTiersRequest) (*ListStorageTiersResponse, error)
	// ClearTierMigrations removes completed and failed tier migration operations
	ClearTierMigrations(context.Context, *ClearTierMigrationsRequest) (*ClearTierMigrationsResponse, error)
	mustEmbedUnimplementedComputeServiceServer()
}

// UnimplementedComputeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedComputeServiceServer struct{}

func (UnimplementedComputeServiceServer) CreateInstance(*CreateInstanceRequest, grpc.ServerStreamingServer[CreateInstanceResponse]) error {
	return status.Error(codes.Unimplemented, "method CreateInstance not implemented")
}
func (UnimplementedComputeServiceServer) ListInstances(*ListInstancesRequest, grpc.ServerStreamingServer[ListInstancesResponse]) error {
	return status.Error(codes.Unimplemented, "method ListInstances not implemented")
}
func (UnimplementedComputeServiceServer) GetInstance(context.Context, *GetInstanceRequest) (*GetInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstance not implemented")
}
func (UnimplementedComputeServiceServer) GetInstanceLogs(*GetInstanceLogsRequest, grpc.ServerStreamingServer[GetInstanceLogsResponse]) error {
	return status.Error(codes.Unimplemented, "method GetInstanceLogs not implemented")
}
func (UnimplementedComputeServiceServer) StartInstance(context.Context, *StartInstanceRequest) (*StartInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartInstance not implemented")
}
func (UnimplementedComputeServiceServer) StopInstance(context.Context, *StopInstanceRequest) (*StopInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopInstance not implemented")
}
func (UnimplementedComputeServiceServer) UpdateInstance(context.Context, *UpdateInstanceRequest) (*UpdateInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateInstance not implemented")
}
func (UnimplementedComputeServiceServer) DeleteInstance(context.Context, *DeleteInstanceRequest) (*DeleteInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteInstance not implemented")
}
func (UnimplementedComputeServiceServer) SetInstanceGroup(context.Context, *SetInstanceGroupRequest) (*SetInstanceGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetInstanceGroup not implemented")
}
func (UnimplementedComputeServiceServer) RenameInstance(context.Context, *RenameInstanceRequest) (*RenameInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameInstance not implemented")
}
func (UnimplementedComputeServiceServer) GetSystemInfo(context.Context, *GetSystemInfoRequest) (*GetSystemInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSystemInfo not implemented")
}
func (UnimplementedComputeServiceServer) SendVM(grpc.BidiStreamingServer[SendVMRequest, SendVMResponse]) error {
	return status.Error(codes.Unimplemented, "method SendVM not implemented")
}
func (UnimplementedComputeServiceServer) ReceiveVM(grpc.BidiStreamingServer[ReceiveVMRequest, ReceiveVMResponse]) error {
	return status.Error(codes.Unimplemented, "method ReceiveVM not implemented")
}
func (UnimplementedComputeServiceServer) GrowDisk(context.Context, *GrowDiskRequest) (*GrowDiskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GrowDisk not implemented")
}
func (UnimplementedComputeServiceServer) ResizeVM(context.Context, *ResizeVMRequest) (*ResizeVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResizeVM not implemented")
}
func (UnimplementedComputeServiceServer) CloneInstance(*CloneInstanceRequest, grpc.ServerStreamingServer[CloneInstanceResponse]) error {
	return status.Error(codes.Unimplemented, "method CloneInstance not implemented")
}
func (UnimplementedComputeServiceServer) MigrateStorageTier(context.Context, *MigrateStorageTierRequest) (*MigrateStorageTierResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MigrateStorageTier not implemented")
}
func (UnimplementedComputeServiceServer) GetTierMigrationStatus(context.Context, *GetTierMigrationStatusRequest) (*GetTierMigrationStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTierMigrationStatus not implemented")
}
func (UnimplementedComputeServiceServer) ListStorageTiers(context.Context, *ListStorageTiersRequest) (*ListStorageTiersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStorageTiers not implemented")
}
func (UnimplementedComputeServiceServer) ClearTierMigrations(context.Context, *ClearTierMigrationsRequest) (*ClearTierMigrationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearTierMigrations not implemented")
}
func (UnimplementedComputeServiceServer) mustEmbedUnimplementedComputeServiceServer() {}
func (UnimplementedComputeServiceServer) testEmbeddedByValue()                        {}

// UnsafeComputeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComputeServiceServer will
// result in compilation errors.
type UnsafeComputeServiceServer interface {
	mustEmbedUnimplementedComputeServiceServer()
}

func RegisterComputeServiceServer(s grpc.ServiceRegistrar, srv ComputeServiceServer) {
	// If the following call panics, it indicates UnimplementedComputeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ComputeService_ServiceDesc, srv)
}

func _ComputeService_CreateInstance_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CreateInstanceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ComputeServiceServer).CreateInstance(m, &grpc.GenericServerStream[CreateInstanceRequest, CreateInstanceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ComputeService_CreateInstanceServer = grpc.ServerStreamingServer[CreateInstanceResponse]

func _ComputeService_ListInstances_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListInstancesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ComputeServiceServer).ListInstances(m, &grpc.GenericServerStream[ListInstancesRequest, ListInstancesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ComputeService_ListInstancesServer = grpc.ServerStreamingServer[ListInstancesResponse]

func _ComputeService_GetInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).GetInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_GetInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).GetInstance(ctx, req.(*GetInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_GetInstanceLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetInstanceLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ComputeServiceServer).GetInstanceLogs(m, &grpc.GenericServerStream[GetInstanceLogsRequest, GetInstanceLogsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ComputeService_GetInstanceLogsServer = grpc.ServerStreamingServer[GetInstanceLogsResponse]

func _ComputeService_StartInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).StartInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_StartInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).StartInstance(ctx, req.(*StartInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_StopInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).StopInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_StopInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).StopInstance(ctx, req.(*StopInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_UpdateInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).UpdateInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_UpdateInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).UpdateInstance(ctx, req.(*UpdateInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_DeleteInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).DeleteInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_DeleteInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).DeleteInstance(ctx, req.(*DeleteInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_SetInstanceGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetInstanceGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).SetInstanceGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_SetInstanceGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).SetInstanceGroup(ctx, req.(*SetInstanceGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_RenameInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).RenameInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_RenameInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).RenameInstance(ctx, req.(*RenameInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_GetSystemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSystemInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).GetSystemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_GetSystemInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).GetSystemInfo(ctx, req.(*GetSystemInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_SendVM_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ComputeServiceServer).SendVM(&grpc.GenericServerStream[SendVMRequest, SendVMResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ComputeService_SendVMServer = grpc.BidiStreamingServer[SendVMRequest, SendVMResponse]

func _ComputeService_ReceiveVM_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ComputeServiceServer).ReceiveVM(&grpc.GenericServerStream[ReceiveVMRequest, ReceiveVMResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ComputeService_ReceiveVMServer = grpc.BidiStreamingServer[ReceiveVMRequest, ReceiveVMResponse]

func _ComputeService_GrowDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrowDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).GrowDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_GrowDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).GrowDisk(ctx, req.(*GrowDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_ResizeVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResizeVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).ResizeVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_ResizeVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).ResizeVM(ctx, req.(*ResizeVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_CloneInstance_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CloneInstanceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ComputeServiceServer).CloneInstance(m, &grpc.GenericServerStream[CloneInstanceRequest, CloneInstanceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ComputeService_CloneInstanceServer = grpc.ServerStreamingServer[CloneInstanceResponse]

func _ComputeService_MigrateStorageTier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateStorageTierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).MigrateStorageTier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_MigrateStorageTier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).MigrateStorageTier(ctx, req.(*MigrateStorageTierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_GetTierMigrationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTierMigrationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).GetTierMigrationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_GetTierMigrationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).GetTierMigrationStatus(ctx, req.(*GetTierMigrationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_ListStorageTiers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStorageTiersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).ListStorageTiers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_ListStorageTiers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).ListStorageTiers(ctx, req.(*ListStorageTiersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_ClearTierMigrations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearTierMigrationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).ClearTierMigrations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_ClearTierMigrations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).ClearTierMigrations(ctx, req.(*ClearTierMigrationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ComputeService_ServiceDesc is the grpc.ServiceDesc for ComputeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ComputeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "exe.compute.v1.ComputeService",
	HandlerType: (*ComputeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInstance",
			Handler:    _ComputeService_GetInstance_Handler,
		},
		{
			MethodName: "StartInstance",
			Handler:    _ComputeService_StartInstance_Handler,
		},
		{
			MethodName: "StopInstance",
			Handler:    _ComputeService_StopInstance_Handler,
		},
		{
			MethodName: "UpdateInstance",
			Handler:    _ComputeService_UpdateInstance_Handler,
		},
		{
			MethodName: "DeleteInstance",
			Handler:    _ComputeService_DeleteInstance_Handler,
		},
		{
			MethodName: "SetInstanceGroup",
			Handler:    _ComputeService_SetInstanceGroup_Handler,
		},
		{
			MethodName: "RenameInstance",
			Handler:    _ComputeService_RenameInstance_Handler,
		},
		{
			MethodName: "GetSystemInfo",
			Handler:    _ComputeService_GetSystemInfo_Handler,
		},
		{
			MethodName: "GrowDisk",
			Handler:    _ComputeService_GrowDisk_Handler,
		},
		{
			MethodName: "ResizeVM",
			Handler:    _ComputeService_ResizeVM_Handler,
		},
		{
			MethodName: "MigrateStorageTier",
			Handler:    _ComputeService_MigrateStorageTier_Handler,
		},
		{
			MethodName: "GetTierMigrationStatus",
			Handler:    _ComputeService_GetTierMigrationStatus_Handler,
		},
		{
			MethodName: "ListStorageTiers",
			Handler:    _ComputeService_ListStorageTiers_Handler,
		},
		{
			MethodName: "ClearTierMigrations",
			Handler:    _ComputeService_ClearTierMigrations_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateInstance",
			Handler:       _ComputeService_CreateInstance_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListInstances",
			Handler:       _ComputeService_ListInstances_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetInstanceLogs",
			Handler:       _ComputeService_GetInstanceLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SendVM",
			Handler:       _ComputeService_SendVM_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ReceiveVM",
			Handler:       _ComputeService_ReceiveVM_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CloneInstance",
			Handler:       _ComputeService_CloneInstance_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "exe/compute/v1/compute.proto",
}
