// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: exe/compute/v1/compute.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	ComputeService_CreateInstance_FullMethodName   = "/exe.compute.v1.ComputeService/CreateInstance"
	ComputeService_ListInstances_FullMethodName    = "/exe.compute.v1.ComputeService/ListInstances"
	ComputeService_GetInstance_FullMethodName      = "/exe.compute.v1.ComputeService/GetInstance"
	ComputeService_GetInstanceLogs_FullMethodName  = "/exe.compute.v1.ComputeService/GetInstanceLogs"
	ComputeService_StartInstance_FullMethodName    = "/exe.compute.v1.ComputeService/StartInstance"
	ComputeService_StopInstance_FullMethodName     = "/exe.compute.v1.ComputeService/StopInstance"
	ComputeService_UpdateInstance_FullMethodName   = "/exe.compute.v1.ComputeService/UpdateInstance"
	ComputeService_DeleteInstance_FullMethodName   = "/exe.compute.v1.ComputeService/DeleteInstance"
	ComputeService_SetInstanceGroup_FullMethodName = "/exe.compute.v1.ComputeService/SetInstanceGroup"
	ComputeService_RenameInstance_FullMethodName   = "/exe.compute.v1.ComputeService/RenameInstance"
	ComputeService_GetSystemInfo_FullMethodName    = "/exe.compute.v1.ComputeService/GetSystemInfo"
	ComputeService_SendVM_FullMethodName           = "/exe.compute.v1.ComputeService/SendVM"
	ComputeService_ReceiveVM_FullMethodName        = "/exe.compute.v1.ComputeService/ReceiveVM"
	ComputeService_GrowDisk_FullMethodName         = "/exe.compute.v1.ComputeService/GrowDisk"
)

// ComputeServiceClient is the client API for ComputeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ComputeServiceClient interface {
	CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (ComputeService_CreateInstanceClient, error)
	ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (ComputeService_ListInstancesClient, error)
	GetInstance(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*GetInstanceResponse, error)
	GetInstanceLogs(ctx context.Context, in *GetInstanceLogsRequest, opts ...grpc.CallOption) (ComputeService_GetInstanceLogsClient, error)
	StartInstance(ctx context.Context, in *StartInstanceRequest, opts ...grpc.CallOption) (*StartInstanceResponse, error)
	StopInstance(ctx context.Context, in *StopInstanceRequest, opts ...grpc.CallOption) (*StopInstanceResponse, error)
	UpdateInstance(ctx context.Context, in *UpdateInstanceRequest, opts ...grpc.CallOption) (*UpdateInstanceResponse, error)
	DeleteInstance(ctx context.Context, in *DeleteInstanceRequest, opts ...grpc.CallOption) (*DeleteInstanceResponse, error)
	SetInstanceGroup(ctx context.Context, in *SetInstanceGroupRequest, opts ...grpc.CallOption) (*SetInstanceGroupResponse, error)
	RenameInstance(ctx context.Context, in *RenameInstanceRequest, opts ...grpc.CallOption) (*RenameInstanceResponse, error)
	GetSystemInfo(ctx context.Context, in *GetSystemInfoRequest, opts ...grpc.CallOption) (*GetSystemInfoResponse, error)
	// SendVM streams a stopped VM's disk and config to the caller for migration
	SendVM(ctx context.Context, opts ...grpc.CallOption) (ComputeService_SendVMClient, error)
	// ReceiveVM receives a VM from another exelet
	ReceiveVM(ctx context.Context, opts ...grpc.CallOption) (ComputeService_ReceiveVMClient, error)
	// GrowDisk grows the disk of a running VM
	GrowDisk(ctx context.Context, in *GrowDiskRequest, opts ...grpc.CallOption) (*GrowDiskResponse, error)
}

type computeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewComputeServiceClient(cc grpc.ClientConnInterface) ComputeServiceClient {
	return &computeServiceClient{cc}
}

func (c *computeServiceClient) CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (ComputeService_CreateInstanceClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ComputeService_ServiceDesc.Streams[0], ComputeService_CreateInstance_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &computeServiceCreateInstanceClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ComputeService_CreateInstanceClient interface {
	Recv() (*CreateInstanceResponse, error)
	grpc.ClientStream
}

type computeServiceCreateInstanceClient struct {
	grpc.ClientStream
}

func (x *computeServiceCreateInstanceClient) Recv() (*CreateInstanceResponse, error) {
	m := new(CreateInstanceResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *computeServiceClient) ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (ComputeService_ListInstancesClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ComputeService_ServiceDesc.Streams[1], ComputeService_ListInstances_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &computeServiceListInstancesClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ComputeService_ListInstancesClient interface {
	Recv() (*ListInstancesResponse, error)
	grpc.ClientStream
}

type computeServiceListInstancesClient struct {
	grpc.ClientStream
}

func (x *computeServiceListInstancesClient) Recv() (*ListInstancesResponse, error) {
	m := new(ListInstancesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *computeServiceClient) GetInstance(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*GetInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInstanceResponse)
	err := c.cc.Invoke(ctx, ComputeService_GetInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) GetInstanceLogs(ctx context.Context, in *GetInstanceLogsRequest, opts ...grpc.CallOption) (ComputeService_GetInstanceLogsClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ComputeService_ServiceDesc.Streams[2], ComputeService_GetInstanceLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &computeServiceGetInstanceLogsClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ComputeService_GetInstanceLogsClient interface {
	Recv() (*GetInstanceLogsResponse, error)
	grpc.ClientStream
}

type computeServiceGetInstanceLogsClient struct {
	grpc.ClientStream
}

func (x *computeServiceGetInstanceLogsClient) Recv() (*GetInstanceLogsResponse, error) {
	m := new(GetInstanceLogsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *computeServiceClient) StartInstance(ctx context.Context, in *StartInstanceRequest, opts ...grpc.CallOption) (*StartInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartInstanceResponse)
	err := c.cc.Invoke(ctx, ComputeService_StartInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) StopInstance(ctx context.Context, in *StopInstanceRequest, opts ...grpc.CallOption) (*StopInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopInstanceResponse)
	err := c.cc.Invoke(ctx, ComputeService_StopInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) UpdateInstance(ctx context.Context, in *UpdateInstanceRequest, opts ...grpc.CallOption) (*UpdateInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateInstanceResponse)
	err := c.cc.Invoke(ctx, ComputeService_UpdateInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) DeleteInstance(ctx context.Context, in *DeleteInstanceRequest, opts ...grpc.CallOption) (*DeleteInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteInstanceResponse)
	err := c.cc.Invoke(ctx, ComputeService_DeleteInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) SetInstanceGroup(ctx context.Context, in *SetInstanceGroupRequest, opts ...grpc.CallOption) (*SetInstanceGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetInstanceGroupResponse)
	err := c.cc.Invoke(ctx, ComputeService_SetInstanceGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) RenameInstance(ctx context.Context, in *RenameInstanceRequest, opts ...grpc.CallOption) (*RenameInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenameInstanceResponse)
	err := c.cc.Invoke(ctx, ComputeService_RenameInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) GetSystemInfo(ctx context.Context, in *GetSystemInfoRequest, opts ...grpc.CallOption) (*GetSystemInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSystemInfoResponse)
	err := c.cc.Invoke(ctx, ComputeService_GetSystemInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) SendVM(ctx context.Context, opts ...grpc.CallOption) (ComputeService_SendVMClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ComputeService_ServiceDesc.Streams[3], ComputeService_SendVM_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &computeServiceSendVMClient{ClientStream: stream}
	return x, nil
}

type ComputeService_SendVMClient interface {
	Send(*SendVMRequest) error
	Recv() (*SendVMResponse, error)
	grpc.ClientStream
}

type computeServiceSendVMClient struct {
	grpc.ClientStream
}

func (x *computeServiceSendVMClient) Send(m *SendVMRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *computeServiceSendVMClient) Recv() (*SendVMResponse, error) {
	m := new(SendVMResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *computeServiceClient) ReceiveVM(ctx context.Context, opts ...grpc.CallOption) (ComputeService_ReceiveVMClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ComputeService_ServiceDesc.Streams[4], ComputeService_ReceiveVM_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &computeServiceReceiveVMClient{ClientStream: stream}
	return x, nil
}

type ComputeService_ReceiveVMClient interface {
	Send(*ReceiveVMRequest) error
	Recv() (*ReceiveVMResponse, error)
	grpc.ClientStream
}

type computeServiceReceiveVMClient struct {
	grpc.ClientStream
}

func (x *computeServiceReceiveVMClient) Send(m *ReceiveVMRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *computeServiceReceiveVMClient) Recv() (*ReceiveVMResponse, error) {
	m := new(ReceiveVMResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *computeServiceClient) GrowDisk(ctx context.Context, in *GrowDiskRequest, opts ...grpc.CallOption) (*GrowDiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrowDiskResponse)
	err := c.cc.Invoke(ctx, ComputeService_GrowDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComputeServiceServer is the server API for ComputeService service.
// All implementations must embed UnimplementedComputeServiceServer
// for forward compatibility
type ComputeServiceServer interface {
	CreateInstance(*CreateInstanceRequest, ComputeService_CreateInstanceServer) error
	ListInstances(*ListInstancesRequest, ComputeService_ListInstancesServer) error
	GetInstance(context.Context, *GetInstanceRequest) (*GetInstanceResponse, error)
	GetInstanceLogs(*GetInstanceLogsRequest, ComputeService_GetInstanceLogsServer) error
	StartInstance(context.Context, *StartInstanceRequest) (*StartInstanceResponse, error)
	StopInstance(context.Context, *StopInstanceRequest) (*StopInstanceResponse, error)
	UpdateInstance(context.Context, *UpdateInstanceRequest) (*UpdateInstanceResponse, error)
	DeleteInstance(context.Context, *DeleteInstanceRequest) (*DeleteInstanceResponse, error)
	SetInstanceGroup(context.Context, *SetInstanceGroupRequest) (*SetInstanceGroupResponse, error)
	RenameInstance(context.Context, *RenameInstanceRequest) (*RenameInstanceResponse, error)
	GetSystemInfo(context.Context, *GetSystemInfoRequest) (*GetSystemInfoResponse, error)
	// SendVM streams a stopped VM's disk and config to the caller for migration
	SendVM(ComputeService_SendVMServer) error
	// ReceiveVM receives a VM from another exelet
	ReceiveVM(ComputeService_ReceiveVMServer) error
	// GrowDisk grows the disk of a running VM
	GrowDisk(context.Context, *GrowDiskRequest) (*GrowDiskResponse, error)
	mustEmbedUnimplementedComputeServiceServer()
}

// UnimplementedComputeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedComputeServiceServer struct {
}

func (UnimplementedComputeServiceServer) CreateInstance(*CreateInstanceRequest, ComputeService_CreateInstanceServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateInstance not implemented")
}
func (UnimplementedComputeServiceServer) ListInstances(*ListInstancesRequest, ComputeService_ListInstancesServer) error {
	return status.Errorf(codes.Unimplemented, "method ListInstances not implemented")
}
func (UnimplementedComputeServiceServer) GetInstance(context.Context, *GetInstanceRequest) (*GetInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInstance not implemented")
}
func (UnimplementedComputeServiceServer) GetInstanceLogs(*GetInstanceLogsRequest, ComputeService_GetInstanceLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetInstanceLogs not implemented")
}
func (UnimplementedComputeServiceServer) StartInstance(context.Context, *StartInstanceRequest) (*StartInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartInstance not implemented")
}
func (UnimplementedComputeServiceServer) StopInstance(context.Context, *StopInstanceRequest) (*StopInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopInstance not implemented")
}
func (UnimplementedComputeServiceServer) UpdateInstance(context.Context, *UpdateInstanceRequest) (*UpdateInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateInstance not implemented")
}
func (UnimplementedComputeServiceServer) DeleteInstance(context.Context, *DeleteInstanceRequest) (*DeleteInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteInstance not implemented")
}
func (UnimplementedComputeServiceServer) SetInstanceGroup(context.Context, *SetInstanceGroupRequest) (*SetInstanceGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetInstanceGroup not implemented")
}
func (UnimplementedComputeServiceServer) RenameInstance(context.Context, *RenameInstanceRequest) (*RenameInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenameInstance not implemented")
}
func (UnimplementedComputeServiceServer) GetSystemInfo(context.Context, *GetSystemInfoRequest) (*GetSystemInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSystemInfo not implemented")
}
func (UnimplementedComputeServiceServer) SendVM(ComputeService_SendVMServer) error {
	return status.Errorf(codes.Unimplemented, "method SendVM not implemented")
}
func (UnimplementedComputeServiceServer) ReceiveVM(ComputeService_ReceiveVMServer) error {
	return status.Errorf(codes.Unimplemented, "method ReceiveVM not implemented")
}
func (UnimplementedComputeServiceServer) GrowDisk(context.Context, *GrowDiskRequest) (*GrowDiskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrowDisk not implemented")
}
func (UnimplementedComputeServiceServer) mustEmbedUnimplementedComputeServiceServer() {}

// UnsafeComputeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComputeServiceServer will
// result in compilation errors.
type UnsafeComputeServiceServer interface {
	mustEmbedUnimplementedComputeServiceServer()
}

func RegisterComputeServiceServer(s grpc.ServiceRegistrar, srv ComputeServiceServer) {
	s.RegisterService(&ComputeService_ServiceDesc, srv)
}

func _ComputeService_CreateInstance_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CreateInstanceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ComputeServiceServer).CreateInstance(m, &computeServiceCreateInstanceServer{ServerStream: stream})
}

type ComputeService_CreateInstanceServer interface {
	Send(*CreateInstanceResponse) error
	grpc.ServerStream
}

type computeServiceCreateInstanceServer struct {
	grpc.ServerStream
}

func (x *computeServiceCreateInstanceServer) Send(m *CreateInstanceResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ComputeService_ListInstances_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListInstancesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ComputeServiceServer).ListInstances(m, &computeServiceListInstancesServer{ServerStream: stream})
}

type ComputeService_ListInstancesServer interface {
	Send(*ListInstancesResponse) error
	grpc.ServerStream
}

type computeServiceListInstancesServer struct {
	grpc.ServerStream
}

func (x *computeServiceListInstancesServer) Send(m *ListInstancesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ComputeService_GetInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).GetInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_GetInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).GetInstance(ctx, req.(*GetInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_GetInstanceLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetInstanceLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ComputeServiceServer).GetInstanceLogs(m, &computeServiceGetInstanceLogsServer{ServerStream: stream})
}

type ComputeService_GetInstanceLogsServer interface {
	Send(*GetInstanceLogsResponse) error
	grpc.ServerStream
}

type computeServiceGetInstanceLogsServer struct {
	grpc.ServerStream
}

func (x *computeServiceGetInstanceLogsServer) Send(m *GetInstanceLogsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ComputeService_StartInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).StartInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_StartInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).StartInstance(ctx, req.(*StartInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_StopInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).StopInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_StopInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).StopInstance(ctx, req.(*StopInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_UpdateInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).UpdateInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_UpdateInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).UpdateInstance(ctx, req.(*UpdateInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_DeleteInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).DeleteInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_DeleteInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).DeleteInstance(ctx, req.(*DeleteInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_SetInstanceGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetInstanceGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).SetInstanceGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_SetInstanceGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).SetInstanceGroup(ctx, req.(*SetInstanceGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_RenameInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).RenameInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_RenameInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).RenameInstance(ctx, req.(*RenameInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_GetSystemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSystemInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).GetSystemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_GetSystemInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).GetSystemInfo(ctx, req.(*GetSystemInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_SendVM_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ComputeServiceServer).SendVM(&computeServiceSendVMServer{ServerStream: stream})
}

type ComputeService_SendVMServer interface {
	Send(*SendVMResponse) error
	Recv() (*SendVMRequest, error)
	grpc.ServerStream
}

type computeServiceSendVMServer struct {
	grpc.ServerStream
}

func (x *computeServiceSendVMServer) Send(m *SendVMResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *computeServiceSendVMServer) Recv() (*SendVMRequest, error) {
	m := new(SendVMRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ComputeService_ReceiveVM_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ComputeServiceServer).ReceiveVM(&computeServiceReceiveVMServer{ServerStream: stream})
}

type ComputeService_ReceiveVMServer interface {
	Send(*ReceiveVMResponse) error
	Recv() (*ReceiveVMRequest, error)
	grpc.ServerStream
}

type computeServiceReceiveVMServer struct {
	grpc.ServerStream
}

func (x *computeServiceReceiveVMServer) Send(m *ReceiveVMResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *computeServiceReceiveVMServer) Recv() (*ReceiveVMRequest, error) {
	m := new(ReceiveVMRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ComputeService_GrowDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrowDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).GrowDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_GrowDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).GrowDisk(ctx, req.(*GrowDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ComputeService_ServiceDesc is the grpc.ServiceDesc for ComputeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ComputeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "exe.compute.v1.ComputeService",
	HandlerType: (*ComputeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInstance",
			Handler:    _ComputeService_GetInstance_Handler,
		},
		{
			MethodName: "StartInstance",
			Handler:    _ComputeService_StartInstance_Handler,
		},
		{
			MethodName: "StopInstance",
			Handler:    _ComputeService_StopInstance_Handler,
		},
		{
			MethodName: "UpdateInstance",
			Handler:    _ComputeService_UpdateInstance_Handler,
		},
		{
			MethodName: "DeleteInstance",
			Handler:    _ComputeService_DeleteInstance_Handler,
		},
		{
			MethodName: "SetInstanceGroup",
			Handler:    _ComputeService_SetInstanceGroup_Handler,
		},
		{
			MethodName: "RenameInstance",
			Handler:    _ComputeService_RenameInstance_Handler,
		},
		{
			MethodName: "GetSystemInfo",
			Handler:    _ComputeService_GetSystemInfo_Handler,
		},
		{
			MethodName: "GrowDisk",
			Handler:    _ComputeService_GrowDisk_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateInstance",
			Handler:       _ComputeService_CreateInstance_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListInstances",
			Handler:       _ComputeService_ListInstances_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetInstanceLogs",
			Handler:       _ComputeService_GetInstanceLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SendVM",
			Handler:       _ComputeService_SendVM_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ReceiveVM",
			Handler:       _ComputeService_ReceiveVM_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "exe/compute/v1/compute.proto",
}
