ALTER TABLE servers ADD COLUMN agent_version TEXT NOT NULL DEFAULT '';
ALTER TABLE servers ADD COLUMN arch TEXT NOT NULL DEFAULT '';
ALTER TABLE servers ADD COLUMN upgrade_pending INTEGER NOT NULL DEFAULT 0;
