package notifications

import "time"

// EventType identifies the kind of notification event.
type EventType string

const (
	EventAgentDone  EventType = "agent_done"
	EventAgentError EventType = "agent_error"
)

// Event is a notification event generated by the system.
type Event struct {
	Type           EventType `json:"type"`
	ConversationID string    `json:"conversation_id"`
	Timestamp      time.Time `json:"timestamp"`
	Payload        any       `json:"payload,omitempty"`
}

// AgentDonePayload is the payload for EventAgentDone.
type AgentDonePayload struct {
	Model             string `json:"model,omitempty"`
	ConversationTitle string `json:"conversation_title,omitempty"`
	FinalResponse     string `json:"final_response,omitempty"`
}

// AgentErrorPayload is the payload for EventAgentError.
type AgentErrorPayload struct {
	ErrorMessage string `json:"error_message"`
}
