# THIS FILE IS UNDER SOURCE CONTROL at exe.git/observability/...

global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: "grafana"
    scheme: 'https'
    static_configs:
      - targets: ["grafana.crocodile-vector.ts.net"]
    metrics_path: '/metrics'

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'node'
    static_configs:
      - targets:
        - 'sketch-01:9100'
        - 'mon:9100'
        - 'sketch-dev:9100'
        - 'docker-01:9100'
        - 'docker-02:9100'
        - 'exed-01:19100'  # exed listens on most ports for proxy, so use 10000+9100
        - 'exe-ctr-01:9100'
        - 'ci.crocodile-vector.ts.net:9100'
        labels:
          stage: 'production'
      - targets:
        - 'exed-staging-01:19100'  # exed listens on most ports for proxy, so use 10000+9100
        - 'exe-ctr-staging-01:9100'
        labels:
          stage: 'staging'

  - job_name: 'cadvisor'
    static_configs:
      - targets:
        - 'docker-01:8080'
        - 'docker-02:8080'
        - 'exe-ctr-01:8080'
        labels:
          stage: 'production'
      - targets:
        - 'exe-ctr-staging-01:8080'
        labels:
          stage: 'staging'
    metrics_path: '/metrics'

  - job_name: 'authd'
    static_configs:
      - targets: ["sketch-01:3001"]
    metrics_path: '/authd/metrics'

  - job_name: 'merde'
    scheme: 'https'
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ["merde"]
    metrics_path: '/metrics'

  - job_name: 'skabandd'
    scheme: https
    static_configs:
      - targets: ["sketch-dev.crocodile-vector.ts.net"]
    metrics_path: '/debug/metrics'

  - job_name: 'exed'
    scheme: https
    static_configs:
      - targets: ["exed-01.crocodile-vector.ts.net"]
        labels:
          stage: 'production'
      - targets: ["exed-staging-01.crocodile-vector.ts.net"]
        labels:
          stage: 'staging'
    metrics_path: '/metrics'

  - job_name: 'sshpiperd'
    scheme: http
    static_configs:
      - targets: ["exed-01:30303"]
        labels:
          stage: 'production'
      - targets: ["exed-staging-01:30303"]
        labels:
          stage: 'staging'
    metrics_path: '/metrics'

  - job_name: 'exelet'
    scheme: http
    static_configs:
      - targets: ["exe-ctr-01:9081"]
        labels:
          stage: 'production'
      - targets: ["exe-ctr-staging-01:9081"]
        labels:
          stage: 'staging'
    metrics_path: '/metrics'
