// Auto-generated by shelley.exe.dev/cmd/go2ts.go
// Do not edit manually - regenerate with: go run ./cmd/go2ts -o ui/src/generated-types.ts

// DO NOT EDIT. This file is automatically generated.

export interface Conversation {
	conversation_id: string;
	slug: string | null;
	user_initiated: boolean;
	created_at: string;
	updated_at: string;
}

export interface Message {
	message_id: string;
	conversation_id: string;
	type: string;
	llm_data: string | null;
	user_data: string | null;
	usage_data: string | null;
	created_at: string;
}

export interface Usage {
	input_tokens: number;
	cache_creation_input_tokens: number;
	cache_read_input_tokens: number;
	output_tokens: number;
	cost_usd: number;
}

export type MessageType = 'user' | 'agent' | 'tool';
