package idea

import "exe.dev/exedb"

// SeedTemplates is the curated set of default idea templates.
var SeedTemplates = []exedb.InsertTemplateParams{
	{
		Slug:             "openclaw",
		Title:            "Openclaw",
		ShortDescription: "AI-powered remote development agent with web dashboard",
		Category:         "ai-ml",
		Prompt:           "ANTHROPIC_API_KEY=<fill-this-in>\n\nSet up Openclaw (https://openclaw.ai/) on this VM. Openclaw used to be called Moltbot and before that Clawdbot, so be aware if the executable or other docs still refer to those names. Use the non-interactive and accept-risk flags for openclaw onboarding. Add the supplied auth or token as needed. Configure nginx to forward from the default port 18789 to the root location on the default enabled site config, making sure to enable Websocket support. Pairing is done by \"openclaw devices list\" and \"openclaw device approve <request id>\". Make sure the dashboard shows that Openclaw's health is OK. exe.dev handles forwarding from port 8000 to port 80/443 and HTTPS for us, so the final \"reachable\" should be https://<vm-name>.exe.xyz without port specification.",
		IconURL:          "https://openclaw.ai/favicon.svg",
		Status:           "approved",
		Featured:         true,
		VMShortname:      "openclaw",
	},
	{
		Slug:             "marimo-notebook",
		Title:            "Marimo Notebook",
		ShortDescription: "Reactive Python notebook with built-in SQL support",
		Category:         "ai-ml",
		Image:            "marimo-team/marimo:latest-sql",
		IconURL:          "📓",
		Status:           "approved",
		Featured:         true,
		VMShortname:      "marimo",
	},
	{
		Slug:             "code-server",
		Title:            "VS Code in Browser",
		ShortDescription: "Full VS Code editor accessible from your browser",
		Category:         "dev-tools",
		Prompt:           "Install code-server (VS Code in the browser). Configure it to run on port 8000 with no authentication (exe.dev handles auth). Install common extensions: Python, Go, Rust, and GitLens. Set up the service to start on boot via systemd.",
		IconURL:          "💻",
		Status:           "approved",
		Featured:         true,
		VMShortname:      "vscode",
	},
	{
		Slug:             "ghost-blog",
		Title:            "Ghost Blog",
		ShortDescription: "Beautiful, modern publishing platform",
		Category:         "web-apps",
		Prompt:           "Install Ghost CMS following the official Ubuntu guide (https://docs.ghost.org/install/ubuntu). When configuring NGINX, do NOT set up SSL/TLS — exe.dev handles HTTPS termination for us. Configure Ghost to listen on port 8000 via NGINX. Use SQLite as the database backend for simplicity. Set up an initial admin account.\n\nAfter installation, configure Ghost to authenticate admin users via exe.dev's reverse proxy headers by writing a custom SSO adapter.\n\nGhost has a built-in SSO adapter system. Create a file at content/adapters/sso/ExeDevSSO.js that extends the base class at core/core/server/adapters/sso/SSOBase.js. The adapter must implement three async methods:\n\n- getRequestCredentials(req) — return req.headers['x-exedev-email'] or null\n- getIdentityFromCredentials(email) — return the email as-is\n- getUserForIdentity(email) — look up and return an active Ghost staff user by email using require('../../../core/server/models').User.findOne({email, status: 'active'})\n\nThen in config.production.json, activate it:\n\n{\"adapters\": {\"sso\": {\"active\": \"ExeDevSSO\"}}}\n\nGhost's admin middleware at /ghost already calls createSessionFromToken() on every request, which invokes the SSO adapter — so no route changes are needed. When the adapter returns a user, Ghost automatically creates a session cookie.\n\nMake sure the initial admin account's email matches the exe.dev user's email so SSO works immediately.",
		IconURL:          "👻",
		Status:           "approved",
		Featured:         false,
		VMShortname:      "ghost",
	},
	{
		Slug:             "minecraft-server",
		Title:            "Minecraft Server",
		ShortDescription: "Java Edition server with web map viewer",
		Category:         "games",
		Prompt:           "Install and configure a Minecraft Java Edition server. Install Java 21 (OpenJDK). Download the latest Minecraft server jar. Accept the EULA. Configure server.properties with reasonable defaults (max 10 players, normal difficulty). Set up a systemd service to run the server.\n\nInstall Dynmap and configure it on port 8000 so the live map is viewable from the web at https://<vm-name>.exe.xyz.\n\nInstall the playit.gg agent (https://github.com/playit-cloud/playit-agent) to tunnel the Minecraft port (25565) so players can connect from anywhere without port forwarding. Download the Linux amd64 binary, run it as a systemd service. On first run it prints a claim URL — the user must visit that URL to link the agent to their playit.gg account and create a Minecraft Java tunnel. After claiming, the agent writes its secret to playit.toml and connects automatically on restart.\n\nThe very last line of output from the setup MUST be exactly:\nMinecraft server is running. Open https://<vm-name>.exe.xyz for the live map. To connect in Minecraft, visit the claim URL above to get your playit.gg address, then add it as a server in Multiplayer.",
		IconURL:          "⛏️",
		Status:           "approved",
		Featured:         false,
		VMShortname:      "minecraft",
	},
	{
		Slug:             "gitea",
		Title:            "Gitea",
		ShortDescription: "Lightweight self-hosted Git service",
		Category:         "self-hosted",
		Prompt:           "Install Gitea, a lightweight self-hosted Git service. Download the latest Linux amd64 binary from https://dl.gitea.com/gitea/ and install it to /usr/local/bin. Use SQLite as the database. Run Gitea on port 8000 as a systemd service (User=git, WorkingDirectory=/var/lib/gitea).\n\nAuthentication: Use Gitea's built-in reverse proxy auth — exe.dev already sends X-ExeDev-Email and X-ExeDev-UserID on every request. In app.ini under [service], set:\n- ENABLE_REVERSE_PROXY_AUTHENTICATION = true\n- ENABLE_REVERSE_PROXY_AUTO_REGISTRATION = true\n- ENABLE_REVERSE_PROXY_EMAIL = true\n- REVERSE_PROXY_AUTHENTICATION_EMAIL = X-ExeDev-Email\nAnd under [service] set REVERSE_PROXY_AUTHENTICATION_USER to X-ExeDev-Email (Gitea will use the email as the username for auto-registration since we don't have a separate username header).\nAlso set DISABLE_REGISTRATION = true so only reverse-proxy auth works.\n\nThe first auto-registered user should be promoted to admin. After starting Gitea, use 'gitea admin user list' to find the user and 'gitea admin user change-password' or the Gitea CLI to set IsAdmin=true, or pre-create the admin account with 'gitea admin user create' using the VM owner's email before the first login.\n\nSee https://exe.dev/docs/login-with-exe for background on exe.dev's auth headers.",
		IconURL:          "☕",
		Status:           "approved",
		Featured:         false,
		VMShortname:      "gitea",
	},
	{
		Slug:             "outline-wiki",
		Title:            "Outline",
		ShortDescription: "Beautiful team wiki and knowledge base",
		Category:         "self-hosted",
		Prompt:           "Install Outline (https://github.com/outline/outline), the open-source wiki and knowledge base. Run it via Docker Compose with PostgreSQL and Redis on port 3000. Install exe-oidc-proxy (go install github.com/boldsoftware/exe-oidc-proxy@latest) as a systemd service proxying to Outline, with issuer https://<vm-name>.exe.xyz/_oidc. See https://exe.dev/docs/login-with-exe for background.\n\nArchitecture:\n- exe-oidc-proxy on port 8001\n- nginx on port 8000 (plain HTTP, for exe.dev proxy) → proxy to 8001\n- nginx on port 443 (SSL with self-signed cert, for Docker internal OIDC calls) → proxy to 8001\n- Outline on port 3000\n\nOutline environment:\n- URL=https://<vm-name>.exe.xyz\n- FORCE_HTTPS=false (exe.dev proxy terminates TLS)\n- OIDC_CLIENT_ID and OIDC_CLIENT_SECRET matching the proxy\n- OIDC_AUTH_URI=https://<vm-name>.exe.xyz/_oidc/auth\n- OIDC_TOKEN_URI=https://<vm-name>.exe.xyz/_oidc/token\n- OIDC_USERINFO_URI=https://<vm-name>.exe.xyz/_oidc/userinfo\n- OIDC_SCOPES=openid email profile\n- OIDC_DISPLAY_NAME=exe.dev\n- NODE_TLS_REJECT_UNAUTHORIZED=0 (for Docker's calls to self-signed nginx)\n\nOutline uses explicit OIDC URIs, not discovery. It does NOT need a JWKS or discovery endpoint.\n\nDocker networking: Outline's server-to-server OIDC calls (token exchange, userinfo) go to https://<vm-name>.exe.xyz which doesn't resolve from inside Docker. Use extra_hosts to map <vm-name>.exe.xyz to host-gateway, so requests go to nginx on port 443.",
		IconURL:          "📝",
		Status:           "approved",
		Featured:         false,
		VMShortname:      "outline",
	},
	{
		Slug:             "zulip-chat",
		Title:            "Zulip",
		ShortDescription: "Organized team chat with threaded conversations",
		Category:         "self-hosted",
		Prompt:           "Install Zulip using Docker (github.com/zulip/docker-zulip). Map Zulip to port 9080. Install exe-oidc-proxy (go install github.com/boldsoftware/exe-oidc-proxy@latest) as a systemd service on port 8000, proxying to Zulip on 9080, with issuer https://.exe.xyz/_oidc. See https://exe.dev/docs/login-with-exe for background. Set up an initial organization, disable invite_required on the realm, and pre-create the VM owner as realm owner (role=100) so their first OIDC login grants admin.\n\nNote:\n\nSOCIAL_AUTH_OIDC_ENABLED_IDPS is evaluated as Python, not JSON. The IDP dict MUST include \"secret\": get_secret(\"social_auth_oidc_secret\") — pass the value via a Docker secret named zulip__social_auth_oidc_secret. The IDP dict MUST also include \"oidc_url\" pointing to the issuer — Zulip reads the OIDC endpoint from there, not from a separate setting.\n\nexe-oidc-proxy signs JWTs with ES256. Zulip defaults to RS256. Set SETTING_SOCIAL_AUTH_OIDC_JWT_ALGORITHMS: '[\"ES256\"]'\n\nZulip's Smokescreen outbound proxy breaks OIDC. All uwsgi/worker processes have HTTP_proxy=http://localhost:4750 injected by Puppet via supervisor configs under /etc/supervisor/conf.d/zulip/. Create a /data/post-setup.d/ script (runs after Puppet, before supervisor) that uses find to sed no_proxy=\".exe.xyz\" into every supervisor .conf containing HTTP_proxy.\n\nThe OIDC discovery doc advertises https URLs for token/jwks/userinfo. Zulip calls these server-to-server from inside Docker. Use extra_hosts to resolve .exe.xyz to host-gateway, run nginx on host port 443 with a self-signed cert proxying to localhost:8000, and set SETTING_SOCIAL_AUTH_OIDC_VERIFY_SSL: \"False\" to skip cert verification.",
		IconURL:          "💬",
		Status:           "approved",
		Featured:         false,
		VMShortname:      "zulip",
	},
	{
		Slug:             "vaultwarden",
		Title:            "Vaultwarden",
		ShortDescription: "Self-hosted password manager compatible with Bitwarden clients",
		Category:         "self-hosted",
		Prompt:           "Install Vaultwarden with SSO via exe-oidc-proxy.\n\nArchitecture: exe-oidc-proxy (port 8000) → Vaultwarden (Docker --network=host, port 9080). nginx on port 443 for Vaultwarden's internal OIDC discovery calls.\n\nCritical: Vaultwarden uses rustls which ignores SSL_CERT_FILE. Self-signed certs fail silently. Use mkcert to generate certs, and include $(mkcert -CAROOT)/rootCA.pem in the CA bundle.\n\nNetworking: Add /etc/hosts entry mapping <vm-name>.exe.xyz → 127.0.0.1 so Docker resolves to localhost.\n\nNon-obvious SSO env vars: SSO_PKCE=false, SSO_AUTH_ONLY_NOT_SESSION=true, SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION=true (exe-oidc-proxy limitations).",
		IconURL:          "🔐",
		Status:           "approved",
		Featured:         false,
		VMShortname:      "vaultwarden",
	},
	{
		Slug:             "grafana-prometheus",
		Title:            "Grafana + Prometheus",
		ShortDescription: "Monitoring stack with dashboards and metrics collection",
		Category:         "self-hosted",
		Prompt:           "Install Grafana and Prometheus for a complete monitoring stack. Configure Prometheus to scrape its own metrics and node_exporter for system metrics. Set up Grafana on port 8000 with Prometheus pre-configured as a data source. Import the Node Exporter Full dashboard so there's something useful to look at right away. Configure Grafana to use exe.dev's auth proxy headers for authentication instead of its built-in login — set [auth.proxy] enabled=true with header_name=X-ExeDev-Email and header_property=email, and auto_sign_up=true. See https://exe.dev/docs/login-with-exe for details. Set up all services (Grafana, Prometheus, node_exporter) as systemd services.",
		IconURL:          "📈",
		Status:           "approved",
		Featured:         false,
		VMShortname:      "grafana",
	},
	{
		Slug:             "bitwarden",
		Title:            "Bitwarden",
		ShortDescription: "Self-hosted password manager using Vaultwarden",
		Category:         "self-hosted",
		Prompt:           "Install Vaultwarden (https://github.com/dani-garcia/vaultwarden), the lightweight self-hosted Bitwarden-compatible password manager server. Run it via Docker on port 8000. Enable the admin panel and set an admin token. Configure it with persistent storage for the database. Set up the Docker container as a systemd service so it starts on boot.",
		IconURL:          "🔐",
		Status:           "approved",
		Featured:         false,
		VMShortname:      "bitwarden",
	},
	{
		Slug:             "wekan",
		Title:            "WeKan",
		ShortDescription: "Open-source kanban board — Trello alternative",
		Category:         "self-hosted",
		Prompt:           "Install WeKan (https://github.com/wekan/wekan), the open-source kanban board. Run it via Docker on an internal port (e.g. 9080). Install exe-oidc-proxy (go install github.com/boldsoftware/exe-oidc-proxy@latest) as a systemd service on port 8000, proxying to WeKan, with issuer https://<vm-name>.exe.xyz/_oidc. See https://exe.dev/docs/login-with-exe for background. Configure WeKan's OAuth2 with OAUTH2_ENABLED=true, OAUTH2_CLIENT_ID and OAUTH2_SECRET matching the proxy, OAUTH2_SERVER_URL=https://<vm-name>.exe.xyz/_oidc, OAUTH2_AUTH_ENDPOINT=/authorize, OAUTH2_TOKEN_ENDPOINT=/token, OAUTH2_USERINFO_ENDPOINT=https://<vm-name>.exe.xyz/_oidc/userinfo, OAUTH2_ID_MAP=sub, OAUTH2_USERNAME_MAP=email, OAUTH2_EMAIL_MAP=email, OAUTH2_FULLNAME_MAP=email.\n\nDocker networking gotcha: WeKan's server-to-server OIDC calls (token exchange, userinfo) go to https://<vm-name>.exe.xyz which doesn't resolve from inside Docker. Use extra_hosts to map <vm-name>.exe.xyz to host-gateway, run nginx on host port 443 with a self-signed cert proxying to localhost:8000, and set NODE_TLS_REJECT_UNAUTHORIZED=0 or OAUTH2_CA_CERT as needed.",
		IconURL:          "📋",
		Status:           "approved",
		Featured:         false,
		VMShortname:      "wekan",
	},
	{
		Slug:             "planka",
		Title:            "Planka",
		ShortDescription: "Elegant kanban board for workgroups — Trello alternative",
		Category:         "self-hosted",
		Prompt:           "Install Planka (https://github.com/plankanban/planka), the elegant open-source kanban board. Run it via Docker Compose on port 1337. Install exe-oidc-proxy (go install github.com/boldsoftware/exe-oidc-proxy@latest) as a systemd service proxying to Planka, with issuer https://<vm-name>.exe.xyz/_oidc.\n\nArchitecture (use exe.dev's default proxy, no port in URLs):\n- exe-oidc-proxy on port 8001\n- nginx on port 8000 (plain HTTP, for exe.dev proxy) → proxy to 8001\n- nginx on port 443 (SSL with self-signed cert, for Docker internal OIDC calls) → proxy to 8001\n- Planka on port 1337\n\nPlanka environment:\n- BASE_URL=https://<vm-name>.exe.xyz (no port)\n- OIDC_ISSUER=https://<vm-name>.exe.xyz/_oidc (no port)\n- OIDC_CLIENT_ID and OIDC_CLIENT_SECRET matching the proxy\n- OIDC_SCOPES=openid email profile\n- OIDC_ENFORCED=true\n- OIDC_ID_TOKEN_SIGNED_RESPONSE_ALG=ES256 (exe-oidc-proxy uses ES256)\n- NODE_TLS_REJECT_UNAUTHORIZED=0 (for Docker's calls to self-signed nginx)\n- TERMS_TYPE=none (skip terms of service screen)\n\nDocker networking: Planka's server-to-server OIDC calls go to https://<vm-name>.exe.xyz which doesn't resolve from inside Docker. Use extra_hosts to map <vm-name>.exe.xyz to host-gateway, so requests go to nginx on port 443.\n\niptables persistence: Install iptables-persistent and save rules to /etc/iptables/rules.v4.",
		IconURL:          "🗒️",
		Status:           "approved",
		Featured:         false,
		VMShortname:      "planka",
	},
	{
		Slug:             "huly",
		Title:            "Huly",
		ShortDescription: "All-in-one project management platform — Linear alternative",
		Category:         "self-hosted",
		Prompt:           "Install Huly (https://github.com/hcengineering/huly-platform), the open-source all-in-one project management platform (a Linear/Jira alternative). Use the official self-hosting setup from https://github.com/hcengineering/huly-selfhost. Install exe-oidc-proxy (go install github.com/boldsoftware/exe-oidc-proxy@latest) as a systemd service on port 8000, proxying to Huly's front service port, with issuer https://<vm-name>.exe.xyz/_oidc. See https://exe.dev/docs/login-with-exe for background. Configure Huly's OIDC by adding OPENID_CLIENT_ID, OPENID_CLIENT_SECRET, and OPENID_ISSUER=https://<vm-name>.exe.xyz/_oidc to the account service environment in compose.yml. Make sure the account service callback URL is reachable from the browser.\n\nDocker networking gotcha: Huly's account service makes server-to-server OIDC calls (token exchange) to https://<vm-name>.exe.xyz which doesn't resolve from inside Docker. Use extra_hosts to map <vm-name>.exe.xyz to host-gateway, run nginx on host port 443 with a self-signed cert proxying to localhost:8000, and set NODE_TLS_REJECT_UNAUTHORIZED=0 in the account service environment to skip cert verification.",
		IconURL:          "🚀",
		Status:           "approved",
		Featured:         false,
		VMShortname:      "huly",
	},
	{
		Slug:             "gh-actions-runner",
		Title:            "GitHub Actions Runner",
		ShortDescription: "Self-hosted GitHub Actions runner with persistent disk",
		Category:         "dev-tools",
		Prompt:           "GITHUB_TOKEN=<fill-this-in>\nGITHUB_REPO_OR_ORG_URL=<fill-this-in>\n\nSet up a self-hosted GitHub Actions runner.\n\nGITHUB_TOKEN must be a classic Personal Access Token with `repo` scope (create one at https://github.com/settings/tokens/new with the `repo` checkbox). Fine-grained tokens with `administration:write` permission on the repo also work.\n\nGITHUB_REPO_OR_ORG_URL is the GitHub URL to register the runner against, e.g.:\n- https://github.com/myuser/myrepo (for a single repo)\n- https://github.com/myorg (for an entire organization)\n\nDownload the latest GitHub Actions runner for Linux x64 from https://github.com/actions/runner/releases. Extract it to /home/exedev/actions-runner.\n\nRegister the runner using the --pat flag, which lets config.sh exchange the PAT for a registration token automatically:\n  ./config.sh --url $GITHUB_REPO_OR_ORG_URL --pat $GITHUB_TOKEN --unattended --name <vm-name> --replace\n\nSet up a systemd service that runs /home/exedev/actions-runner/run.sh so it starts on boot and auto-restarts.",
		IconURL:          "⚙️",
		Status:           "approved",
		Featured:         false,
		VMShortname:      "gh-runner",
	},
}
