// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package exedb

import (
	"context"
	"time"
)

const activateAccount = `-- name: ActivateAccount :exec
INSERT INTO billing_events (account_id, event_type, event_at)
SELECT id, 'active', ?2 FROM accounts WHERE created_by = ?1
`

type ActivateAccountParams struct {
	CreatedBy string    `db:"created_by" json:"created_by"`
	EventAt   time.Time `db:"event_at" json:"event_at"`
}

// ActivateAccount marks an account as active after Stripe checkout completes.
// Inserts an 'active' billing event for the account owned by the given user.
// Timestamp should be normalized to Time10 format by caller.
func (q *Queries) ActivateAccount(ctx context.Context, arg ActivateAccountParams) error {
	_, err := q.exec(ctx, q.activateAccountStmt, activateAccount, arg.CreatedBy, arg.EventAt)
	return err
}

const clearAccountParentID = `-- name: ClearAccountParentID :exec
UPDATE accounts SET parent_id = NULL WHERE created_by = ?
`

// Clears the parent_id on a user's account when they leave a team.
func (q *Queries) ClearAccountParentID(ctx context.Context, createdBy string) error {
	_, err := q.exec(ctx, q.clearAccountParentIDStmt, clearAccountParentID, createdBy)
	return err
}

const closeAccountPlan = `-- name: CloseAccountPlan :exec
UPDATE account_plans SET ended_at = ?2 WHERE account_id = ?1 AND ended_at IS NULL
`

type CloseAccountPlanParams struct {
	AccountID string     `db:"account_id" json:"account_id"`
	EndedAt   *time.Time `db:"ended_at" json:"ended_at"`
}

func (q *Queries) CloseAccountPlan(ctx context.Context, arg CloseAccountPlanParams) error {
	_, err := q.exec(ctx, q.closeAccountPlanStmt, closeAccountPlan, arg.AccountID, arg.EndedAt)
	return err
}

const closeAccountPlansByPlanID = `-- name: CloseAccountPlansByPlanID :exec
UPDATE account_plans SET ended_at = ?2 WHERE plan_id = ?1 AND ended_at IS NULL
`

type CloseAccountPlansByPlanIDParams struct {
	PlanID  string     `db:"plan_id" json:"plan_id"`
	EndedAt *time.Time `db:"ended_at" json:"ended_at"`
}

// CloseAccountPlansByPlanID closes all active plans with the given plan_id.
func (q *Queries) CloseAccountPlansByPlanID(ctx context.Context, arg CloseAccountPlansByPlanIDParams) error {
	_, err := q.exec(ctx, q.closeAccountPlansByPlanIDStmt, closeAccountPlansByPlanID, arg.PlanID, arg.EndedAt)
	return err
}

const countAccountsByBillingStatus = `-- name: CountAccountsByBillingStatus :one
SELECT COUNT(*) FROM accounts a
WHERE (
    ?1 = 'pending' AND NOT EXISTS (SELECT 1 FROM billing_events WHERE account_id = a.id)
) OR (
    ?1 != 'pending' AND EXISTS (
        SELECT 1 FROM billing_events e1
        WHERE e1.account_id = a.id
        AND e1.event_type = ?1
        AND e1.id = (
            SELECT e2.id FROM billing_events e2
            WHERE e2.account_id = a.id
            ORDER BY parse_timestamp(e2.event_at) DESC, e2.id DESC
            LIMIT 1
        )
    )
)
`

// CountAccountsByBillingStatus counts accounts with the given billing status.
// For 'active' or 'canceled', counts accounts whose most recent billing event matches.
// For 'pending', counts accounts with no billing events.
func (q *Queries) CountAccountsByBillingStatus(ctx context.Context, dollar_1 interface{}) (int64, error) {
	row := q.queryRow(ctx, q.countAccountsByBillingStatusStmt, countAccountsByBillingStatus, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAccountsWithoutActivePlan = `-- name: CountAccountsWithoutActivePlan :one
SELECT COUNT(*) FROM accounts a
WHERE NOT EXISTS (
    SELECT 1 FROM account_plans ap
    WHERE ap.account_id = a.id AND ap.ended_at IS NULL
)
`

// CountAccountsWithoutActivePlan counts accounts that have no active (ended_at IS NULL) plan row.
func (q *Queries) CountAccountsWithoutActivePlan(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countAccountsWithoutActivePlanStmt, countAccountsWithoutActivePlan)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAccountsWithoutUser = `-- name: CountAccountsWithoutUser :one
SELECT COUNT(*) FROM accounts a
WHERE NOT EXISTS (
    SELECT 1 FROM users u WHERE u.user_id = a.created_by
)
`

// CountAccountsWithoutUser counts accounts whose created_by user no longer exists.
func (q *Queries) CountAccountsWithoutUser(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countAccountsWithoutUserStmt, countAccountsWithoutUser)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllAccounts = `-- name: CountAllAccounts :one
SELECT COUNT(*) FROM accounts
`

func (q *Queries) CountAllAccounts(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countAllAccountsStmt, countAllAccounts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAccountsByUserID = `-- name: DeleteAccountsByUserID :exec
DELETE FROM accounts WHERE created_by = ?
`

func (q *Queries) DeleteAccountsByUserID(ctx context.Context, createdBy string) error {
	_, err := q.exec(ctx, q.deleteAccountsByUserIDStmt, deleteAccountsByUserID, createdBy)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, created_by, created_at, parent_id, status FROM accounts WHERE id = ?
`

func (q *Queries) GetAccount(ctx context.Context, id string) (Account, error) {
	row := q.queryRow(ctx, q.getAccountStmt, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ParentID,
		&i.Status,
	)
	return i, err
}

const getAccountByUserID = `-- name: GetAccountByUserID :one
SELECT id, created_by, created_at, parent_id, status FROM accounts WHERE created_by = ?
`

func (q *Queries) GetAccountByUserID(ctx context.Context, createdBy string) (Account, error) {
	row := q.queryRow(ctx, q.getAccountByUserIDStmt, getAccountByUserID, createdBy)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ParentID,
		&i.Status,
	)
	return i, err
}

const getAccountWithBillingStatus = `-- name: GetAccountWithBillingStatus :one
SELECT a.id, a.created_by, a.created_at,
    CAST(COALESCE(
        (SELECT e.event_type FROM billing_events e
         WHERE e.account_id = a.id
         ORDER BY parse_timestamp(e.event_at) DESC, e.id DESC LIMIT 1),
        'pending'
    ) AS TEXT) AS billing_status
FROM accounts a WHERE a.created_by = ?
`

type GetAccountWithBillingStatusRow struct {
	ID            string    `db:"id" json:"id"`
	CreatedBy     string    `db:"created_by" json:"created_by"`
	CreatedAt     time.Time `db:"created_at" json:"created_at"`
	BillingStatus string    `db:"billing_status" json:"billing_status"`
}

// Returns account info with billing status derived from billing_events.
// billing_status is 'pending' if no events, otherwise the most recent event_type.
func (q *Queries) GetAccountWithBillingStatus(ctx context.Context, createdBy string) (GetAccountWithBillingStatusRow, error) {
	row := q.queryRow(ctx, q.getAccountWithBillingStatusStmt, getAccountWithBillingStatus, createdBy)
	var i GetAccountWithBillingStatusRow
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.BillingStatus,
	)
	return i, err
}

const getActiveAccountPlan = `-- name: GetActiveAccountPlan :one
SELECT account_id, plan_id, started_at, ended_at, trial_expires_at, changed_by, created_at
FROM account_plans
WHERE account_id = ? AND ended_at IS NULL
`

func (q *Queries) GetActiveAccountPlan(ctx context.Context, accountID string) (AccountPlan, error) {
	row := q.queryRow(ctx, q.getActiveAccountPlanStmt, getActiveAccountPlan, accountID)
	var i AccountPlan
	err := row.Scan(
		&i.AccountID,
		&i.PlanID,
		&i.StartedAt,
		&i.EndedAt,
		&i.TrialExpiresAt,
		&i.ChangedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getActivePlanForUser = `-- name: GetActivePlanForUser :one
SELECT
    COALESCE(parent_ap.plan_id, own_ap.plan_id) AS plan_id,
    COALESCE(parent_ap.account_id, own_ap.account_id) AS account_id
FROM users u
JOIN accounts a ON a.created_by = u.user_id
JOIN account_plans own_ap ON own_ap.account_id = a.id AND own_ap.ended_at IS NULL
LEFT JOIN accounts parent_acct ON parent_acct.id = a.parent_id
LEFT JOIN account_plans parent_ap ON parent_ap.account_id = parent_acct.id AND parent_ap.ended_at IS NULL
WHERE u.user_id = ?
`

type GetActivePlanForUserRow struct {
	PlanID    string `db:"plan_id" json:"plan_id"`
	AccountID string `db:"account_id" json:"account_id"`
}

// Resolves a user's effective plan. If parent_id is set, uses parent's plan.
// trial_expires_at is excluded because COALESCE returns it as a string
// that the Go SQLite driver cannot scan into *time.Time.
func (q *Queries) GetActivePlanForUser(ctx context.Context, userID string) (GetActivePlanForUserRow, error) {
	row := q.queryRow(ctx, q.getActivePlanForUserStmt, getActivePlanForUser, userID)
	var i GetActivePlanForUserRow
	err := row.Scan(&i.PlanID, &i.AccountID)
	return i, err
}

const getTeamBillingOwnerAccountID = `-- name: GetTeamBillingOwnerAccountID :one
SELECT a.id
FROM accounts a
JOIN team_members tm_billing ON a.created_by = tm_billing.user_id
JOIN team_members tm_user ON tm_billing.team_id = tm_user.team_id
WHERE tm_user.user_id = ?1
AND tm_billing.role = 'billing_owner'
`

// GetTeamBillingOwnerAccountID returns the billing account ID of the user's team billing_owner.
func (q *Queries) GetTeamBillingOwnerAccountID(ctx context.Context, memberUserID string) (string, error) {
	row := q.queryRow(ctx, q.getTeamBillingOwnerAccountIDStmt, getTeamBillingOwnerAccountID, memberUserID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getUserBilling = `-- name: GetUserBilling :one
SELECT
    CASE
        WHEN u.billing_exemption = 'free' THEN 'friend'
        WHEN EXISTS (
            SELECT 1 FROM accounts a
            JOIN billing_events e ON e.account_id = a.id
            WHERE a.created_by = ?1
            AND e.event_type = 'active'
            AND e.id = (
                SELECT e2.id FROM billing_events e2
                WHERE e2.account_id = a.id
                ORDER BY parse_timestamp(e2.event_at) DESC, e2.id DESC
                LIMIT 1
            )
        ) THEN 'has_billing'
        WHEN EXISTS (
            SELECT 1 FROM team_members tm_user
            JOIN team_members tm_billing ON tm_user.team_id = tm_billing.team_id
            JOIN accounts a ON a.created_by = tm_billing.user_id
            JOIN billing_events e ON e.account_id = a.id
            WHERE tm_user.user_id = ?1
            AND tm_billing.role = 'billing_owner'
            AND e.event_type = 'active'
            AND e.id = (
                SELECT e2.id FROM billing_events e2
                WHERE e2.account_id = a.id
                ORDER BY parse_timestamp(e2.event_at) DESC, e2.id DESC
                LIMIT 1
            )
        ) THEN 'has_billing'
        ELSE 'no_billing'
    END AS category,
    CAST(COALESCE(
        CASE
            WHEN EXISTS (
                SELECT 1 FROM accounts a
                JOIN billing_events e ON e.account_id = a.id
                WHERE a.created_by = u.user_id
                AND e.event_type = 'active'
                AND e.id = (
                    SELECT e2.id FROM billing_events e2
                    WHERE e2.account_id = a.id
                    ORDER BY parse_timestamp(e2.event_at) DESC, e2.id DESC
                    LIMIT 1
                )
            ) THEN 'active'
            WHEN EXISTS (
                SELECT 1 FROM accounts a
                JOIN billing_events e ON e.account_id = a.id
                WHERE a.created_by = u.user_id
                AND e.event_type = 'canceled'
                AND e.id = (
                    SELECT e2.id FROM billing_events e2
                    WHERE e2.account_id = a.id
                    ORDER BY parse_timestamp(e2.event_at) DESC, e2.id DESC
                    LIMIT 1
                )
            ) THEN 'canceled'
        END,
    '') AS TEXT) AS billing_status,
    u.email,
    u.created_at,
    u.billing_exemption,
    u.billing_trial_ends_at
FROM users u
WHERE u.user_id = ?1
`

type GetUserBillingRow struct {
	Category           string     `db:"category" json:"category"`
	BillingStatus      string     `db:"billing_status" json:"billing_status"`
	Email              string     `db:"email" json:"email"`
	CreatedAt          *time.Time `db:"created_at" json:"created_at"`
	BillingExemption   *string    `db:"billing_exemption" json:"billing_exemption"`
	BillingTrialEndsAt *time.Time `db:"billing_trial_ends_at" json:"billing_trial_ends_at"`
}

// GetUserBilling returns a single row with the user's plan category, billing status,
// account creation date, billing exemption, and trial end date.
// Combines GetUserBillingStatus and GetUserPlanCategory into one round trip.
func (q *Queries) GetUserBilling(ctx context.Context, createdBy string) (GetUserBillingRow, error) {
	row := q.queryRow(ctx, q.getUserBillingStmt, getUserBilling, createdBy)
	var i GetUserBillingRow
	err := row.Scan(
		&i.Category,
		&i.BillingStatus,
		&i.Email,
		&i.CreatedAt,
		&i.BillingExemption,
		&i.BillingTrialEndsAt,
	)
	return i, err
}

const getUserBillingStatus = `-- name: GetUserBillingStatus :one
SELECT
    CASE
        WHEN EXISTS (
            SELECT 1 FROM accounts a
            JOIN billing_events e ON e.account_id = a.id
            WHERE a.created_by = u.user_id
            AND e.event_type = 'active'
            AND e.id = (
                SELECT e2.id FROM billing_events e2
                WHERE e2.account_id = a.id
                ORDER BY parse_timestamp(e2.event_at) DESC, e2.id DESC
                LIMIT 1
            )
        ) THEN 'active'
        WHEN EXISTS (
            SELECT 1 FROM accounts a
            JOIN billing_events e ON e.account_id = a.id
            WHERE a.created_by = u.user_id
            AND e.event_type = 'canceled'
            AND e.id = (
                SELECT e2.id FROM billing_events e2
                WHERE e2.account_id = a.id
                ORDER BY parse_timestamp(e2.event_at) DESC, e2.id DESC
                LIMIT 1
            )
        ) THEN 'canceled'
        ELSE ''
    END AS billing_status,
    u.created_at,
    u.billing_exemption,
    u.billing_trial_ends_at
FROM users u
WHERE u.user_id = ?1
`

type GetUserBillingStatusRow struct {
	BillingStatus      string     `db:"billing_status" json:"billing_status"`
	CreatedAt          *time.Time `db:"created_at" json:"created_at"`
	BillingExemption   *string    `db:"billing_exemption" json:"billing_exemption"`
	BillingTrialEndsAt *time.Time `db:"billing_trial_ends_at" json:"billing_trial_ends_at"`
}

// Returns the user's billing information for determining payment status.
// billing_status is 'active' if ANY account has active billing as its most recent event,
// 'canceled' if ANY account has canceled as its most recent event (and none have active),
// or empty string if no billing events exist.
// This handles users with multiple accounts correctly by checking across all accounts.
func (q *Queries) GetUserBillingStatus(ctx context.Context, userID string) (GetUserBillingStatusRow, error) {
	row := q.queryRow(ctx, q.getUserBillingStatusStmt, getUserBillingStatus, userID)
	var i GetUserBillingStatusRow
	err := row.Scan(
		&i.BillingStatus,
		&i.CreatedAt,
		&i.BillingExemption,
		&i.BillingTrialEndsAt,
	)
	return i, err
}

const getUserIDByAccountID = `-- name: GetUserIDByAccountID :one
SELECT created_by FROM accounts WHERE id = ?
`

// Returns the user_id of the account owner.
func (q *Queries) GetUserIDByAccountID(ctx context.Context, id string) (string, error) {
	row := q.queryRow(ctx, q.getUserIDByAccountIDStmt, getUserIDByAccountID, id)
	var created_by string
	err := row.Scan(&created_by)
	return created_by, err
}

const getUserPlanCategory = `-- name: GetUserPlanCategory :one
SELECT
    CASE
        WHEN u.billing_exemption = 'free' THEN 'friend'
        WHEN EXISTS (
            SELECT 1 FROM accounts a
            JOIN billing_events e ON e.account_id = a.id
            WHERE a.created_by = ?1
            AND e.event_type = 'active'
            AND e.id = (
                SELECT e2.id FROM billing_events e2
                WHERE e2.account_id = a.id
                ORDER BY parse_timestamp(e2.event_at) DESC, e2.id DESC
                LIMIT 1
            )
        ) THEN 'has_billing'
        WHEN EXISTS (
            SELECT 1 FROM team_members tm_user
            JOIN team_members tm_billing ON tm_user.team_id = tm_billing.team_id
            JOIN accounts a ON a.created_by = tm_billing.user_id
            JOIN billing_events e ON e.account_id = a.id
            WHERE tm_user.user_id = ?1
            AND tm_billing.role = 'billing_owner'
            AND e.event_type = 'active'
            AND e.id = (
                SELECT e2.id FROM billing_events e2
                WHERE e2.account_id = a.id
                ORDER BY parse_timestamp(e2.event_at) DESC, e2.id DESC
                LIMIT 1
            )
        ) THEN 'has_billing'
        ELSE 'no_billing'
    END
FROM users u WHERE u.user_id = ?1
`

// GetUserPlanCategory determines the user's plan category for LLM gateway credit limits.
// Returns 'friend' if user has billing_exemption='free'
// Returns 'has_billing' if user has an active billing account (most recent billing event is 'active'),
//
//	or if user's team billing_owner has an active billing account
//
// Returns 'no_billing' otherwise
// Note: 'custom' category is determined by checking for explicit overrides in code, not SQL.
func (q *Queries) GetUserPlanCategory(ctx context.Context, createdBy string) (string, error) {
	row := q.queryRow(ctx, q.getUserPlanCategoryStmt, getUserPlanCategory, createdBy)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const insertAccount = `-- name: InsertAccount :exec
INSERT OR IGNORE INTO accounts (id, created_by) VALUES (?, ?)
`

type InsertAccountParams struct {
	ID        string `db:"id" json:"id"`
	CreatedBy string `db:"created_by" json:"created_by"`
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) error {
	_, err := q.exec(ctx, q.insertAccountStmt, insertAccount, arg.ID, arg.CreatedBy)
	return err
}

const insertAccountPlan = `-- name: InsertAccountPlan :exec
INSERT INTO account_plans (account_id, plan_id, started_at, trial_expires_at, changed_by)
VALUES (?, ?, ?, ?, ?)
`

type InsertAccountPlanParams struct {
	AccountID      string     `db:"account_id" json:"account_id"`
	PlanID         string     `db:"plan_id" json:"plan_id"`
	StartedAt      time.Time  `db:"started_at" json:"started_at"`
	TrialExpiresAt *time.Time `db:"trial_expires_at" json:"trial_expires_at"`
	ChangedBy      *string    `db:"changed_by" json:"changed_by"`
}

func (q *Queries) InsertAccountPlan(ctx context.Context, arg InsertAccountPlanParams) error {
	_, err := q.exec(ctx, q.insertAccountPlanStmt, insertAccountPlan,
		arg.AccountID,
		arg.PlanID,
		arg.StartedAt,
		arg.TrialExpiresAt,
		arg.ChangedBy,
	)
	return err
}

const insertAccountPlanMigration = `-- name: InsertAccountPlanMigration :exec
INSERT INTO account_plans (account_id, plan_id, started_at, changed_by)
VALUES (?, ?, ?, ?)
`

type InsertAccountPlanMigrationParams struct {
	AccountID string    `db:"account_id" json:"account_id"`
	PlanID    string    `db:"plan_id" json:"plan_id"`
	StartedAt time.Time `db:"started_at" json:"started_at"`
	ChangedBy *string   `db:"changed_by" json:"changed_by"`
}

// InsertAccountPlanMigration inserts a new plan row during a plan version migration.
func (q *Queries) InsertAccountPlanMigration(ctx context.Context, arg InsertAccountPlanMigrationParams) error {
	_, err := q.exec(ctx, q.insertAccountPlanMigrationStmt, insertAccountPlanMigration,
		arg.AccountID,
		arg.PlanID,
		arg.StartedAt,
		arg.ChangedBy,
	)
	return err
}

const listAccountPlanHistory = `-- name: ListAccountPlanHistory :many
SELECT account_id, plan_id, started_at, ended_at, trial_expires_at, changed_by, created_at
FROM account_plans
WHERE account_id = ?
ORDER BY started_at DESC
`

func (q *Queries) ListAccountPlanHistory(ctx context.Context, accountID string) ([]AccountPlan, error) {
	rows, err := q.query(ctx, q.listAccountPlanHistoryStmt, listAccountPlanHistory, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountPlan{}
	for rows.Next() {
		var i AccountPlan
		if err := rows.Scan(
			&i.AccountID,
			&i.PlanID,
			&i.StartedAt,
			&i.EndedAt,
			&i.TrialExpiresAt,
			&i.ChangedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSubscribersByPlanID = `-- name: ListActiveSubscribersByPlanID :many
SELECT account_id
FROM account_plans
WHERE plan_id = ? AND ended_at IS NULL
ORDER BY started_at
`

// ListActiveSubscribersByPlanID returns all account IDs with the given active plan.
func (q *Queries) ListActiveSubscribersByPlanID(ctx context.Context, planID string) ([]string, error) {
	rows, err := q.query(ctx, q.listActiveSubscribersByPlanIDStmt, listActiveSubscribersByPlanID, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var account_id string
		if err := rows.Scan(&account_id); err != nil {
			return nil, err
		}
		items = append(items, account_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAccounts = `-- name: ListAllAccounts :many
SELECT id, created_by, created_at, parent_id, status FROM accounts
`

func (q *Queries) ListAllAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.query(ctx, q.listAllAccountsStmt, listAllAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ParentID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredStripeTrialPlans = `-- name: ListExpiredStripeTrialPlans :many
SELECT account_id, plan_id, started_at, ended_at, trial_expires_at, changed_by, created_at
FROM account_plans
WHERE plan_id = 'trial' AND ended_at IS NULL AND trial_expires_at IS NOT NULL AND trial_expires_at < ?
  AND (changed_by IS NULL OR changed_by NOT LIKE 'invite:%')
`

// Returns active Stripe trial plans that have expired (trial_expires_at in the past).
// Excludes invite-code trials (changed_by starts with 'invite:') which have their own terms.
func (q *Queries) ListExpiredStripeTrialPlans(ctx context.Context, trialExpiresAt *time.Time) ([]AccountPlan, error) {
	rows, err := q.query(ctx, q.listExpiredStripeTrialPlansStmt, listExpiredStripeTrialPlans, trialExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountPlan{}
	for rows.Next() {
		var i AccountPlan
		if err := rows.Scan(
			&i.AccountID,
			&i.PlanID,
			&i.StartedAt,
			&i.EndedAt,
			&i.TrialExpiresAt,
			&i.ChangedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanVersionCounts = `-- name: ListPlanVersionCounts :many
SELECT plan_id, COUNT(*) as cnt
FROM account_plans
WHERE ended_at IS NULL
GROUP BY plan_id
ORDER BY cnt DESC, plan_id
`

type ListPlanVersionCountsRow struct {
	PlanID string `db:"plan_id" json:"plan_id"`
	Cnt    int64  `db:"cnt" json:"cnt"`
}

// ListPlanVersionCounts returns all active plan versions with subscriber counts.
func (q *Queries) ListPlanVersionCounts(ctx context.Context) ([]ListPlanVersionCountsRow, error) {
	rows, err := q.query(ctx, q.listPlanVersionCountsStmt, listPlanVersionCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlanVersionCountsRow{}
	for rows.Next() {
		var i ListPlanVersionCountsRow
		if err := rows.Scan(&i.PlanID, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAccountParentID = `-- name: SetAccountParentID :exec
UPDATE accounts SET parent_id = ?2 WHERE created_by = ?1
`

type SetAccountParentIDParams struct {
	CreatedBy string  `db:"created_by" json:"created_by"`
	ParentID  *string `db:"parent_id" json:"parent_id"`
}

// Sets the parent_id on a user's account to link them to a team billing owner's account.
func (q *Queries) SetAccountParentID(ctx context.Context, arg SetAccountParentIDParams) error {
	_, err := q.exec(ctx, q.setAccountParentIDStmt, setAccountParentID, arg.CreatedBy, arg.ParentID)
	return err
}

const setTrialExpiresAt = `-- name: SetTrialExpiresAt :exec
UPDATE account_plans
SET trial_expires_at = ?2
WHERE account_id = ?1 AND ended_at IS NULL AND changed_by = 'stripe:event'
`

type SetTrialExpiresAtParams struct {
	AccountID      string     `db:"account_id" json:"account_id"`
	TrialExpiresAt *time.Time `db:"trial_expires_at" json:"trial_expires_at"`
}

// SetTrialExpiresAt updates trial_expires_at for an active Stripe-managed plan.
// Only updates rows where changed_by='stripe:event' to avoid modifying invite trials.
func (q *Queries) SetTrialExpiresAt(ctx context.Context, arg SetTrialExpiresAtParams) error {
	_, err := q.exec(ctx, q.setTrialExpiresAtStmt, setTrialExpiresAt, arg.AccountID, arg.TrialExpiresAt)
	return err
}

const upsertAccountPlan = `-- name: UpsertAccountPlan :exec
INSERT OR IGNORE INTO account_plans (account_id, plan_id, started_at, trial_expires_at, changed_by)
VALUES (?, ?, ?, ?, ?)
`

type UpsertAccountPlanParams struct {
	AccountID      string     `db:"account_id" json:"account_id"`
	PlanID         string     `db:"plan_id" json:"plan_id"`
	StartedAt      time.Time  `db:"started_at" json:"started_at"`
	TrialExpiresAt *time.Time `db:"trial_expires_at" json:"trial_expires_at"`
	ChangedBy      *string    `db:"changed_by" json:"changed_by"`
}

// UpsertAccountPlan inserts an account plan only if the account has no active plan.
func (q *Queries) UpsertAccountPlan(ctx context.Context, arg UpsertAccountPlanParams) error {
	_, err := q.exec(ctx, q.upsertAccountPlanStmt, upsertAccountPlan,
		arg.AccountID,
		arg.PlanID,
		arg.StartedAt,
		arg.TrialExpiresAt,
		arg.ChangedBy,
	)
	return err
}
