// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: allocs.sql

package exedb

import (
	"context"
)

const allocExistsForUser = `-- name: AllocExistsForUser :one
SELECT EXISTS(SELECT 1 FROM allocs WHERE user_id = ?)
`

func (q *Queries) AllocExistsForUser(ctx context.Context, userID string) (int64, error) {
	row := q.queryRow(ctx, q.allocExistsForUserStmt, allocExistsForUser, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getAllocBillingInfo = `-- name: GetAllocBillingInfo :one
SELECT billing_account_id
FROM allocs WHERE alloc_id = ?
`

func (q *Queries) GetAllocBillingInfo(ctx context.Context, allocID string) (string, error) {
	row := q.queryRow(ctx, q.getAllocBillingInfoStmt, getAllocBillingInfo, allocID)
	var billing_account_id string
	err := row.Scan(&billing_account_id)
	return billing_account_id, err
}

const getAllocByUserID = `-- name: GetAllocByUserID :one
SELECT alloc_id, user_id, alloc_type, region, ctrhost, created_at, billing_account_id
FROM allocs
WHERE user_id = ?
LIMIT 1
`

func (q *Queries) GetAllocByUserID(ctx context.Context, userID string) (Alloc, error) {
	row := q.queryRow(ctx, q.getAllocByUserIDStmt, getAllocByUserID, userID)
	var i Alloc
	err := row.Scan(
		&i.AllocID,
		&i.UserID,
		&i.AllocType,
		&i.Region,
		&i.Ctrhost,
		&i.CreatedAt,
		&i.BillingAccountID,
	)
	return i, err
}

const getAllocsByHost = `-- name: GetAllocsByHost :many
SELECT alloc_id, user_id, alloc_type, region, ctrhost, created_at, billing_account_id
FROM allocs
WHERE ctrhost = ?
`

func (q *Queries) GetAllocsByHost(ctx context.Context, ctrhost string) ([]Alloc, error) {
	rows, err := q.query(ctx, q.getAllocsByHostStmt, getAllocsByHost, ctrhost)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alloc{}
	for rows.Next() {
		var i Alloc
		if err := rows.Scan(
			&i.AllocID,
			&i.UserID,
			&i.AllocType,
			&i.Region,
			&i.Ctrhost,
			&i.CreatedAt,
			&i.BillingAccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCtrhostByAllocID = `-- name: GetCtrhostByAllocID :one
SELECT ctrhost FROM allocs WHERE alloc_id = ?
`

func (q *Queries) GetCtrhostByAllocID(ctx context.Context, allocID string) (string, error) {
	row := q.queryRow(ctx, q.getCtrhostByAllocIDStmt, getCtrhostByAllocID, allocID)
	var ctrhost string
	err := row.Scan(&ctrhost)
	return ctrhost, err
}

const insertAlloc = `-- name: InsertAlloc :exec
INSERT INTO allocs (alloc_id, user_id, alloc_type, region, ctrhost, billing_account_id)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertAllocParams struct {
	AllocID          string `db:"alloc_id" json:"alloc_id"`
	UserID           string `db:"user_id" json:"user_id"`
	AllocType        string `db:"alloc_type" json:"alloc_type"`
	Region           string `db:"region" json:"region"`
	Ctrhost          string `db:"ctrhost" json:"ctrhost"`
	BillingAccountID string `db:"billing_account_id" json:"billing_account_id"`
}

func (q *Queries) InsertAlloc(ctx context.Context, arg InsertAllocParams) error {
	_, err := q.exec(ctx, q.insertAllocStmt, insertAlloc,
		arg.AllocID,
		arg.UserID,
		arg.AllocType,
		arg.Region,
		arg.Ctrhost,
		arg.BillingAccountID,
	)
	return err
}

const updateAllocBillingAccount = `-- name: UpdateAllocBillingAccount :exec
UPDATE allocs SET billing_account_id = ? WHERE alloc_id = ?
`

type UpdateAllocBillingAccountParams struct {
	BillingAccountID string `db:"billing_account_id" json:"billing_account_id"`
	AllocID          string `db:"alloc_id" json:"alloc_id"`
}

func (q *Queries) UpdateAllocBillingAccount(ctx context.Context, arg UpdateAllocBillingAccountParams) error {
	_, err := q.exec(ctx, q.updateAllocBillingAccountStmt, updateAllocBillingAccount, arg.BillingAccountID, arg.AllocID)
	return err
}
