// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: allocs.sql

package exedb

import (
	"context"
)

const allocExistsForUser = `-- name: AllocExistsForUser :one
SELECT EXISTS(SELECT 1 FROM allocs WHERE user_id = ?)
`

func (q *Queries) AllocExistsForUser(ctx context.Context, userID string) (int64, error) {
	row := q.queryRow(ctx, q.allocExistsForUserStmt, allocExistsForUser, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getAllocsByHost = `-- name: GetAllocsByHost :many
SELECT alloc_id, user_id, alloc_type, region, ctrhost, created_at, stripe_customer_id, billing_email
FROM allocs
WHERE ctrhost = ?
`

func (q *Queries) GetAllocsByHost(ctx context.Context, ctrhost string) ([]Alloc, error) {
	rows, err := q.query(ctx, q.getAllocsByHostStmt, getAllocsByHost, ctrhost)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alloc{}
	for rows.Next() {
		var i Alloc
		if err := rows.Scan(
			&i.AllocID,
			&i.UserID,
			&i.AllocType,
			&i.Region,
			&i.Ctrhost,
			&i.CreatedAt,
			&i.StripeCustomerID,
			&i.BillingEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAlloc = `-- name: InsertAlloc :exec
INSERT INTO allocs (alloc_id, user_id, alloc_type, region, ctrhost, billing_email)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertAllocParams struct {
	AllocID      string  `db:"alloc_id" json:"alloc_id"`
	UserID       string  `db:"user_id" json:"user_id"`
	AllocType    string  `db:"alloc_type" json:"alloc_type"`
	Region       string  `db:"region" json:"region"`
	Ctrhost      string  `db:"ctrhost" json:"ctrhost"`
	BillingEmail *string `db:"billing_email" json:"billing_email"`
}

func (q *Queries) InsertAlloc(ctx context.Context, arg InsertAllocParams) error {
	_, err := q.exec(ctx, q.insertAllocStmt, insertAlloc,
		arg.AllocID,
		arg.UserID,
		arg.AllocType,
		arg.Region,
		arg.Ctrhost,
		arg.BillingEmail,
	)
	return err
}
