// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_cookies.sql

package exedb

import (
	"context"
	"time"
)

const deleteAuthCookie = `-- name: DeleteAuthCookie :exec
DELETE FROM auth_cookies WHERE cookie_value = ?
`

func (q *Queries) DeleteAuthCookie(ctx context.Context, cookieValue string) error {
	_, err := q.exec(ctx, q.deleteAuthCookieStmt, deleteAuthCookie, cookieValue)
	return err
}

const deleteAuthCookieByValue = `-- name: DeleteAuthCookieByValue :exec
DELETE FROM auth_cookies WHERE cookie_value = ?
`

func (q *Queries) DeleteAuthCookieByValue(ctx context.Context, cookieValue string) error {
	_, err := q.exec(ctx, q.deleteAuthCookieByValueStmt, deleteAuthCookieByValue, cookieValue)
	return err
}

const deleteAuthCookiesByUserID = `-- name: DeleteAuthCookiesByUserID :exec
DELETE FROM auth_cookies WHERE user_id = ?
`

func (q *Queries) DeleteAuthCookiesByUserID(ctx context.Context, userID string) error {
	_, err := q.exec(ctx, q.deleteAuthCookiesByUserIDStmt, deleteAuthCookiesByUserID, userID)
	return err
}

const getAuthCookieInfo = `-- name: GetAuthCookieInfo :one
SELECT user_id, expires_at
FROM auth_cookies
WHERE cookie_value = ? AND domain = ?
`

type GetAuthCookieInfoParams struct {
	CookieValue string `db:"cookie_value" json:"cookie_value"`
	Domain      string `db:"domain" json:"domain"`
}

type GetAuthCookieInfoRow struct {
	UserID    string    `db:"user_id" json:"user_id"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
}

func (q *Queries) GetAuthCookieInfo(ctx context.Context, arg GetAuthCookieInfoParams) (GetAuthCookieInfoRow, error) {
	row := q.queryRow(ctx, q.getAuthCookieInfoStmt, getAuthCookieInfo, arg.CookieValue, arg.Domain)
	var i GetAuthCookieInfoRow
	err := row.Scan(&i.UserID, &i.ExpiresAt)
	return i, err
}

const insertAuthCookie = `-- name: InsertAuthCookie :exec
INSERT INTO auth_cookies (cookie_value, user_id, domain, expires_at)
VALUES (?, ?, ?, ?)
`

type InsertAuthCookieParams struct {
	CookieValue string    `db:"cookie_value" json:"cookie_value"`
	UserID      string    `db:"user_id" json:"user_id"`
	Domain      string    `db:"domain" json:"domain"`
	ExpiresAt   time.Time `db:"expires_at" json:"expires_at"`
}

func (q *Queries) InsertAuthCookie(ctx context.Context, arg InsertAuthCookieParams) error {
	_, err := q.exec(ctx, q.insertAuthCookieStmt, insertAuthCookie,
		arg.CookieValue,
		arg.UserID,
		arg.Domain,
		arg.ExpiresAt,
	)
	return err
}

const updateAuthCookieLastUsed = `-- name: UpdateAuthCookieLastUsed :exec
UPDATE auth_cookies SET last_used_at = CURRENT_TIMESTAMP WHERE cookie_value = ?
`

func (q *Queries) UpdateAuthCookieLastUsed(ctx context.Context, cookieValue string) error {
	_, err := q.exec(ctx, q.updateAuthCookieLastUsedStmt, updateAuthCookieLastUsed, cookieValue)
	return err
}

const userHasAuthCookie = `-- name: UserHasAuthCookie :one
SELECT EXISTS (
    SELECT 1
    FROM auth_cookies
    WHERE user_id = ?
      AND expires_at > CURRENT_TIMESTAMP
)
`

func (q *Queries) UserHasAuthCookie(ctx context.Context, userID string) (int64, error) {
	row := q.queryRow(ctx, q.userHasAuthCookieStmt, userHasAuthCookie, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
