// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing_events.sql

package exedb

import (
	"context"
	"time"
)

const getLatestBillingStatus = `-- name: GetLatestBillingStatus :one
SELECT event_type FROM billing_events WHERE account_id = ? ORDER BY parse_timestamp(event_at) DESC, id DESC LIMIT 1
`

func (q *Queries) GetLatestBillingStatus(ctx context.Context, accountID string) (string, error) {
	row := q.queryRow(ctx, q.getLatestBillingStatusStmt, getLatestBillingStatus, accountID)
	var event_type string
	err := row.Scan(&event_type)
	return event_type, err
}

const insertBillingEvent = `-- name: InsertBillingEvent :exec
INSERT OR IGNORE INTO billing_events (account_id, event_type, event_at, stripe_event_id) VALUES (?, ?, ?, ?)
`

type InsertBillingEventParams struct {
	AccountID     string    `db:"account_id" json:"account_id"`
	EventType     string    `db:"event_type" json:"event_type"`
	EventAt       time.Time `db:"event_at" json:"event_at"`
	StripeEventID *string   `db:"stripe_event_id" json:"stripe_event_id"`
}

// event_at should be a string in Time10 format (YYYY-MM-DD HH:MM:SS.nnnnnnnnn-HH:MM)
// to ensure consistent storage and comparison. Use sqlite.FormatTime(t) to format.
// stripe_event_id provides idempotent dedup for Stripe-sourced events;
// NULL for non-Stripe inserts (checkout, debug), which still dedup via
// the (account_id, event_type, event_at) unique index.
func (q *Queries) InsertBillingEvent(ctx context.Context, arg InsertBillingEventParams) error {
	_, err := q.exec(ctx, q.insertBillingEventStmt, insertBillingEvent,
		arg.AccountID,
		arg.EventType,
		arg.EventAt,
		arg.StripeEventID,
	)
	return err
}

const listBillingEventsForAccount = `-- name: ListBillingEventsForAccount :many
SELECT id, account_id, event_type, event_at, created_at
FROM billing_events WHERE account_id = ?
ORDER BY id DESC
`

type ListBillingEventsForAccountRow struct {
	ID        int64     `db:"id" json:"id"`
	AccountID string    `db:"account_id" json:"account_id"`
	EventType string    `db:"event_type" json:"event_type"`
	EventAt   time.Time `db:"event_at" json:"event_at"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) ListBillingEventsForAccount(ctx context.Context, accountID string) ([]ListBillingEventsForAccountRow, error) {
	rows, err := q.query(ctx, q.listBillingEventsForAccountStmt, listBillingEventsForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBillingEventsForAccountRow{}
	for rows.Next() {
		var i ListBillingEventsForAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.EventType,
			&i.EventAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionEvents = `-- name: ListSubscriptionEvents :many
SELECT account_id, event_type, event_at
FROM billing_events
WHERE account_id = ?
ORDER BY event_at ASC
`

type ListSubscriptionEventsRow struct {
	AccountID string    `db:"account_id" json:"account_id"`
	EventType string    `db:"event_type" json:"event_type"`
	EventAt   time.Time `db:"event_at" json:"event_at"`
}

// ListSubscriptionEvents returns subscription events for an account, ordered by time ascending.
func (q *Queries) ListSubscriptionEvents(ctx context.Context, accountID string) ([]ListSubscriptionEventsRow, error) {
	rows, err := q.query(ctx, q.listSubscriptionEventsStmt, listSubscriptionEvents, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubscriptionEventsRow{}
	for rows.Next() {
		var i ListSubscriptionEventsRow
		if err := rows.Scan(&i.AccountID, &i.EventType, &i.EventAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
