// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: box_shares.sql

package exedb

import (
	"context"
	"time"
)

const countBoxShares = `-- name: CountBoxShares :one
SELECT COUNT(*) as share_count
FROM box_shares
WHERE box_id = ?
`

func (q *Queries) CountBoxShares(ctx context.Context, boxID int64) (int64, error) {
	row := q.queryRow(ctx, q.countBoxSharesStmt, countBoxShares, boxID)
	var share_count int64
	err := row.Scan(&share_count)
	return share_count, err
}

const countBoxSharesByUser = `-- name: CountBoxSharesByUser :many
SELECT bs.box_id, COUNT(*) as share_count
FROM box_shares bs
JOIN boxes b ON bs.box_id = b.id
WHERE b.created_by_user_id = ? AND b.status != 'failed'
GROUP BY bs.box_id
`

type CountBoxSharesByUserRow struct {
	BoxID      int64 `db:"box_id" json:"box_id"`
	ShareCount int64 `db:"share_count" json:"share_count"`
}

func (q *Queries) CountBoxSharesByUser(ctx context.Context, createdByUserID string) ([]CountBoxSharesByUserRow, error) {
	rows, err := q.query(ctx, q.countBoxSharesByUserStmt, countBoxSharesByUser, createdByUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountBoxSharesByUserRow{}
	for rows.Next() {
		var i CountBoxSharesByUserRow
		if err := rows.Scan(&i.BoxID, &i.ShareCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createBoxShare = `-- name: CreateBoxShare :one
INSERT INTO box_shares (
    box_id,
    shared_with_user_id,
    shared_by_user_id,
    message
) VALUES (?, ?, ?, ?)
RETURNING id, box_id, shared_with_user_id, shared_by_user_id, message, created_at
`

type CreateBoxShareParams struct {
	BoxID            int64   `db:"box_id" json:"box_id"`
	SharedWithUserID string  `db:"shared_with_user_id" json:"shared_with_user_id"`
	SharedByUserID   string  `db:"shared_by_user_id" json:"shared_by_user_id"`
	Message          *string `db:"message" json:"message"`
}

func (q *Queries) CreateBoxShare(ctx context.Context, arg CreateBoxShareParams) (BoxShare, error) {
	row := q.queryRow(ctx, q.createBoxShareStmt, createBoxShare,
		arg.BoxID,
		arg.SharedWithUserID,
		arg.SharedByUserID,
		arg.Message,
	)
	var i BoxShare
	err := row.Scan(
		&i.ID,
		&i.BoxID,
		&i.SharedWithUserID,
		&i.SharedByUserID,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBoxShareByBoxAndUser = `-- name: DeleteBoxShareByBoxAndUser :exec
DELETE FROM box_shares
WHERE box_id = ? AND shared_with_user_id = ?
`

type DeleteBoxShareByBoxAndUserParams struct {
	BoxID            int64  `db:"box_id" json:"box_id"`
	SharedWithUserID string `db:"shared_with_user_id" json:"shared_with_user_id"`
}

func (q *Queries) DeleteBoxShareByBoxAndUser(ctx context.Context, arg DeleteBoxShareByBoxAndUserParams) error {
	_, err := q.exec(ctx, q.deleteBoxShareByBoxAndUserStmt, deleteBoxShareByBoxAndUser, arg.BoxID, arg.SharedWithUserID)
	return err
}

const deleteBoxSharesByBox = `-- name: DeleteBoxSharesByBox :exec
DELETE FROM box_shares WHERE box_id = ?
`

func (q *Queries) DeleteBoxSharesByBox(ctx context.Context, boxID int64) error {
	_, err := q.exec(ctx, q.deleteBoxSharesByBoxStmt, deleteBoxSharesByBox, boxID)
	return err
}

const getBoxShareEmailsByUser = `-- name: GetBoxShareEmailsByUser :many
SELECT bs.box_id, u.email as shared_with_user_email
FROM box_shares bs
JOIN boxes b ON bs.box_id = b.id
JOIN users u ON bs.shared_with_user_id = u.user_id
WHERE b.created_by_user_id = ?
AND b.status != 'failed'
ORDER BY bs.box_id, bs.created_at DESC
`

type GetBoxShareEmailsByUserRow struct {
	BoxID               int64  `db:"box_id" json:"box_id"`
	SharedWithUserEmail string `db:"shared_with_user_email" json:"shared_with_user_email"`
}

func (q *Queries) GetBoxShareEmailsByUser(ctx context.Context, createdByUserID string) ([]GetBoxShareEmailsByUserRow, error) {
	rows, err := q.query(ctx, q.getBoxShareEmailsByUserStmt, getBoxShareEmailsByUser, createdByUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBoxShareEmailsByUserRow{}
	for rows.Next() {
		var i GetBoxShareEmailsByUserRow
		if err := rows.Scan(&i.BoxID, &i.SharedWithUserEmail); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBoxSharesByBoxID = `-- name: GetBoxSharesByBoxID :many
SELECT bs.id, bs.box_id, bs.shared_with_user_id, bs.shared_by_user_id, bs.message, bs.created_at, u.email as shared_with_user_email
FROM box_shares bs
JOIN users u ON bs.shared_with_user_id = u.user_id
WHERE bs.box_id = ?
ORDER BY bs.created_at DESC
`

type GetBoxSharesByBoxIDRow struct {
	ID                  int64      `db:"id" json:"id"`
	BoxID               int64      `db:"box_id" json:"box_id"`
	SharedWithUserID    string     `db:"shared_with_user_id" json:"shared_with_user_id"`
	SharedByUserID      string     `db:"shared_by_user_id" json:"shared_by_user_id"`
	Message             *string    `db:"message" json:"message"`
	CreatedAt           *time.Time `db:"created_at" json:"created_at"`
	SharedWithUserEmail string     `db:"shared_with_user_email" json:"shared_with_user_email"`
}

func (q *Queries) GetBoxSharesByBoxID(ctx context.Context, boxID int64) ([]GetBoxSharesByBoxIDRow, error) {
	rows, err := q.query(ctx, q.getBoxSharesByBoxIDStmt, getBoxSharesByBoxID, boxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBoxSharesByBoxIDRow{}
	for rows.Next() {
		var i GetBoxSharesByBoxIDRow
		if err := rows.Scan(
			&i.ID,
			&i.BoxID,
			&i.SharedWithUserID,
			&i.SharedByUserID,
			&i.Message,
			&i.CreatedAt,
			&i.SharedWithUserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBoxesSharedWithUser = `-- name: GetBoxesSharedWithUser :many
SELECT 
    b.id,
    b.name,
    b.status,
    b.image,
    b.created_at,
    b.routes,
    bs.message,
    bs.created_at as shared_at,
    owner.email as owner_email
FROM boxes b
JOIN box_shares bs ON b.id = bs.box_id
JOIN users owner ON b.created_by_user_id = owner.user_id
WHERE bs.shared_with_user_id = ?
ORDER BY bs.created_at DESC
`

type GetBoxesSharedWithUserRow struct {
	ID         int        `db:"id" json:"id"`
	Name       string     `db:"name" json:"name"`
	Status     string     `db:"status" json:"status"`
	Image      string     `db:"image" json:"image"`
	CreatedAt  *time.Time `db:"created_at" json:"created_at"`
	Routes     *string    `db:"routes" json:"routes"`
	Message    *string    `db:"message" json:"message"`
	SharedAt   *time.Time `db:"shared_at" json:"shared_at"`
	OwnerEmail string     `db:"owner_email" json:"owner_email"`
}

func (q *Queries) GetBoxesSharedWithUser(ctx context.Context, sharedWithUserID string) ([]GetBoxesSharedWithUserRow, error) {
	rows, err := q.query(ctx, q.getBoxesSharedWithUserStmt, getBoxesSharedWithUser, sharedWithUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBoxesSharedWithUserRow{}
	for rows.Next() {
		var i GetBoxesSharedWithUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Image,
			&i.CreatedAt,
			&i.Routes,
			&i.Message,
			&i.SharedAt,
			&i.OwnerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasUserAccessToBox = `-- name: HasUserAccessToBox :one
SELECT COUNT(*) > 0 as has_access
FROM box_shares
WHERE box_id = ? AND shared_with_user_id = ?
`

type HasUserAccessToBoxParams struct {
	BoxID            int64  `db:"box_id" json:"box_id"`
	SharedWithUserID string `db:"shared_with_user_id" json:"shared_with_user_id"`
}

func (q *Queries) HasUserAccessToBox(ctx context.Context, arg HasUserAccessToBoxParams) (bool, error) {
	row := q.queryRow(ctx, q.hasUserAccessToBoxStmt, hasUserAccessToBox, arg.BoxID, arg.SharedWithUserID)
	var has_access bool
	err := row.Scan(&has_access)
	return has_access, err
}
