// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: boxes.sql

package exedb

import (
	"context"
	"time"
)

const boxNamed = `-- name: BoxNamed :one
SELECT id, name, status, image, ctrhost, container_id, created_by_user_id, created_at, updated_at, last_started_at, routes, ssh_server_identity_key, ssh_authorized_keys, ssh_client_private_key, ssh_port, ssh_user, creation_log, support_access_allowed FROM boxes WHERE name = ?
`

// This is not a secure API!
// Whenever possible, use an alternative method that also checks the alloc/user and/or returns less data.
func (q *Queries) BoxNamed(ctx context.Context, name string) (Box, error) {
	row := q.queryRow(ctx, q.boxNamedStmt, boxNamed, name)
	var i Box
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Image,
		&i.Ctrhost,
		&i.ContainerID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastStartedAt,
		&i.Routes,
		&i.SSHServerIdentityKey,
		&i.SSHAuthorizedKeys,
		&i.SSHClientPrivateKey,
		&i.SSHPort,
		&i.SSHUser,
		&i.CreationLog,
		&i.SupportAccessAllowed,
	)
	return i, err
}

const boxWithNameExists = `-- name: BoxWithNameExists :one
SELECT EXISTS ( SELECT 1 FROM boxes WHERE name = ? )
`

func (q *Queries) BoxWithNameExists(ctx context.Context, name string) (int64, error) {
	row := q.queryRow(ctx, q.boxWithNameExistsStmt, boxWithNameExists, name)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const boxWithOwnerNamed = `-- name: BoxWithOwnerNamed :one
SELECT id, name, status, image, ctrhost, container_id, created_by_user_id, created_at, updated_at, last_started_at, routes, ssh_server_identity_key, ssh_authorized_keys, ssh_client_private_key, ssh_port, ssh_user, creation_log, support_access_allowed FROM boxes WHERE name = ? AND boxes.created_by_user_id = ?
`

type BoxWithOwnerNamedParams struct {
	Name            string `db:"name" json:"name"`
	CreatedByUserID string `db:"created_by_user_id" json:"created_by_user_id"`
}

func (q *Queries) BoxWithOwnerNamed(ctx context.Context, arg BoxWithOwnerNamedParams) (Box, error) {
	row := q.queryRow(ctx, q.boxWithOwnerNamedStmt, boxWithOwnerNamed, arg.Name, arg.CreatedByUserID)
	var i Box
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Image,
		&i.Ctrhost,
		&i.ContainerID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastStartedAt,
		&i.Routes,
		&i.SSHServerIdentityKey,
		&i.SSHAuthorizedKeys,
		&i.SSHClientPrivateKey,
		&i.SSHPort,
		&i.SSHUser,
		&i.CreationLog,
		&i.SupportAccessAllowed,
	)
	return i, err
}

const boxesForUser = `-- name: BoxesForUser :many
SELECT id, name, status, image, ctrhost, container_id, created_by_user_id, created_at, updated_at, last_started_at, routes, ssh_server_identity_key, ssh_authorized_keys, ssh_client_private_key, ssh_port, ssh_user, creation_log, support_access_allowed
FROM boxes
WHERE created_by_user_id = ?
ORDER BY updated_at DESC, id DESC
`

func (q *Queries) BoxesForUser(ctx context.Context, createdByUserID string) ([]Box, error) {
	rows, err := q.query(ctx, q.boxesForUserStmt, boxesForUser, createdByUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Box{}
	for rows.Next() {
		var i Box
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Image,
			&i.Ctrhost,
			&i.ContainerID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastStartedAt,
			&i.Routes,
			&i.SSHServerIdentityKey,
			&i.SSHAuthorizedKeys,
			&i.SSHClientPrivateKey,
			&i.SSHPort,
			&i.SSHUser,
			&i.CreationLog,
			&i.SupportAccessAllowed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countBoxes = `-- name: CountBoxes :one
SELECT COUNT(*) FROM boxes
`

func (q *Queries) CountBoxes(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countBoxesStmt, countBoxes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBoxesForUser = `-- name: CountBoxesForUser :one
SELECT COUNT(*) FROM boxes WHERE created_by_user_id = ?
`

func (q *Queries) CountBoxesForUser(ctx context.Context, createdByUserID string) (int64, error) {
	row := q.queryRow(ctx, q.countBoxesForUserStmt, countBoxesForUser, createdByUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersWithBoxes = `-- name: CountUsersWithBoxes :one
SELECT COUNT(DISTINCT created_by_user_id) FROM boxes
`

func (q *Queries) CountUsersWithBoxes(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countUsersWithBoxesStmt, countUsersWithBoxes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBox = `-- name: DeleteBox :exec
DELETE FROM boxes WHERE id = ?
`

func (q *Queries) DeleteBox(ctx context.Context, id int) error {
	_, err := q.exec(ctx, q.deleteBoxStmt, deleteBox, id)
	return err
}

const getBoxByNameAndAlloc = `-- name: GetBoxByNameAndAlloc :one
SELECT id, name, status, image, ctrhost, container_id, created_by_user_id, created_at, updated_at, last_started_at, routes, ssh_server_identity_key, ssh_authorized_keys, ssh_client_private_key, ssh_port, ssh_user, creation_log, support_access_allowed FROM boxes WHERE name = ? AND created_by_user_id = ?
`

type GetBoxByNameAndAllocParams struct {
	Name            string `db:"name" json:"name"`
	CreatedByUserID string `db:"created_by_user_id" json:"created_by_user_id"`
}

func (q *Queries) GetBoxByNameAndAlloc(ctx context.Context, arg GetBoxByNameAndAllocParams) (Box, error) {
	row := q.queryRow(ctx, q.getBoxByNameAndAllocStmt, getBoxByNameAndAlloc, arg.Name, arg.CreatedByUserID)
	var i Box
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Image,
		&i.Ctrhost,
		&i.ContainerID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastStartedAt,
		&i.Routes,
		&i.SSHServerIdentityKey,
		&i.SSHAuthorizedKeys,
		&i.SSHClientPrivateKey,
		&i.SSHPort,
		&i.SSHUser,
		&i.CreationLog,
		&i.SupportAccessAllowed,
	)
	return i, err
}

const getBoxByNameWithSupportAccess = `-- name: GetBoxByNameWithSupportAccess :one
SELECT id, name, status, image, ctrhost, container_id, created_by_user_id, created_at, updated_at, last_started_at, routes, ssh_server_identity_key, ssh_authorized_keys, ssh_client_private_key, ssh_port, ssh_user, creation_log, support_access_allowed FROM boxes WHERE name = ? AND support_access_allowed = 1
`

func (q *Queries) GetBoxByNameWithSupportAccess(ctx context.Context, name string) (Box, error) {
	row := q.queryRow(ctx, q.getBoxByNameWithSupportAccessStmt, getBoxByNameWithSupportAccess, name)
	var i Box
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Image,
		&i.Ctrhost,
		&i.ContainerID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastStartedAt,
		&i.Routes,
		&i.SSHServerIdentityKey,
		&i.SSHAuthorizedKeys,
		&i.SSHClientPrivateKey,
		&i.SSHPort,
		&i.SSHUser,
		&i.CreationLog,
		&i.SupportAccessAllowed,
	)
	return i, err
}

const getBoxDetailsForSetup = `-- name: GetBoxDetailsForSetup :one
SELECT container_id, created_by_user_id, name, image
FROM boxes WHERE id = ?
`

type GetBoxDetailsForSetupRow struct {
	ContainerID     *string `db:"container_id" json:"container_id"`
	CreatedByUserID string  `db:"created_by_user_id" json:"created_by_user_id"`
	Name            string  `db:"name" json:"name"`
	Image           string  `db:"image" json:"image"`
}

func (q *Queries) GetBoxDetailsForSetup(ctx context.Context, id int) (GetBoxDetailsForSetupRow, error) {
	row := q.queryRow(ctx, q.getBoxDetailsForSetupStmt, getBoxDetailsForSetup, id)
	var i GetBoxDetailsForSetupRow
	err := row.Scan(
		&i.ContainerID,
		&i.CreatedByUserID,
		&i.Name,
		&i.Image,
	)
	return i, err
}

const getBoxOwnerByContainerID = `-- name: GetBoxOwnerByContainerID :one
SELECT u.user_id, u.email
FROM boxes b
JOIN users u ON u.user_id = b.created_by_user_id
WHERE b.container_id = ?
`

type GetBoxOwnerByContainerIDRow struct {
	UserID string `db:"user_id" json:"user_id"`
	Email  string `db:"email" json:"email"`
}

func (q *Queries) GetBoxOwnerByContainerID(ctx context.Context, containerID *string) (GetBoxOwnerByContainerIDRow, error) {
	row := q.queryRow(ctx, q.getBoxOwnerByContainerIDStmt, getBoxOwnerByContainerID, containerID)
	var i GetBoxOwnerByContainerIDRow
	err := row.Scan(&i.UserID, &i.Email)
	return i, err
}

const getBoxSSHDetails = `-- name: GetBoxSSHDetails :one
SELECT m.ssh_port, m.ssh_client_private_key, m.ssh_server_identity_key, m.ctrhost, m.ssh_user
FROM boxes m
WHERE m.id = ?
`

type GetBoxSSHDetailsRow struct {
	SSHPort              *int64  `db:"ssh_port" json:"ssh_port"`
	SSHClientPrivateKey  []byte  `db:"ssh_client_private_key" json:"ssh_client_private_key"`
	SSHServerIdentityKey []byte  `db:"ssh_server_identity_key" json:"ssh_server_identity_key"`
	Ctrhost              string  `db:"ctrhost" json:"ctrhost"`
	SSHUser              *string `db:"ssh_user" json:"ssh_user"`
}

func (q *Queries) GetBoxSSHDetails(ctx context.Context, id int) (GetBoxSSHDetailsRow, error) {
	row := q.queryRow(ctx, q.getBoxSSHDetailsStmt, getBoxSSHDetails, id)
	var i GetBoxSSHDetailsRow
	err := row.Scan(
		&i.SSHPort,
		&i.SSHClientPrivateKey,
		&i.SSHServerIdentityKey,
		&i.Ctrhost,
		&i.SSHUser,
	)
	return i, err
}

const getBoxSupportAccessAllowed = `-- name: GetBoxSupportAccessAllowed :one
SELECT support_access_allowed FROM boxes WHERE id = ?
`

func (q *Queries) GetBoxSupportAccessAllowed(ctx context.Context, id int) (int64, error) {
	row := q.queryRow(ctx, q.getBoxSupportAccessAllowedStmt, getBoxSupportAccessAllowed, id)
	var support_access_allowed int64
	err := row.Scan(&support_access_allowed)
	return support_access_allowed, err
}

const getBoxesByHost = `-- name: GetBoxesByHost :many
SELECT b.id, b.name, b.status, b.image, b.ctrhost, b.container_id, b.created_by_user_id, b.created_at, b.updated_at, b.last_started_at, b.routes, b.ssh_server_identity_key, b.ssh_authorized_keys, b.ssh_client_private_key, b.ssh_port, b.ssh_user, b.creation_log, b.support_access_allowed
FROM boxes b
WHERE b.ctrhost = ? AND b.status != 'failed'
`

func (q *Queries) GetBoxesByHost(ctx context.Context, ctrhost string) ([]Box, error) {
	rows, err := q.query(ctx, q.getBoxesByHostStmt, getBoxesByHost, ctrhost)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Box{}
	for rows.Next() {
		var i Box
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Image,
			&i.Ctrhost,
			&i.ContainerID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastStartedAt,
			&i.Routes,
			&i.SSHServerIdentityKey,
			&i.SSHAuthorizedKeys,
			&i.SSHClientPrivateKey,
			&i.SSHPort,
			&i.SSHUser,
			&i.CreationLog,
			&i.SupportAccessAllowed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBoxesForUserDashboard = `-- name: GetBoxesForUserDashboard :many
SELECT m.id, m.name, m.status, COALESCE(m.image, '') as image,
       COALESCE(m.container_id, '') as container_id, m.created_by_user_id,
       m.created_at, m.updated_at, m.last_started_at,
       COALESCE(m.creation_log, '') as creation_log, m.routes
FROM boxes m
WHERE m.created_by_user_id = ? AND m.status != 'failed'
ORDER BY m.updated_at DESC
`

type GetBoxesForUserDashboardRow struct {
	ID              int        `db:"id" json:"id"`
	Name            string     `db:"name" json:"name"`
	Status          string     `db:"status" json:"status"`
	Image           string     `db:"image" json:"image"`
	ContainerID     string     `db:"container_id" json:"container_id"`
	CreatedByUserID string     `db:"created_by_user_id" json:"created_by_user_id"`
	CreatedAt       *time.Time `db:"created_at" json:"created_at"`
	UpdatedAt       *time.Time `db:"updated_at" json:"updated_at"`
	LastStartedAt   *time.Time `db:"last_started_at" json:"last_started_at"`
	CreationLog     string     `db:"creation_log" json:"creation_log"`
	Routes          *string    `db:"routes" json:"routes"`
}

func (q *Queries) GetBoxesForUserDashboard(ctx context.Context, createdByUserID string) ([]GetBoxesForUserDashboardRow, error) {
	rows, err := q.query(ctx, q.getBoxesForUserDashboardStmt, getBoxesForUserDashboard, createdByUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBoxesForUserDashboardRow{}
	for rows.Next() {
		var i GetBoxesForUserDashboardRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Image,
			&i.ContainerID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastStartedAt,
			&i.CreationLog,
			&i.Routes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBox = `-- name: InsertBox :execlastid
INSERT INTO boxes (
    ctrhost, name, status, image, container_id, created_by_user_id, routes
) VALUES (?, ?, ?, ?, NULL, ?, ?)
`

type InsertBoxParams struct {
	Ctrhost         string  `db:"ctrhost" json:"ctrhost"`
	Name            string  `db:"name" json:"name"`
	Status          string  `db:"status" json:"status"`
	Image           string  `db:"image" json:"image"`
	CreatedByUserID string  `db:"created_by_user_id" json:"created_by_user_id"`
	Routes          *string `db:"routes" json:"routes"`
}

func (q *Queries) InsertBox(ctx context.Context, arg InsertBoxParams) (int64, error) {
	result, err := q.exec(ctx, q.insertBoxStmt, insertBox,
		arg.Ctrhost,
		arg.Name,
		arg.Status,
		arg.Image,
		arg.CreatedByUserID,
		arg.Routes,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const listAllBoxesWithOwner = `-- name: ListAllBoxesWithOwner :many
SELECT b.name, b.status, b.ctrhost, b.container_id, b.created_by_user_id as owner_user_id, u.email as owner_email
FROM boxes b
JOIN users u ON u.user_id = b.created_by_user_id
ORDER BY b.name
`

type ListAllBoxesWithOwnerRow struct {
	Name        string  `db:"name" json:"name"`
	Status      string  `db:"status" json:"status"`
	Ctrhost     string  `db:"ctrhost" json:"ctrhost"`
	ContainerID *string `db:"container_id" json:"container_id"`
	OwnerUserID string  `db:"owner_user_id" json:"owner_user_id"`
	OwnerEmail  string  `db:"owner_email" json:"owner_email"`
}

func (q *Queries) ListAllBoxesWithOwner(ctx context.Context) ([]ListAllBoxesWithOwnerRow, error) {
	rows, err := q.query(ctx, q.listAllBoxesWithOwnerStmt, listAllBoxesWithOwner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllBoxesWithOwnerRow{}
	for rows.Next() {
		var i ListAllBoxesWithOwnerRow
		if err := rows.Scan(
			&i.Name,
			&i.Status,
			&i.Ctrhost,
			&i.ContainerID,
			&i.OwnerUserID,
			&i.OwnerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sSHKeyForBoxNamed = `-- name: SSHKeyForBoxNamed :one
SELECT ssh_server_identity_key FROM boxes WHERE name = ?
`

func (q *Queries) SSHKeyForBoxNamed(ctx context.Context, name string) ([]byte, error) {
	row := q.queryRow(ctx, q.sSHKeyForBoxNamedStmt, sSHKeyForBoxNamed, name)
	var ssh_server_identity_key []byte
	err := row.Scan(&ssh_server_identity_key)
	return ssh_server_identity_key, err
}

const setBoxSupportAccessAllowed = `-- name: SetBoxSupportAccessAllowed :exec
UPDATE boxes SET support_access_allowed = ? WHERE id = ?
`

type SetBoxSupportAccessAllowedParams struct {
	SupportAccessAllowed int64 `db:"support_access_allowed" json:"support_access_allowed"`
	ID                   int   `db:"id" json:"id"`
}

func (q *Queries) SetBoxSupportAccessAllowed(ctx context.Context, arg SetBoxSupportAccessAllowedParams) error {
	_, err := q.exec(ctx, q.setBoxSupportAccessAllowedStmt, setBoxSupportAccessAllowed, arg.SupportAccessAllowed, arg.ID)
	return err
}

const updateBoxContainerAndStatus = `-- name: UpdateBoxContainerAndStatus :exec
UPDATE boxes SET 
    container_id = ?,
    status = ?,
    ssh_server_identity_key = ?,
    ssh_authorized_keys = ?,
    ssh_client_private_key = ?,
    ssh_port = ?,
    ssh_user = ?
WHERE id = ?
`

type UpdateBoxContainerAndStatusParams struct {
	ContainerID          *string `db:"container_id" json:"container_id"`
	Status               string  `db:"status" json:"status"`
	SSHServerIdentityKey []byte  `db:"ssh_server_identity_key" json:"ssh_server_identity_key"`
	SSHAuthorizedKeys    *string `db:"ssh_authorized_keys" json:"ssh_authorized_keys"`
	SSHClientPrivateKey  []byte  `db:"ssh_client_private_key" json:"ssh_client_private_key"`
	SSHPort              *int64  `db:"ssh_port" json:"ssh_port"`
	SSHUser              *string `db:"ssh_user" json:"ssh_user"`
	ID                   int     `db:"id" json:"id"`
}

func (q *Queries) UpdateBoxContainerAndStatus(ctx context.Context, arg UpdateBoxContainerAndStatusParams) error {
	_, err := q.exec(ctx, q.updateBoxContainerAndStatusStmt, updateBoxContainerAndStatus,
		arg.ContainerID,
		arg.Status,
		arg.SSHServerIdentityKey,
		arg.SSHAuthorizedKeys,
		arg.SSHClientPrivateKey,
		arg.SSHPort,
		arg.SSHUser,
		arg.ID,
	)
	return err
}

const updateBoxContainerIDAndStatus = `-- name: UpdateBoxContainerIDAndStatus :exec
UPDATE boxes SET container_id = ?, status = 'running' WHERE id = ?
`

type UpdateBoxContainerIDAndStatusParams struct {
	ContainerID *string `db:"container_id" json:"container_id"`
	ID          int     `db:"id" json:"id"`
}

func (q *Queries) UpdateBoxContainerIDAndStatus(ctx context.Context, arg UpdateBoxContainerIDAndStatusParams) error {
	_, err := q.exec(ctx, q.updateBoxContainerIDAndStatusStmt, updateBoxContainerIDAndStatus, arg.ContainerID, arg.ID)
	return err
}

const updateBoxCreationLog = `-- name: UpdateBoxCreationLog :exec
UPDATE boxes SET creation_log = ? WHERE name = ?
`

type UpdateBoxCreationLogParams struct {
	CreationLog *string `db:"creation_log" json:"creation_log"`
	Name        string  `db:"name" json:"name"`
}

func (q *Queries) UpdateBoxCreationLog(ctx context.Context, arg UpdateBoxCreationLogParams) error {
	_, err := q.exec(ctx, q.updateBoxCreationLogStmt, updateBoxCreationLog, arg.CreationLog, arg.Name)
	return err
}

const updateBoxMigration = `-- name: UpdateBoxMigration :exec
UPDATE boxes
SET ctrhost = ?, ssh_port = ?, status = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateBoxMigrationParams struct {
	Ctrhost string `db:"ctrhost" json:"ctrhost"`
	SSHPort *int64 `db:"ssh_port" json:"ssh_port"`
	Status  string `db:"status" json:"status"`
	ID      int    `db:"id" json:"id"`
}

func (q *Queries) UpdateBoxMigration(ctx context.Context, arg UpdateBoxMigrationParams) error {
	_, err := q.exec(ctx, q.updateBoxMigrationStmt, updateBoxMigration,
		arg.Ctrhost,
		arg.SSHPort,
		arg.Status,
		arg.ID,
	)
	return err
}

const updateBoxRoutes = `-- name: UpdateBoxRoutes :exec
UPDATE boxes SET routes = ? WHERE name = ? AND created_by_user_id = ?
`

type UpdateBoxRoutesParams struct {
	Routes          *string `db:"routes" json:"routes"`
	Name            string  `db:"name" json:"name"`
	CreatedByUserID string  `db:"created_by_user_id" json:"created_by_user_id"`
}

func (q *Queries) UpdateBoxRoutes(ctx context.Context, arg UpdateBoxRoutesParams) error {
	_, err := q.exec(ctx, q.updateBoxRoutesStmt, updateBoxRoutes, arg.Routes, arg.Name, arg.CreatedByUserID)
	return err
}

const updateBoxSSHDetails = `-- name: UpdateBoxSSHDetails :exec
UPDATE boxes SET
    ssh_server_identity_key = ?, ssh_authorized_keys = ?,
    ssh_client_private_key = ?, ssh_port = ?
WHERE id = ?
`

type UpdateBoxSSHDetailsParams struct {
	SSHServerIdentityKey []byte  `db:"ssh_server_identity_key" json:"ssh_server_identity_key"`
	SSHAuthorizedKeys    *string `db:"ssh_authorized_keys" json:"ssh_authorized_keys"`
	SSHClientPrivateKey  []byte  `db:"ssh_client_private_key" json:"ssh_client_private_key"`
	SSHPort              *int64  `db:"ssh_port" json:"ssh_port"`
	ID                   int     `db:"id" json:"id"`
}

func (q *Queries) UpdateBoxSSHDetails(ctx context.Context, arg UpdateBoxSSHDetailsParams) error {
	_, err := q.exec(ctx, q.updateBoxSSHDetailsStmt, updateBoxSSHDetails,
		arg.SSHServerIdentityKey,
		arg.SSHAuthorizedKeys,
		arg.SSHClientPrivateKey,
		arg.SSHPort,
		arg.ID,
	)
	return err
}

const updateBoxStatus = `-- name: UpdateBoxStatus :exec
UPDATE boxes
SET status = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateBoxStatusParams struct {
	Status string `db:"status" json:"status"`
	ID     int    `db:"id" json:"id"`
}

func (q *Queries) UpdateBoxStatus(ctx context.Context, arg UpdateBoxStatusParams) error {
	_, err := q.exec(ctx, q.updateBoxStatusStmt, updateBoxStatus, arg.Status, arg.ID)
	return err
}
