// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: boxes.sql

package exedb

import (
	"context"
	"time"
)

const boxNamed = `-- name: BoxNamed :one
SELECT id, alloc_id, name, status, image, container_id, created_by_user_id, created_at, updated_at, last_started_at, routes, ssh_server_identity_key, ssh_authorized_keys, ssh_client_private_key, ssh_port, ssh_user, creation_log FROM boxes WHERE name = ?
`

// This is not a secure API!
// Whenever possible, use an alternative method that also checks the alloc/user and/or returns less data.
func (q *Queries) BoxNamed(ctx context.Context, name string) (Box, error) {
	row := q.queryRow(ctx, q.boxNamedStmt, boxNamed, name)
	var i Box
	err := row.Scan(
		&i.ID,
		&i.AllocID,
		&i.Name,
		&i.Status,
		&i.Image,
		&i.ContainerID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastStartedAt,
		&i.Routes,
		&i.SSHServerIdentityKey,
		&i.SSHAuthorizedKeys,
		&i.SSHClientPrivateKey,
		&i.SSHPort,
		&i.SSHUser,
		&i.CreationLog,
	)
	return i, err
}

const boxWithNameExists = `-- name: BoxWithNameExists :one
SELECT EXISTS ( SELECT 1 FROM boxes WHERE name = ? )
`

func (q *Queries) BoxWithNameExists(ctx context.Context, name string) (int64, error) {
	row := q.queryRow(ctx, q.boxWithNameExistsStmt, boxWithNameExists, name)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const boxWithOwnerNamed = `-- name: BoxWithOwnerNamed :one
SELECT id, alloc_id, name, status, image, container_id, created_by_user_id, created_at, updated_at, last_started_at, routes, ssh_server_identity_key, ssh_authorized_keys, ssh_client_private_key, ssh_port, ssh_user, creation_log FROM boxes WHERE name = ? AND boxes.alloc_id = (SELECT allocs.alloc_id FROM allocs WHERE allocs.user_id = ?)
`

type BoxWithOwnerNamedParams struct {
	Name   string `db:"name" json:"name"`
	UserID string `db:"user_id" json:"user_id"`
}

func (q *Queries) BoxWithOwnerNamed(ctx context.Context, arg BoxWithOwnerNamedParams) (Box, error) {
	row := q.queryRow(ctx, q.boxWithOwnerNamedStmt, boxWithOwnerNamed, arg.Name, arg.UserID)
	var i Box
	err := row.Scan(
		&i.ID,
		&i.AllocID,
		&i.Name,
		&i.Status,
		&i.Image,
		&i.ContainerID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastStartedAt,
		&i.Routes,
		&i.SSHServerIdentityKey,
		&i.SSHAuthorizedKeys,
		&i.SSHClientPrivateKey,
		&i.SSHPort,
		&i.SSHUser,
		&i.CreationLog,
	)
	return i, err
}

const deleteBox = `-- name: DeleteBox :exec
DELETE FROM boxes WHERE id = ?
`

func (q *Queries) DeleteBox(ctx context.Context, id int) error {
	_, err := q.exec(ctx, q.deleteBoxStmt, deleteBox, id)
	return err
}

const getBoxByNameAndAlloc = `-- name: GetBoxByNameAndAlloc :one
SELECT id, alloc_id, name, status, image, container_id, created_by_user_id, created_at, updated_at, last_started_at, routes, ssh_server_identity_key, ssh_authorized_keys, ssh_client_private_key, ssh_port, ssh_user, creation_log FROM boxes WHERE name = ? AND alloc_id = ?
`

type GetBoxByNameAndAllocParams struct {
	Name    string `db:"name" json:"name"`
	AllocID string `db:"alloc_id" json:"alloc_id"`
}

func (q *Queries) GetBoxByNameAndAlloc(ctx context.Context, arg GetBoxByNameAndAllocParams) (Box, error) {
	row := q.queryRow(ctx, q.getBoxByNameAndAllocStmt, getBoxByNameAndAlloc, arg.Name, arg.AllocID)
	var i Box
	err := row.Scan(
		&i.ID,
		&i.AllocID,
		&i.Name,
		&i.Status,
		&i.Image,
		&i.ContainerID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastStartedAt,
		&i.Routes,
		&i.SSHServerIdentityKey,
		&i.SSHAuthorizedKeys,
		&i.SSHClientPrivateKey,
		&i.SSHPort,
		&i.SSHUser,
		&i.CreationLog,
	)
	return i, err
}

const getBoxDetailsForSetup = `-- name: GetBoxDetailsForSetup :one
SELECT container_id, created_by_user_id, name, image
FROM boxes WHERE id = ?
`

type GetBoxDetailsForSetupRow struct {
	ContainerID     *string `db:"container_id" json:"container_id"`
	CreatedByUserID string  `db:"created_by_user_id" json:"created_by_user_id"`
	Name            string  `db:"name" json:"name"`
	Image           string  `db:"image" json:"image"`
}

func (q *Queries) GetBoxDetailsForSetup(ctx context.Context, id int) (GetBoxDetailsForSetupRow, error) {
	row := q.queryRow(ctx, q.getBoxDetailsForSetupStmt, getBoxDetailsForSetup, id)
	var i GetBoxDetailsForSetupRow
	err := row.Scan(
		&i.ContainerID,
		&i.CreatedByUserID,
		&i.Name,
		&i.Image,
	)
	return i, err
}

const getBoxIDAndAllocByName = `-- name: GetBoxIDAndAllocByName :one
SELECT id, alloc_id FROM boxes WHERE name = ?
`

type GetBoxIDAndAllocByNameRow struct {
	ID      int    `db:"id" json:"id"`
	AllocID string `db:"alloc_id" json:"alloc_id"`
}

func (q *Queries) GetBoxIDAndAllocByName(ctx context.Context, name string) (GetBoxIDAndAllocByNameRow, error) {
	row := q.queryRow(ctx, q.getBoxIDAndAllocByNameStmt, getBoxIDAndAllocByName, name)
	var i GetBoxIDAndAllocByNameRow
	err := row.Scan(&i.ID, &i.AllocID)
	return i, err
}

const getBoxSSHDetails = `-- name: GetBoxSSHDetails :one
SELECT m.ssh_port, m.ssh_client_private_key, m.ssh_server_identity_key, a.ctrhost, m.ssh_user
FROM boxes m
JOIN allocs a ON m.alloc_id = a.alloc_id
WHERE m.id = ?
`

type GetBoxSSHDetailsRow struct {
	SSHPort              *int64  `db:"ssh_port" json:"ssh_port"`
	SSHClientPrivateKey  []byte  `db:"ssh_client_private_key" json:"ssh_client_private_key"`
	SSHServerIdentityKey []byte  `db:"ssh_server_identity_key" json:"ssh_server_identity_key"`
	Ctrhost              string  `db:"ctrhost" json:"ctrhost"`
	SSHUser              *string `db:"ssh_user" json:"ssh_user"`
}

func (q *Queries) GetBoxSSHDetails(ctx context.Context, id int) (GetBoxSSHDetailsRow, error) {
	row := q.queryRow(ctx, q.getBoxSSHDetailsStmt, getBoxSSHDetails, id)
	var i GetBoxSSHDetailsRow
	err := row.Scan(
		&i.SSHPort,
		&i.SSHClientPrivateKey,
		&i.SSHServerIdentityKey,
		&i.Ctrhost,
		&i.SSHUser,
	)
	return i, err
}

const getBoxesByHost = `-- name: GetBoxesByHost :many
SELECT b.id, b.alloc_id, b.name, b.status, b.image, b.container_id, b.created_by_user_id, b.created_at, b.updated_at, b.last_started_at, b.routes, b.ssh_server_identity_key, b.ssh_authorized_keys, b.ssh_client_private_key, b.ssh_port, b.ssh_user, b.creation_log
FROM boxes b
INNER JOIN allocs a ON b.alloc_id = a.alloc_id
WHERE a.ctrhost = ? AND b.status != 'failed'
`

func (q *Queries) GetBoxesByHost(ctx context.Context, ctrhost string) ([]Box, error) {
	rows, err := q.query(ctx, q.getBoxesByHostStmt, getBoxesByHost, ctrhost)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Box{}
	for rows.Next() {
		var i Box
		if err := rows.Scan(
			&i.ID,
			&i.AllocID,
			&i.Name,
			&i.Status,
			&i.Image,
			&i.ContainerID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastStartedAt,
			&i.Routes,
			&i.SSHServerIdentityKey,
			&i.SSHAuthorizedKeys,
			&i.SSHClientPrivateKey,
			&i.SSHPort,
			&i.SSHUser,
			&i.CreationLog,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBoxesForAlloc = `-- name: GetBoxesForAlloc :many
SELECT id, alloc_id, name, status, image, container_id, created_by_user_id, created_at, updated_at, last_started_at, routes, ssh_server_identity_key, ssh_authorized_keys, ssh_client_private_key, ssh_port, ssh_user, creation_log
FROM boxes
WHERE alloc_id = ?
ORDER BY name
`

func (q *Queries) GetBoxesForAlloc(ctx context.Context, allocID string) ([]Box, error) {
	rows, err := q.query(ctx, q.getBoxesForAllocStmt, getBoxesForAlloc, allocID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Box{}
	for rows.Next() {
		var i Box
		if err := rows.Scan(
			&i.ID,
			&i.AllocID,
			&i.Name,
			&i.Status,
			&i.Image,
			&i.ContainerID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastStartedAt,
			&i.Routes,
			&i.SSHServerIdentityKey,
			&i.SSHAuthorizedKeys,
			&i.SSHClientPrivateKey,
			&i.SSHPort,
			&i.SSHUser,
			&i.CreationLog,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBoxesForUserDashboard = `-- name: GetBoxesForUserDashboard :many
SELECT m.id, m.alloc_id, m.name, m.status, COALESCE(m.image, '') as image,
       COALESCE(m.container_id, '') as container_id, m.created_by_user_id,
       m.created_at, m.updated_at, m.last_started_at,
       COALESCE(m.creation_log, '') as creation_log
FROM boxes m
JOIN allocs a ON m.alloc_id = a.alloc_id
WHERE a.user_id = ?
ORDER BY m.updated_at DESC
`

type GetBoxesForUserDashboardRow struct {
	ID              int        `db:"id" json:"id"`
	AllocID         string     `db:"alloc_id" json:"alloc_id"`
	Name            string     `db:"name" json:"name"`
	Status          string     `db:"status" json:"status"`
	Image           string     `db:"image" json:"image"`
	ContainerID     string     `db:"container_id" json:"container_id"`
	CreatedByUserID string     `db:"created_by_user_id" json:"created_by_user_id"`
	CreatedAt       *time.Time `db:"created_at" json:"created_at"`
	UpdatedAt       *time.Time `db:"updated_at" json:"updated_at"`
	LastStartedAt   *time.Time `db:"last_started_at" json:"last_started_at"`
	CreationLog     string     `db:"creation_log" json:"creation_log"`
}

func (q *Queries) GetBoxesForUserDashboard(ctx context.Context, userID string) ([]GetBoxesForUserDashboardRow, error) {
	rows, err := q.query(ctx, q.getBoxesForUserDashboardStmt, getBoxesForUserDashboard, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBoxesForUserDashboardRow{}
	for rows.Next() {
		var i GetBoxesForUserDashboardRow
		if err := rows.Scan(
			&i.ID,
			&i.AllocID,
			&i.Name,
			&i.Status,
			&i.Image,
			&i.ContainerID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastStartedAt,
			&i.CreationLog,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBox = `-- name: InsertBox :execlastid
INSERT INTO boxes (
    alloc_id, name, status, image, container_id, created_by_user_id, routes
) VALUES (?, ?, ?, ?, NULL, ?, ?)
`

type InsertBoxParams struct {
	AllocID         string  `db:"alloc_id" json:"alloc_id"`
	Name            string  `db:"name" json:"name"`
	Status          string  `db:"status" json:"status"`
	Image           string  `db:"image" json:"image"`
	CreatedByUserID string  `db:"created_by_user_id" json:"created_by_user_id"`
	Routes          *string `db:"routes" json:"routes"`
}

func (q *Queries) InsertBox(ctx context.Context, arg InsertBoxParams) (int64, error) {
	result, err := q.exec(ctx, q.insertBoxStmt, insertBox,
		arg.AllocID,
		arg.Name,
		arg.Status,
		arg.Image,
		arg.CreatedByUserID,
		arg.Routes,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const sSHKeyForBoxNamed = `-- name: SSHKeyForBoxNamed :one
SELECT ssh_server_identity_key FROM boxes WHERE name = ?
`

func (q *Queries) SSHKeyForBoxNamed(ctx context.Context, name string) ([]byte, error) {
	row := q.queryRow(ctx, q.sSHKeyForBoxNamedStmt, sSHKeyForBoxNamed, name)
	var ssh_server_identity_key []byte
	err := row.Scan(&ssh_server_identity_key)
	return ssh_server_identity_key, err
}

const updateBoxContainerAndStatus = `-- name: UpdateBoxContainerAndStatus :exec
UPDATE boxes SET 
    container_id = ?,
    status = ?,
    ssh_server_identity_key = ?,
    ssh_authorized_keys = ?,
    ssh_client_private_key = ?,
    ssh_port = ?,
    ssh_user = ?
WHERE id = ?
`

type UpdateBoxContainerAndStatusParams struct {
	ContainerID          *string `db:"container_id" json:"container_id"`
	Status               string  `db:"status" json:"status"`
	SSHServerIdentityKey []byte  `db:"ssh_server_identity_key" json:"ssh_server_identity_key"`
	SSHAuthorizedKeys    *string `db:"ssh_authorized_keys" json:"ssh_authorized_keys"`
	SSHClientPrivateKey  []byte  `db:"ssh_client_private_key" json:"ssh_client_private_key"`
	SSHPort              *int64  `db:"ssh_port" json:"ssh_port"`
	SSHUser              *string `db:"ssh_user" json:"ssh_user"`
	ID                   int     `db:"id" json:"id"`
}

func (q *Queries) UpdateBoxContainerAndStatus(ctx context.Context, arg UpdateBoxContainerAndStatusParams) error {
	_, err := q.exec(ctx, q.updateBoxContainerAndStatusStmt, updateBoxContainerAndStatus,
		arg.ContainerID,
		arg.Status,
		arg.SSHServerIdentityKey,
		arg.SSHAuthorizedKeys,
		arg.SSHClientPrivateKey,
		arg.SSHPort,
		arg.SSHUser,
		arg.ID,
	)
	return err
}

const updateBoxContainerIDAndStatus = `-- name: UpdateBoxContainerIDAndStatus :exec
UPDATE boxes SET container_id = ?, status = 'running' WHERE id = ?
`

type UpdateBoxContainerIDAndStatusParams struct {
	ContainerID *string `db:"container_id" json:"container_id"`
	ID          int     `db:"id" json:"id"`
}

func (q *Queries) UpdateBoxContainerIDAndStatus(ctx context.Context, arg UpdateBoxContainerIDAndStatusParams) error {
	_, err := q.exec(ctx, q.updateBoxContainerIDAndStatusStmt, updateBoxContainerIDAndStatus, arg.ContainerID, arg.ID)
	return err
}

const updateBoxRoutes = `-- name: UpdateBoxRoutes :exec
UPDATE boxes SET routes = ? WHERE name = ? AND alloc_id = ?
`

type UpdateBoxRoutesParams struct {
	Routes  *string `db:"routes" json:"routes"`
	Name    string  `db:"name" json:"name"`
	AllocID string  `db:"alloc_id" json:"alloc_id"`
}

func (q *Queries) UpdateBoxRoutes(ctx context.Context, arg UpdateBoxRoutesParams) error {
	_, err := q.exec(ctx, q.updateBoxRoutesStmt, updateBoxRoutes, arg.Routes, arg.Name, arg.AllocID)
	return err
}

const updateBoxSSHDetails = `-- name: UpdateBoxSSHDetails :exec
UPDATE boxes SET
    ssh_server_identity_key = ?, ssh_authorized_keys = ?,
    ssh_client_private_key = ?, ssh_port = ?
WHERE id = ?
`

type UpdateBoxSSHDetailsParams struct {
	SSHServerIdentityKey []byte  `db:"ssh_server_identity_key" json:"ssh_server_identity_key"`
	SSHAuthorizedKeys    *string `db:"ssh_authorized_keys" json:"ssh_authorized_keys"`
	SSHClientPrivateKey  []byte  `db:"ssh_client_private_key" json:"ssh_client_private_key"`
	SSHPort              *int64  `db:"ssh_port" json:"ssh_port"`
	ID                   int     `db:"id" json:"id"`
}

func (q *Queries) UpdateBoxSSHDetails(ctx context.Context, arg UpdateBoxSSHDetailsParams) error {
	_, err := q.exec(ctx, q.updateBoxSSHDetailsStmt, updateBoxSSHDetails,
		arg.SSHServerIdentityKey,
		arg.SSHAuthorizedKeys,
		arg.SSHClientPrivateKey,
		arg.SSHPort,
		arg.ID,
	)
	return err
}

const updateBoxStatus = `-- name: UpdateBoxStatus :exec
UPDATE boxes
SET status = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateBoxStatusParams struct {
	Status string `db:"status" json:"status"`
	ID     int    `db:"id" json:"id"`
}

func (q *Queries) UpdateBoxStatus(ctx context.Context, arg UpdateBoxStatusParams) error {
	_, err := q.exec(ctx, q.updateBoxStatusStmt, updateBoxStatus, arg.Status, arg.ID)
	return err
}

const updateBoxStatusRunning = `-- name: UpdateBoxStatusRunning :exec
UPDATE boxes SET status = 'running', last_started_at = CURRENT_TIMESTAMP
WHERE name = ?
`

func (q *Queries) UpdateBoxStatusRunning(ctx context.Context, name string) error {
	_, err := q.exec(ctx, q.updateBoxStatusRunningStmt, updateBoxStatusRunning, name)
	return err
}

const updateBoxStatusRunningByID = `-- name: UpdateBoxStatusRunningByID :exec
UPDATE boxes SET status = 'running', updated_at = ? WHERE id = ?
`

type UpdateBoxStatusRunningByIDParams struct {
	UpdatedAt *time.Time `db:"updated_at" json:"updated_at"`
	ID        int        `db:"id" json:"id"`
}

func (q *Queries) UpdateBoxStatusRunningByID(ctx context.Context, arg UpdateBoxStatusRunningByIDParams) error {
	_, err := q.exec(ctx, q.updateBoxStatusRunningByIDStmt, updateBoxStatusRunningByID, arg.UpdatedAt, arg.ID)
	return err
}

const updateBoxStatusStopped = `-- name: UpdateBoxStatusStopped :exec
UPDATE boxes SET status = 'stopped'
WHERE name = ?
`

func (q *Queries) UpdateBoxStatusStopped(ctx context.Context, name string) error {
	_, err := q.exec(ctx, q.updateBoxStatusStoppedStmt, updateBoxStatusStopped, name)
	return err
}
