// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: checkout_params.sql

package exedb

import (
	"context"
	"time"
)

const consumeCheckoutParams = `-- name: ConsumeCheckoutParams :one
DELETE FROM checkout_params WHERE token = ? AND user_id = ? RETURNING token, user_id, source, vm_name, vm_prompt, created_at, vm_image
`

type ConsumeCheckoutParamsParams struct {
	Token  string `db:"token" json:"token"`
	UserID string `db:"user_id" json:"user_id"`
}

func (q *Queries) ConsumeCheckoutParams(ctx context.Context, arg ConsumeCheckoutParamsParams) (CheckoutParam, error) {
	row := q.queryRow(ctx, q.consumeCheckoutParamsStmt, consumeCheckoutParams, arg.Token, arg.UserID)
	var i CheckoutParam
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.Source,
		&i.VMName,
		&i.VMPrompt,
		&i.CreatedAt,
		&i.VMImage,
	)
	return i, err
}

const deleteOldCheckoutParams = `-- name: DeleteOldCheckoutParams :exec
DELETE FROM checkout_params WHERE created_at < ?
`

func (q *Queries) DeleteOldCheckoutParams(ctx context.Context, createdAt time.Time) error {
	_, err := q.exec(ctx, q.deleteOldCheckoutParamsStmt, deleteOldCheckoutParams, createdAt)
	return err
}

const getCheckoutParams = `-- name: GetCheckoutParams :one
SELECT token, user_id, source, vm_name, vm_prompt, created_at, vm_image FROM checkout_params WHERE token = ? AND user_id = ?
`

type GetCheckoutParamsParams struct {
	Token  string `db:"token" json:"token"`
	UserID string `db:"user_id" json:"user_id"`
}

func (q *Queries) GetCheckoutParams(ctx context.Context, arg GetCheckoutParamsParams) (CheckoutParam, error) {
	row := q.queryRow(ctx, q.getCheckoutParamsStmt, getCheckoutParams, arg.Token, arg.UserID)
	var i CheckoutParam
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.Source,
		&i.VMName,
		&i.VMPrompt,
		&i.CreatedAt,
		&i.VMImage,
	)
	return i, err
}

const insertCheckoutParams = `-- name: InsertCheckoutParams :exec
INSERT INTO checkout_params (token, user_id, source, vm_name, vm_prompt, vm_image) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertCheckoutParamsParams struct {
	Token    string `db:"token" json:"token"`
	UserID   string `db:"user_id" json:"user_id"`
	Source   string `db:"source" json:"source"`
	VMName   string `db:"vm_name" json:"vm_name"`
	VMPrompt string `db:"vm_prompt" json:"vm_prompt"`
	VMImage  string `db:"vm_image" json:"vm_image"`
}

func (q *Queries) InsertCheckoutParams(ctx context.Context, arg InsertCheckoutParamsParams) error {
	_, err := q.exec(ctx, q.insertCheckoutParamsStmt, insertCheckoutParams,
		arg.Token,
		arg.UserID,
		arg.Source,
		arg.VMName,
		arg.VMPrompt,
		arg.VMImage,
	)
	return err
}
