// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package exedb

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.allocExistsForUserStmt, err = db.PrepareContext(ctx, allocExistsForUser); err != nil {
		return nil, fmt.Errorf("error preparing query AllocExistsForUser: %w", err)
	}
	if q.deleteAuthCookieStmt, err = db.PrepareContext(ctx, deleteAuthCookie); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAuthCookie: %w", err)
	}
	if q.deleteAuthCookieByValueStmt, err = db.PrepareContext(ctx, deleteAuthCookieByValue); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAuthCookieByValue: %w", err)
	}
	if q.deleteAuthCookiesByUserIDStmt, err = db.PrepareContext(ctx, deleteAuthCookiesByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAuthCookiesByUserID: %w", err)
	}
	if q.deleteEmailVerificationByTokenStmt, err = db.PrepareContext(ctx, deleteEmailVerificationByToken); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteEmailVerificationByToken: %w", err)
	}
	if q.deletePendingSSHKeyByTokenStmt, err = db.PrepareContext(ctx, deletePendingSSHKeyByToken); err != nil {
		return nil, fmt.Errorf("error preparing query DeletePendingSSHKeyByToken: %w", err)
	}
	if q.getAllUserEventsStmt, err = db.PrepareContext(ctx, getAllUserEvents); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllUserEvents: %w", err)
	}
	if q.getAllocByUserIDStmt, err = db.PrepareContext(ctx, getAllocByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllocByUserID: %w", err)
	}
	if q.getAllocsByHostStmt, err = db.PrepareContext(ctx, getAllocsByHost); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllocsByHost: %w", err)
	}
	if q.getAuthCookieInfoStmt, err = db.PrepareContext(ctx, getAuthCookieInfo); err != nil {
		return nil, fmt.Errorf("error preparing query GetAuthCookieInfo: %w", err)
	}
	if q.getAuthTokenInfoStmt, err = db.PrepareContext(ctx, getAuthTokenInfo); err != nil {
		return nil, fmt.Errorf("error preparing query GetAuthTokenInfo: %w", err)
	}
	if q.getBoxByNameStmt, err = db.PrepareContext(ctx, getBoxByName); err != nil {
		return nil, fmt.Errorf("error preparing query GetBoxByName: %w", err)
	}
	if q.getBoxByNameAndAllocStmt, err = db.PrepareContext(ctx, getBoxByNameAndAlloc); err != nil {
		return nil, fmt.Errorf("error preparing query GetBoxByNameAndAlloc: %w", err)
	}
	if q.getBoxDetailsForSetupStmt, err = db.PrepareContext(ctx, getBoxDetailsForSetup); err != nil {
		return nil, fmt.Errorf("error preparing query GetBoxDetailsForSetup: %w", err)
	}
	if q.getBoxSSHDetailsStmt, err = db.PrepareContext(ctx, getBoxSSHDetails); err != nil {
		return nil, fmt.Errorf("error preparing query GetBoxSSHDetails: %w", err)
	}
	if q.getBoxesByHostStmt, err = db.PrepareContext(ctx, getBoxesByHost); err != nil {
		return nil, fmt.Errorf("error preparing query GetBoxesByHost: %w", err)
	}
	if q.getBoxesForAllocStmt, err = db.PrepareContext(ctx, getBoxesForAlloc); err != nil {
		return nil, fmt.Errorf("error preparing query GetBoxesForAlloc: %w", err)
	}
	if q.getBoxesForUserDashboardStmt, err = db.PrepareContext(ctx, getBoxesForUserDashboard); err != nil {
		return nil, fmt.Errorf("error preparing query GetBoxesForUserDashboard: %w", err)
	}
	if q.getCtrhostByAllocIDStmt, err = db.PrepareContext(ctx, getCtrhostByAllocID); err != nil {
		return nil, fmt.Errorf("error preparing query GetCtrhostByAllocID: %w", err)
	}
	if q.getEmailBySSHKeyStmt, err = db.PrepareContext(ctx, getEmailBySSHKey); err != nil {
		return nil, fmt.Errorf("error preparing query GetEmailBySSHKey: %w", err)
	}
	if q.getEmailByUserIDStmt, err = db.PrepareContext(ctx, getEmailByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetEmailByUserID: %w", err)
	}
	if q.getEmailVerificationByEmailStmt, err = db.PrepareContext(ctx, getEmailVerificationByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetEmailVerificationByEmail: %w", err)
	}
	if q.getEmailVerificationByPartialTokenStmt, err = db.PrepareContext(ctx, getEmailVerificationByPartialToken); err != nil {
		return nil, fmt.Errorf("error preparing query GetEmailVerificationByPartialToken: %w", err)
	}
	if q.getEmailVerificationByTokenStmt, err = db.PrepareContext(ctx, getEmailVerificationByToken); err != nil {
		return nil, fmt.Errorf("error preparing query GetEmailVerificationByToken: %w", err)
	}
	if q.getFirstUserIDStmt, err = db.PrepareContext(ctx, getFirstUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetFirstUserID: %w", err)
	}
	if q.getPendingSSHKeyByTokenStmt, err = db.PrepareContext(ctx, getPendingSSHKeyByToken); err != nil {
		return nil, fmt.Errorf("error preparing query GetPendingSSHKeyByToken: %w", err)
	}
	if q.getPendingSSHKeyEmailByPublicKeyStmt, err = db.PrepareContext(ctx, getPendingSSHKeyEmailByPublicKey); err != nil {
		return nil, fmt.Errorf("error preparing query GetPendingSSHKeyEmailByPublicKey: %w", err)
	}
	if q.getSSHHostKeyStmt, err = db.PrepareContext(ctx, getSSHHostKey); err != nil {
		return nil, fmt.Errorf("error preparing query GetSSHHostKey: %w", err)
	}
	if q.getSSHHostPublicKeyStmt, err = db.PrepareContext(ctx, getSSHHostPublicKey); err != nil {
		return nil, fmt.Errorf("error preparing query GetSSHHostPublicKey: %w", err)
	}
	if q.getSSHKeysForUserStmt, err = db.PrepareContext(ctx, getSSHKeysForUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetSSHKeysForUser: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getUserEventCountStmt, err = db.PrepareContext(ctx, getUserEventCount); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserEventCount: %w", err)
	}
	if q.getUserIDByEmailStmt, err = db.PrepareContext(ctx, getUserIDByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserIDByEmail: %w", err)
	}
	if q.getUserIDBySSHKeyStmt, err = db.PrepareContext(ctx, getUserIDBySSHKey); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserIDBySSHKey: %w", err)
	}
	if q.getUserWithDetailsStmt, err = db.PrepareContext(ctx, getUserWithDetails); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserWithDetails: %w", err)
	}
	if q.getUserWithSSHKeyStmt, err = db.PrepareContext(ctx, getUserWithSSHKey); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserWithSSHKey: %w", err)
	}
	if q.insertAllocStmt, err = db.PrepareContext(ctx, insertAlloc); err != nil {
		return nil, fmt.Errorf("error preparing query InsertAlloc: %w", err)
	}
	if q.insertAuthCookieStmt, err = db.PrepareContext(ctx, insertAuthCookie); err != nil {
		return nil, fmt.Errorf("error preparing query InsertAuthCookie: %w", err)
	}
	if q.insertBoxStmt, err = db.PrepareContext(ctx, insertBox); err != nil {
		return nil, fmt.Errorf("error preparing query InsertBox: %w", err)
	}
	if q.insertEmailVerificationStmt, err = db.PrepareContext(ctx, insertEmailVerification); err != nil {
		return nil, fmt.Errorf("error preparing query InsertEmailVerification: %w", err)
	}
	if q.insertOrReplaceEmailVerificationStmt, err = db.PrepareContext(ctx, insertOrReplaceEmailVerification); err != nil {
		return nil, fmt.Errorf("error preparing query InsertOrReplaceEmailVerification: %w", err)
	}
	if q.insertSSHKeyStmt, err = db.PrepareContext(ctx, insertSSHKey); err != nil {
		return nil, fmt.Errorf("error preparing query InsertSSHKey: %w", err)
	}
	if q.insertSSHKeyForEmailUserStmt, err = db.PrepareContext(ctx, insertSSHKeyForEmailUser); err != nil {
		return nil, fmt.Errorf("error preparing query InsertSSHKeyForEmailUser: %w", err)
	}
	if q.insertUserStmt, err = db.PrepareContext(ctx, insertUser); err != nil {
		return nil, fmt.Errorf("error preparing query InsertUser: %w", err)
	}
	if q.recordUserEventStmt, err = db.PrepareContext(ctx, recordUserEvent); err != nil {
		return nil, fmt.Errorf("error preparing query RecordUserEvent: %w", err)
	}
	if q.updateAuthCookieLastUsedStmt, err = db.PrepareContext(ctx, updateAuthCookieLastUsed); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAuthCookieLastUsed: %w", err)
	}
	if q.updateAuthTokenUsedAtStmt, err = db.PrepareContext(ctx, updateAuthTokenUsedAt); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAuthTokenUsedAt: %w", err)
	}
	if q.updateBoxContainerAndStatusStmt, err = db.PrepareContext(ctx, updateBoxContainerAndStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateBoxContainerAndStatus: %w", err)
	}
	if q.updateBoxContainerIDAndStatusStmt, err = db.PrepareContext(ctx, updateBoxContainerIDAndStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateBoxContainerIDAndStatus: %w", err)
	}
	if q.updateBoxSSHDetailsStmt, err = db.PrepareContext(ctx, updateBoxSSHDetails); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateBoxSSHDetails: %w", err)
	}
	if q.updateBoxStatusStmt, err = db.PrepareContext(ctx, updateBoxStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateBoxStatus: %w", err)
	}
	if q.upsertSSHHostKeyStmt, err = db.PrepareContext(ctx, upsertSSHHostKey); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertSSHHostKey: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.allocExistsForUserStmt != nil {
		if cerr := q.allocExistsForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing allocExistsForUserStmt: %w", cerr)
		}
	}
	if q.deleteAuthCookieStmt != nil {
		if cerr := q.deleteAuthCookieStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAuthCookieStmt: %w", cerr)
		}
	}
	if q.deleteAuthCookieByValueStmt != nil {
		if cerr := q.deleteAuthCookieByValueStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAuthCookieByValueStmt: %w", cerr)
		}
	}
	if q.deleteAuthCookiesByUserIDStmt != nil {
		if cerr := q.deleteAuthCookiesByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAuthCookiesByUserIDStmt: %w", cerr)
		}
	}
	if q.deleteEmailVerificationByTokenStmt != nil {
		if cerr := q.deleteEmailVerificationByTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteEmailVerificationByTokenStmt: %w", cerr)
		}
	}
	if q.deletePendingSSHKeyByTokenStmt != nil {
		if cerr := q.deletePendingSSHKeyByTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deletePendingSSHKeyByTokenStmt: %w", cerr)
		}
	}
	if q.getAllUserEventsStmt != nil {
		if cerr := q.getAllUserEventsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllUserEventsStmt: %w", cerr)
		}
	}
	if q.getAllocByUserIDStmt != nil {
		if cerr := q.getAllocByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllocByUserIDStmt: %w", cerr)
		}
	}
	if q.getAllocsByHostStmt != nil {
		if cerr := q.getAllocsByHostStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllocsByHostStmt: %w", cerr)
		}
	}
	if q.getAuthCookieInfoStmt != nil {
		if cerr := q.getAuthCookieInfoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAuthCookieInfoStmt: %w", cerr)
		}
	}
	if q.getAuthTokenInfoStmt != nil {
		if cerr := q.getAuthTokenInfoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAuthTokenInfoStmt: %w", cerr)
		}
	}
	if q.getBoxByNameStmt != nil {
		if cerr := q.getBoxByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBoxByNameStmt: %w", cerr)
		}
	}
	if q.getBoxByNameAndAllocStmt != nil {
		if cerr := q.getBoxByNameAndAllocStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBoxByNameAndAllocStmt: %w", cerr)
		}
	}
	if q.getBoxDetailsForSetupStmt != nil {
		if cerr := q.getBoxDetailsForSetupStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBoxDetailsForSetupStmt: %w", cerr)
		}
	}
	if q.getBoxSSHDetailsStmt != nil {
		if cerr := q.getBoxSSHDetailsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBoxSSHDetailsStmt: %w", cerr)
		}
	}
	if q.getBoxesByHostStmt != nil {
		if cerr := q.getBoxesByHostStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBoxesByHostStmt: %w", cerr)
		}
	}
	if q.getBoxesForAllocStmt != nil {
		if cerr := q.getBoxesForAllocStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBoxesForAllocStmt: %w", cerr)
		}
	}
	if q.getBoxesForUserDashboardStmt != nil {
		if cerr := q.getBoxesForUserDashboardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBoxesForUserDashboardStmt: %w", cerr)
		}
	}
	if q.getCtrhostByAllocIDStmt != nil {
		if cerr := q.getCtrhostByAllocIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCtrhostByAllocIDStmt: %w", cerr)
		}
	}
	if q.getEmailBySSHKeyStmt != nil {
		if cerr := q.getEmailBySSHKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getEmailBySSHKeyStmt: %w", cerr)
		}
	}
	if q.getEmailByUserIDStmt != nil {
		if cerr := q.getEmailByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getEmailByUserIDStmt: %w", cerr)
		}
	}
	if q.getEmailVerificationByEmailStmt != nil {
		if cerr := q.getEmailVerificationByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getEmailVerificationByEmailStmt: %w", cerr)
		}
	}
	if q.getEmailVerificationByPartialTokenStmt != nil {
		if cerr := q.getEmailVerificationByPartialTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getEmailVerificationByPartialTokenStmt: %w", cerr)
		}
	}
	if q.getEmailVerificationByTokenStmt != nil {
		if cerr := q.getEmailVerificationByTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getEmailVerificationByTokenStmt: %w", cerr)
		}
	}
	if q.getFirstUserIDStmt != nil {
		if cerr := q.getFirstUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFirstUserIDStmt: %w", cerr)
		}
	}
	if q.getPendingSSHKeyByTokenStmt != nil {
		if cerr := q.getPendingSSHKeyByTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPendingSSHKeyByTokenStmt: %w", cerr)
		}
	}
	if q.getPendingSSHKeyEmailByPublicKeyStmt != nil {
		if cerr := q.getPendingSSHKeyEmailByPublicKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPendingSSHKeyEmailByPublicKeyStmt: %w", cerr)
		}
	}
	if q.getSSHHostKeyStmt != nil {
		if cerr := q.getSSHHostKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSSHHostKeyStmt: %w", cerr)
		}
	}
	if q.getSSHHostPublicKeyStmt != nil {
		if cerr := q.getSSHHostPublicKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSSHHostPublicKeyStmt: %w", cerr)
		}
	}
	if q.getSSHKeysForUserStmt != nil {
		if cerr := q.getSSHKeysForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSSHKeysForUserStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserEventCountStmt != nil {
		if cerr := q.getUserEventCountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserEventCountStmt: %w", cerr)
		}
	}
	if q.getUserIDByEmailStmt != nil {
		if cerr := q.getUserIDByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserIDByEmailStmt: %w", cerr)
		}
	}
	if q.getUserIDBySSHKeyStmt != nil {
		if cerr := q.getUserIDBySSHKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserIDBySSHKeyStmt: %w", cerr)
		}
	}
	if q.getUserWithDetailsStmt != nil {
		if cerr := q.getUserWithDetailsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserWithDetailsStmt: %w", cerr)
		}
	}
	if q.getUserWithSSHKeyStmt != nil {
		if cerr := q.getUserWithSSHKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserWithSSHKeyStmt: %w", cerr)
		}
	}
	if q.insertAllocStmt != nil {
		if cerr := q.insertAllocStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertAllocStmt: %w", cerr)
		}
	}
	if q.insertAuthCookieStmt != nil {
		if cerr := q.insertAuthCookieStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertAuthCookieStmt: %w", cerr)
		}
	}
	if q.insertBoxStmt != nil {
		if cerr := q.insertBoxStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertBoxStmt: %w", cerr)
		}
	}
	if q.insertEmailVerificationStmt != nil {
		if cerr := q.insertEmailVerificationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertEmailVerificationStmt: %w", cerr)
		}
	}
	if q.insertOrReplaceEmailVerificationStmt != nil {
		if cerr := q.insertOrReplaceEmailVerificationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertOrReplaceEmailVerificationStmt: %w", cerr)
		}
	}
	if q.insertSSHKeyStmt != nil {
		if cerr := q.insertSSHKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertSSHKeyStmt: %w", cerr)
		}
	}
	if q.insertSSHKeyForEmailUserStmt != nil {
		if cerr := q.insertSSHKeyForEmailUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertSSHKeyForEmailUserStmt: %w", cerr)
		}
	}
	if q.insertUserStmt != nil {
		if cerr := q.insertUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertUserStmt: %w", cerr)
		}
	}
	if q.recordUserEventStmt != nil {
		if cerr := q.recordUserEventStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing recordUserEventStmt: %w", cerr)
		}
	}
	if q.updateAuthCookieLastUsedStmt != nil {
		if cerr := q.updateAuthCookieLastUsedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAuthCookieLastUsedStmt: %w", cerr)
		}
	}
	if q.updateAuthTokenUsedAtStmt != nil {
		if cerr := q.updateAuthTokenUsedAtStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAuthTokenUsedAtStmt: %w", cerr)
		}
	}
	if q.updateBoxContainerAndStatusStmt != nil {
		if cerr := q.updateBoxContainerAndStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateBoxContainerAndStatusStmt: %w", cerr)
		}
	}
	if q.updateBoxContainerIDAndStatusStmt != nil {
		if cerr := q.updateBoxContainerIDAndStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateBoxContainerIDAndStatusStmt: %w", cerr)
		}
	}
	if q.updateBoxSSHDetailsStmt != nil {
		if cerr := q.updateBoxSSHDetailsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateBoxSSHDetailsStmt: %w", cerr)
		}
	}
	if q.updateBoxStatusStmt != nil {
		if cerr := q.updateBoxStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateBoxStatusStmt: %w", cerr)
		}
	}
	if q.upsertSSHHostKeyStmt != nil {
		if cerr := q.upsertSSHHostKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertSSHHostKeyStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                     DBTX
	tx                                     *sql.Tx
	allocExistsForUserStmt                 *sql.Stmt
	deleteAuthCookieStmt                   *sql.Stmt
	deleteAuthCookieByValueStmt            *sql.Stmt
	deleteAuthCookiesByUserIDStmt          *sql.Stmt
	deleteEmailVerificationByTokenStmt     *sql.Stmt
	deletePendingSSHKeyByTokenStmt         *sql.Stmt
	getAllUserEventsStmt                   *sql.Stmt
	getAllocByUserIDStmt                   *sql.Stmt
	getAllocsByHostStmt                    *sql.Stmt
	getAuthCookieInfoStmt                  *sql.Stmt
	getAuthTokenInfoStmt                   *sql.Stmt
	getBoxByNameStmt                       *sql.Stmt
	getBoxByNameAndAllocStmt               *sql.Stmt
	getBoxDetailsForSetupStmt              *sql.Stmt
	getBoxSSHDetailsStmt                   *sql.Stmt
	getBoxesByHostStmt                     *sql.Stmt
	getBoxesForAllocStmt                   *sql.Stmt
	getBoxesForUserDashboardStmt           *sql.Stmt
	getCtrhostByAllocIDStmt                *sql.Stmt
	getEmailBySSHKeyStmt                   *sql.Stmt
	getEmailByUserIDStmt                   *sql.Stmt
	getEmailVerificationByEmailStmt        *sql.Stmt
	getEmailVerificationByPartialTokenStmt *sql.Stmt
	getEmailVerificationByTokenStmt        *sql.Stmt
	getFirstUserIDStmt                     *sql.Stmt
	getPendingSSHKeyByTokenStmt            *sql.Stmt
	getPendingSSHKeyEmailByPublicKeyStmt   *sql.Stmt
	getSSHHostKeyStmt                      *sql.Stmt
	getSSHHostPublicKeyStmt                *sql.Stmt
	getSSHKeysForUserStmt                  *sql.Stmt
	getUserByEmailStmt                     *sql.Stmt
	getUserEventCountStmt                  *sql.Stmt
	getUserIDByEmailStmt                   *sql.Stmt
	getUserIDBySSHKeyStmt                  *sql.Stmt
	getUserWithDetailsStmt                 *sql.Stmt
	getUserWithSSHKeyStmt                  *sql.Stmt
	insertAllocStmt                        *sql.Stmt
	insertAuthCookieStmt                   *sql.Stmt
	insertBoxStmt                          *sql.Stmt
	insertEmailVerificationStmt            *sql.Stmt
	insertOrReplaceEmailVerificationStmt   *sql.Stmt
	insertSSHKeyStmt                       *sql.Stmt
	insertSSHKeyForEmailUserStmt           *sql.Stmt
	insertUserStmt                         *sql.Stmt
	recordUserEventStmt                    *sql.Stmt
	updateAuthCookieLastUsedStmt           *sql.Stmt
	updateAuthTokenUsedAtStmt              *sql.Stmt
	updateBoxContainerAndStatusStmt        *sql.Stmt
	updateBoxContainerIDAndStatusStmt      *sql.Stmt
	updateBoxSSHDetailsStmt                *sql.Stmt
	updateBoxStatusStmt                    *sql.Stmt
	upsertSSHHostKeyStmt                   *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                     tx,
		tx:                                     tx,
		allocExistsForUserStmt:                 q.allocExistsForUserStmt,
		deleteAuthCookieStmt:                   q.deleteAuthCookieStmt,
		deleteAuthCookieByValueStmt:            q.deleteAuthCookieByValueStmt,
		deleteAuthCookiesByUserIDStmt:          q.deleteAuthCookiesByUserIDStmt,
		deleteEmailVerificationByTokenStmt:     q.deleteEmailVerificationByTokenStmt,
		deletePendingSSHKeyByTokenStmt:         q.deletePendingSSHKeyByTokenStmt,
		getAllUserEventsStmt:                   q.getAllUserEventsStmt,
		getAllocByUserIDStmt:                   q.getAllocByUserIDStmt,
		getAllocsByHostStmt:                    q.getAllocsByHostStmt,
		getAuthCookieInfoStmt:                  q.getAuthCookieInfoStmt,
		getAuthTokenInfoStmt:                   q.getAuthTokenInfoStmt,
		getBoxByNameStmt:                       q.getBoxByNameStmt,
		getBoxByNameAndAllocStmt:               q.getBoxByNameAndAllocStmt,
		getBoxDetailsForSetupStmt:              q.getBoxDetailsForSetupStmt,
		getBoxSSHDetailsStmt:                   q.getBoxSSHDetailsStmt,
		getBoxesByHostStmt:                     q.getBoxesByHostStmt,
		getBoxesForAllocStmt:                   q.getBoxesForAllocStmt,
		getBoxesForUserDashboardStmt:           q.getBoxesForUserDashboardStmt,
		getCtrhostByAllocIDStmt:                q.getCtrhostByAllocIDStmt,
		getEmailBySSHKeyStmt:                   q.getEmailBySSHKeyStmt,
		getEmailByUserIDStmt:                   q.getEmailByUserIDStmt,
		getEmailVerificationByEmailStmt:        q.getEmailVerificationByEmailStmt,
		getEmailVerificationByPartialTokenStmt: q.getEmailVerificationByPartialTokenStmt,
		getEmailVerificationByTokenStmt:        q.getEmailVerificationByTokenStmt,
		getFirstUserIDStmt:                     q.getFirstUserIDStmt,
		getPendingSSHKeyByTokenStmt:            q.getPendingSSHKeyByTokenStmt,
		getPendingSSHKeyEmailByPublicKeyStmt:   q.getPendingSSHKeyEmailByPublicKeyStmt,
		getSSHHostKeyStmt:                      q.getSSHHostKeyStmt,
		getSSHHostPublicKeyStmt:                q.getSSHHostPublicKeyStmt,
		getSSHKeysForUserStmt:                  q.getSSHKeysForUserStmt,
		getUserByEmailStmt:                     q.getUserByEmailStmt,
		getUserEventCountStmt:                  q.getUserEventCountStmt,
		getUserIDByEmailStmt:                   q.getUserIDByEmailStmt,
		getUserIDBySSHKeyStmt:                  q.getUserIDBySSHKeyStmt,
		getUserWithDetailsStmt:                 q.getUserWithDetailsStmt,
		getUserWithSSHKeyStmt:                  q.getUserWithSSHKeyStmt,
		insertAllocStmt:                        q.insertAllocStmt,
		insertAuthCookieStmt:                   q.insertAuthCookieStmt,
		insertBoxStmt:                          q.insertBoxStmt,
		insertEmailVerificationStmt:            q.insertEmailVerificationStmt,
		insertOrReplaceEmailVerificationStmt:   q.insertOrReplaceEmailVerificationStmt,
		insertSSHKeyStmt:                       q.insertSSHKeyStmt,
		insertSSHKeyForEmailUserStmt:           q.insertSSHKeyForEmailUserStmt,
		insertUserStmt:                         q.insertUserStmt,
		recordUserEventStmt:                    q.recordUserEventStmt,
		updateAuthCookieLastUsedStmt:           q.updateAuthCookieLastUsedStmt,
		updateAuthTokenUsedAtStmt:              q.updateAuthTokenUsedAtStmt,
		updateBoxContainerAndStatusStmt:        q.updateBoxContainerAndStatusStmt,
		updateBoxContainerIDAndStatusStmt:      q.updateBoxContainerIDAndStatusStmt,
		updateBoxSSHDetailsStmt:                q.updateBoxSSHDetailsStmt,
		updateBoxStatusStmt:                    q.updateBoxStatusStmt,
		upsertSSHHostKeyStmt:                   q.upsertSSHHostKeyStmt,
	}
}
