// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package exedb

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.activateAccountStmt, err = db.PrepareContext(ctx, activateAccount); err != nil {
		return nil, fmt.Errorf("error preparing query ActivateAccount: %w", err)
	}
	if q.boxNamedStmt, err = db.PrepareContext(ctx, boxNamed); err != nil {
		return nil, fmt.Errorf("error preparing query BoxNamed: %w", err)
	}
	if q.boxWithNameExistsStmt, err = db.PrepareContext(ctx, boxWithNameExists); err != nil {
		return nil, fmt.Errorf("error preparing query BoxWithNameExists: %w", err)
	}
	if q.boxWithOwnerNamedStmt, err = db.PrepareContext(ctx, boxWithOwnerNamed); err != nil {
		return nil, fmt.Errorf("error preparing query BoxWithOwnerNamed: %w", err)
	}
	if q.boxesForUserStmt, err = db.PrepareContext(ctx, boxesForUser); err != nil {
		return nil, fmt.Errorf("error preparing query BoxesForUser: %w", err)
	}
	if q.cleanupExpiredPasskeyChallengesStmt, err = db.PrepareContext(ctx, cleanupExpiredPasskeyChallenges); err != nil {
		return nil, fmt.Errorf("error preparing query CleanupExpiredPasskeyChallenges: %w", err)
	}
	if q.clearPreferredExeletStmt, err = db.PrepareContext(ctx, clearPreferredExelet); err != nil {
		return nil, fmt.Errorf("error preparing query ClearPreferredExelet: %w", err)
	}
	if q.countBoxShareLinksStmt, err = db.PrepareContext(ctx, countBoxShareLinks); err != nil {
		return nil, fmt.Errorf("error preparing query CountBoxShareLinks: %w", err)
	}
	if q.countBoxSharesStmt, err = db.PrepareContext(ctx, countBoxShares); err != nil {
		return nil, fmt.Errorf("error preparing query CountBoxShares: %w", err)
	}
	if q.countBoxesStmt, err = db.PrepareContext(ctx, countBoxes); err != nil {
		return nil, fmt.Errorf("error preparing query CountBoxes: %w", err)
	}
	if q.countBoxesForUserStmt, err = db.PrepareContext(ctx, countBoxesForUser); err != nil {
		return nil, fmt.Errorf("error preparing query CountBoxesForUser: %w", err)
	}
	if q.countDevUsersStmt, err = db.PrepareContext(ctx, countDevUsers); err != nil {
		return nil, fmt.Errorf("error preparing query CountDevUsers: %w", err)
	}
	if q.countIPShardsStmt, err = db.PrepareContext(ctx, countIPShards); err != nil {
		return nil, fmt.Errorf("error preparing query CountIPShards: %w", err)
	}
	if q.countLoginUsersStmt, err = db.PrepareContext(ctx, countLoginUsers); err != nil {
		return nil, fmt.Errorf("error preparing query CountLoginUsers: %w", err)
	}
	if q.countPendingBoxSharesStmt, err = db.PrepareContext(ctx, countPendingBoxShares); err != nil {
		return nil, fmt.Errorf("error preparing query CountPendingBoxShares: %w", err)
	}
	if q.countUsersWithBoxesStmt, err = db.PrepareContext(ctx, countUsersWithBoxes); err != nil {
		return nil, fmt.Errorf("error preparing query CountUsersWithBoxes: %w", err)
	}
	if q.createBoxShareStmt, err = db.PrepareContext(ctx, createBoxShare); err != nil {
		return nil, fmt.Errorf("error preparing query CreateBoxShare: %w", err)
	}
	if q.createBoxShareLinkStmt, err = db.PrepareContext(ctx, createBoxShareLink); err != nil {
		return nil, fmt.Errorf("error preparing query CreateBoxShareLink: %w", err)
	}
	if q.createPendingBoxShareStmt, err = db.PrepareContext(ctx, createPendingBoxShare); err != nil {
		return nil, fmt.Errorf("error preparing query CreatePendingBoxShare: %w", err)
	}
	if q.deleteAuthCookieStmt, err = db.PrepareContext(ctx, deleteAuthCookie); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAuthCookie: %w", err)
	}
	if q.deleteAuthCookieByValueStmt, err = db.PrepareContext(ctx, deleteAuthCookieByValue); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAuthCookieByValue: %w", err)
	}
	if q.deleteAuthCookiesByUserIDStmt, err = db.PrepareContext(ctx, deleteAuthCookiesByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAuthCookiesByUserID: %w", err)
	}
	if q.deleteBoxStmt, err = db.PrepareContext(ctx, deleteBox); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBox: %w", err)
	}
	if q.deleteBoxIPShardStmt, err = db.PrepareContext(ctx, deleteBoxIPShard); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBoxIPShard: %w", err)
	}
	if q.deleteBoxShareByBoxAndUserStmt, err = db.PrepareContext(ctx, deleteBoxShareByBoxAndUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBoxShareByBoxAndUser: %w", err)
	}
	if q.deleteBoxShareLinkByBoxAndTokenStmt, err = db.PrepareContext(ctx, deleteBoxShareLinkByBoxAndToken); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBoxShareLinkByBoxAndToken: %w", err)
	}
	if q.deleteEmailVerificationByTokenStmt, err = db.PrepareContext(ctx, deleteEmailVerificationByToken); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteEmailVerificationByToken: %w", err)
	}
	if q.deletePasskeyStmt, err = db.PrepareContext(ctx, deletePasskey); err != nil {
		return nil, fmt.Errorf("error preparing query DeletePasskey: %w", err)
	}
	if q.deletePasskeyChallengeStmt, err = db.PrepareContext(ctx, deletePasskeyChallenge); err != nil {
		return nil, fmt.Errorf("error preparing query DeletePasskeyChallenge: %w", err)
	}
	if q.deletePendingBoxShareByBoxAndEmailStmt, err = db.PrepareContext(ctx, deletePendingBoxShareByBoxAndEmail); err != nil {
		return nil, fmt.Errorf("error preparing query DeletePendingBoxShareByBoxAndEmail: %w", err)
	}
	if q.deletePendingSSHKeyByTokenStmt, err = db.PrepareContext(ctx, deletePendingSSHKeyByToken); err != nil {
		return nil, fmt.Errorf("error preparing query DeletePendingSSHKeyByToken: %w", err)
	}
	if q.deleteSSHKeyForUserStmt, err = db.PrepareContext(ctx, deleteSSHKeyForUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSSHKeyForUser: %w", err)
	}
	if q.deleteTagResolutionStmt, err = db.PrepareContext(ctx, deleteTagResolution); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteTagResolution: %w", err)
	}
	if q.getAccountStmt, err = db.PrepareContext(ctx, getAccount); err != nil {
		return nil, fmt.Errorf("error preparing query GetAccount: %w", err)
	}
	if q.getAccountByUserIDStmt, err = db.PrepareContext(ctx, getAccountByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetAccountByUserID: %w", err)
	}
	if q.getAllBoxShareLinksByBoxIDStmt, err = db.PrepareContext(ctx, getAllBoxShareLinksByBoxID); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllBoxShareLinksByBoxID: %w", err)
	}
	if q.getAllUserEventsStmt, err = db.PrepareContext(ctx, getAllUserEvents); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllUserEvents: %w", err)
	}
	if q.getAuthCookieInfoStmt, err = db.PrepareContext(ctx, getAuthCookieInfo); err != nil {
		return nil, fmt.Errorf("error preparing query GetAuthCookieInfo: %w", err)
	}
	if q.getAuthTokenInfoStmt, err = db.PrepareContext(ctx, getAuthTokenInfo); err != nil {
		return nil, fmt.Errorf("error preparing query GetAuthTokenInfo: %w", err)
	}
	if q.getBoxByNameAndAllocStmt, err = db.PrepareContext(ctx, getBoxByNameAndAlloc); err != nil {
		return nil, fmt.Errorf("error preparing query GetBoxByNameAndAlloc: %w", err)
	}
	if q.getBoxByNameWithSupportAccessStmt, err = db.PrepareContext(ctx, getBoxByNameWithSupportAccess); err != nil {
		return nil, fmt.Errorf("error preparing query GetBoxByNameWithSupportAccess: %w", err)
	}
	if q.getBoxByUserAndShardStmt, err = db.PrepareContext(ctx, getBoxByUserAndShard); err != nil {
		return nil, fmt.Errorf("error preparing query GetBoxByUserAndShard: %w", err)
	}
	if q.getBoxDetailsForSetupStmt, err = db.PrepareContext(ctx, getBoxDetailsForSetup); err != nil {
		return nil, fmt.Errorf("error preparing query GetBoxDetailsForSetup: %w", err)
	}
	if q.getBoxIPShardStmt, err = db.PrepareContext(ctx, getBoxIPShard); err != nil {
		return nil, fmt.Errorf("error preparing query GetBoxIPShard: %w", err)
	}
	if q.getBoxOwnerEmailByContainerIDStmt, err = db.PrepareContext(ctx, getBoxOwnerEmailByContainerID); err != nil {
		return nil, fmt.Errorf("error preparing query GetBoxOwnerEmailByContainerID: %w", err)
	}
	if q.getBoxSSHDetailsStmt, err = db.PrepareContext(ctx, getBoxSSHDetails); err != nil {
		return nil, fmt.Errorf("error preparing query GetBoxSSHDetails: %w", err)
	}
	if q.getBoxShareLinkByTokenAndBoxIDStmt, err = db.PrepareContext(ctx, getBoxShareLinkByTokenAndBoxID); err != nil {
		return nil, fmt.Errorf("error preparing query GetBoxShareLinkByTokenAndBoxID: %w", err)
	}
	if q.getBoxShareLinksByBoxIDStmt, err = db.PrepareContext(ctx, getBoxShareLinksByBoxID); err != nil {
		return nil, fmt.Errorf("error preparing query GetBoxShareLinksByBoxID: %w", err)
	}
	if q.getBoxSharesByBoxIDStmt, err = db.PrepareContext(ctx, getBoxSharesByBoxID); err != nil {
		return nil, fmt.Errorf("error preparing query GetBoxSharesByBoxID: %w", err)
	}
	if q.getBoxSupportAccessAllowedStmt, err = db.PrepareContext(ctx, getBoxSupportAccessAllowed); err != nil {
		return nil, fmt.Errorf("error preparing query GetBoxSupportAccessAllowed: %w", err)
	}
	if q.getBoxesByHostStmt, err = db.PrepareContext(ctx, getBoxesByHost); err != nil {
		return nil, fmt.Errorf("error preparing query GetBoxesByHost: %w", err)
	}
	if q.getBoxesForUserDashboardStmt, err = db.PrepareContext(ctx, getBoxesForUserDashboard); err != nil {
		return nil, fmt.Errorf("error preparing query GetBoxesForUserDashboard: %w", err)
	}
	if q.getBoxesSharedWithUserStmt, err = db.PrepareContext(ctx, getBoxesSharedWithUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetBoxesSharedWithUser: %w", err)
	}
	if q.getEmailAddressQualityByEmailStmt, err = db.PrepareContext(ctx, getEmailAddressQualityByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetEmailAddressQualityByEmail: %w", err)
	}
	if q.getEmailBySSHKeyStmt, err = db.PrepareContext(ctx, getEmailBySSHKey); err != nil {
		return nil, fmt.Errorf("error preparing query GetEmailBySSHKey: %w", err)
	}
	if q.getEmailByUserIDStmt, err = db.PrepareContext(ctx, getEmailByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetEmailByUserID: %w", err)
	}
	if q.getEmailVerificationByPartialTokenStmt, err = db.PrepareContext(ctx, getEmailVerificationByPartialToken); err != nil {
		return nil, fmt.Errorf("error preparing query GetEmailVerificationByPartialToken: %w", err)
	}
	if q.getEmailVerificationByTokenStmt, err = db.PrepareContext(ctx, getEmailVerificationByToken); err != nil {
		return nil, fmt.Errorf("error preparing query GetEmailVerificationByToken: %w", err)
	}
	if q.getHLLSketchStmt, err = db.PrepareContext(ctx, getHLLSketch); err != nil {
		return nil, fmt.Errorf("error preparing query GetHLLSketch: %w", err)
	}
	if q.getIPShardByBoxNameStmt, err = db.PrepareContext(ctx, getIPShardByBoxName); err != nil {
		return nil, fmt.Errorf("error preparing query GetIPShardByBoxName: %w", err)
	}
	if q.getLoginCreationDisabledStmt, err = db.PrepareContext(ctx, getLoginCreationDisabled); err != nil {
		return nil, fmt.Errorf("error preparing query GetLoginCreationDisabled: %w", err)
	}
	if q.getNewThrottleEmailPatternsStmt, err = db.PrepareContext(ctx, getNewThrottleEmailPatterns); err != nil {
		return nil, fmt.Errorf("error preparing query GetNewThrottleEmailPatterns: %w", err)
	}
	if q.getNewThrottleEnabledStmt, err = db.PrepareContext(ctx, getNewThrottleEnabled); err != nil {
		return nil, fmt.Errorf("error preparing query GetNewThrottleEnabled: %w", err)
	}
	if q.getNewThrottleMessageStmt, err = db.PrepareContext(ctx, getNewThrottleMessage); err != nil {
		return nil, fmt.Errorf("error preparing query GetNewThrottleMessage: %w", err)
	}
	if q.getPasskeyByCredentialIDStmt, err = db.PrepareContext(ctx, getPasskeyByCredentialID); err != nil {
		return nil, fmt.Errorf("error preparing query GetPasskeyByCredentialID: %w", err)
	}
	if q.getPasskeyChallengeStmt, err = db.PrepareContext(ctx, getPasskeyChallenge); err != nil {
		return nil, fmt.Errorf("error preparing query GetPasskeyChallenge: %w", err)
	}
	if q.getPasskeysByUserIDStmt, err = db.PrepareContext(ctx, getPasskeysByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetPasskeysByUserID: %w", err)
	}
	if q.getPendingBoxSharesByBoxIDStmt, err = db.PrepareContext(ctx, getPendingBoxSharesByBoxID); err != nil {
		return nil, fmt.Errorf("error preparing query GetPendingBoxSharesByBoxID: %w", err)
	}
	if q.getPendingBoxSharesByEmailStmt, err = db.PrepareContext(ctx, getPendingBoxSharesByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetPendingBoxSharesByEmail: %w", err)
	}
	if q.getPendingSSHKeyByTokenStmt, err = db.PrepareContext(ctx, getPendingSSHKeyByToken); err != nil {
		return nil, fmt.Errorf("error preparing query GetPendingSSHKeyByToken: %w", err)
	}
	if q.getPendingSSHKeyEmailByPublicKeyStmt, err = db.PrepareContext(ctx, getPendingSSHKeyEmailByPublicKey); err != nil {
		return nil, fmt.Errorf("error preparing query GetPendingSSHKeyEmailByPublicKey: %w", err)
	}
	if q.getPreferredExeletStmt, err = db.PrepareContext(ctx, getPreferredExelet); err != nil {
		return nil, fmt.Errorf("error preparing query GetPreferredExelet: %w", err)
	}
	if q.getProxyBearerTokenStmt, err = db.PrepareContext(ctx, getProxyBearerToken); err != nil {
		return nil, fmt.Errorf("error preparing query GetProxyBearerToken: %w", err)
	}
	if q.getSSHHostKeyStmt, err = db.PrepareContext(ctx, getSSHHostKey); err != nil {
		return nil, fmt.Errorf("error preparing query GetSSHHostKey: %w", err)
	}
	if q.getSSHKeysForUserStmt, err = db.PrepareContext(ctx, getSSHKeysForUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetSSHKeysForUser: %w", err)
	}
	if q.getSSHKeysForUserByEmailStmt, err = db.PrepareContext(ctx, getSSHKeysForUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetSSHKeysForUserByEmail: %w", err)
	}
	if q.getShardPublicIPStmt, err = db.PrepareContext(ctx, getShardPublicIP); err != nil {
		return nil, fmt.Errorf("error preparing query GetShardPublicIP: %w", err)
	}
	if q.getSiteCookiesForUserStmt, err = db.PrepareContext(ctx, getSiteCookiesForUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetSiteCookiesForUser: %w", err)
	}
	if q.getTagResolutionStmt, err = db.PrepareContext(ctx, getTagResolution); err != nil {
		return nil, fmt.Errorf("error preparing query GetTagResolution: %w", err)
	}
	if q.getTagsNeedingRefreshStmt, err = db.PrepareContext(ctx, getTagsNeedingRefresh); err != nil {
		return nil, fmt.Errorf("error preparing query GetTagsNeedingRefresh: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getUserEmailCountForDateStmt, err = db.PrepareContext(ctx, getUserEmailCountForDate); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserEmailCountForDate: %w", err)
	}
	if q.getUserIDByEmailStmt, err = db.PrepareContext(ctx, getUserIDByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserIDByEmail: %w", err)
	}
	if q.getUserIDBySSHKeyStmt, err = db.PrepareContext(ctx, getUserIDBySSHKey); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserIDBySSHKey: %w", err)
	}
	if q.getUserNewVMCreationDisabledStmt, err = db.PrepareContext(ctx, getUserNewVMCreationDisabled); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserNewVMCreationDisabled: %w", err)
	}
	if q.getUserRootSupportStmt, err = db.PrepareContext(ctx, getUserRootSupport); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserRootSupport: %w", err)
	}
	if q.getUserWithDetailsStmt, err = db.PrepareContext(ctx, getUserWithDetails); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserWithDetails: %w", err)
	}
	if q.getUserWithSSHKeyStmt, err = db.PrepareContext(ctx, getUserWithSSHKey); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserWithSSHKey: %w", err)
	}
	if q.hasUserAccessToBoxStmt, err = db.PrepareContext(ctx, hasUserAccessToBox); err != nil {
		return nil, fmt.Errorf("error preparing query HasUserAccessToBox: %w", err)
	}
	if q.incrementSeenOnHostsStmt, err = db.PrepareContext(ctx, incrementSeenOnHosts); err != nil {
		return nil, fmt.Errorf("error preparing query IncrementSeenOnHosts: %w", err)
	}
	if q.incrementShareLinkUsageStmt, err = db.PrepareContext(ctx, incrementShareLinkUsage); err != nil {
		return nil, fmt.Errorf("error preparing query IncrementShareLinkUsage: %w", err)
	}
	if q.incrementUserEmailCountStmt, err = db.PrepareContext(ctx, incrementUserEmailCount); err != nil {
		return nil, fmt.Errorf("error preparing query IncrementUserEmailCount: %w", err)
	}
	if q.insertAccountStmt, err = db.PrepareContext(ctx, insertAccount); err != nil {
		return nil, fmt.Errorf("error preparing query InsertAccount: %w", err)
	}
	if q.insertAuthCookieStmt, err = db.PrepareContext(ctx, insertAuthCookie); err != nil {
		return nil, fmt.Errorf("error preparing query InsertAuthCookie: %w", err)
	}
	if q.insertBoxStmt, err = db.PrepareContext(ctx, insertBox); err != nil {
		return nil, fmt.Errorf("error preparing query InsertBox: %w", err)
	}
	if q.insertBoxIPShardStmt, err = db.PrepareContext(ctx, insertBoxIPShard); err != nil {
		return nil, fmt.Errorf("error preparing query InsertBoxIPShard: %w", err)
	}
	if q.insertDeletedBoxStmt, err = db.PrepareContext(ctx, insertDeletedBox); err != nil {
		return nil, fmt.Errorf("error preparing query InsertDeletedBox: %w", err)
	}
	if q.insertEmailAddressQualityStmt, err = db.PrepareContext(ctx, insertEmailAddressQuality); err != nil {
		return nil, fmt.Errorf("error preparing query InsertEmailAddressQuality: %w", err)
	}
	if q.insertEmailVerificationStmt, err = db.PrepareContext(ctx, insertEmailVerification); err != nil {
		return nil, fmt.Errorf("error preparing query InsertEmailVerification: %w", err)
	}
	if q.insertOrReplaceEmailVerificationStmt, err = db.PrepareContext(ctx, insertOrReplaceEmailVerification); err != nil {
		return nil, fmt.Errorf("error preparing query InsertOrReplaceEmailVerification: %w", err)
	}
	if q.insertPasskeyStmt, err = db.PrepareContext(ctx, insertPasskey); err != nil {
		return nil, fmt.Errorf("error preparing query InsertPasskey: %w", err)
	}
	if q.insertPasskeyChallengeStmt, err = db.PrepareContext(ctx, insertPasskeyChallenge); err != nil {
		return nil, fmt.Errorf("error preparing query InsertPasskeyChallenge: %w", err)
	}
	if q.insertPendingSSHKeyStmt, err = db.PrepareContext(ctx, insertPendingSSHKey); err != nil {
		return nil, fmt.Errorf("error preparing query InsertPendingSSHKey: %w", err)
	}
	if q.insertProxyBearerTokenStmt, err = db.PrepareContext(ctx, insertProxyBearerToken); err != nil {
		return nil, fmt.Errorf("error preparing query InsertProxyBearerToken: %w", err)
	}
	if q.insertSSHKeyStmt, err = db.PrepareContext(ctx, insertSSHKey); err != nil {
		return nil, fmt.Errorf("error preparing query InsertSSHKey: %w", err)
	}
	if q.insertSSHKeyForEmailUserStmt, err = db.PrepareContext(ctx, insertSSHKeyForEmailUser); err != nil {
		return nil, fmt.Errorf("error preparing query InsertSSHKeyForEmailUser: %w", err)
	}
	if q.insertTagResolutionHistoryStmt, err = db.PrepareContext(ctx, insertTagResolutionHistory); err != nil {
		return nil, fmt.Errorf("error preparing query InsertTagResolutionHistory: %w", err)
	}
	if q.insertUserStmt, err = db.PrepareContext(ctx, insertUser); err != nil {
		return nil, fmt.Errorf("error preparing query InsertUser: %w", err)
	}
	if q.listAllAccountsStmt, err = db.PrepareContext(ctx, listAllAccounts); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllAccounts: %w", err)
	}
	if q.listAllUsersStmt, err = db.PrepareContext(ctx, listAllUsers); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllUsers: %w", err)
	}
	if q.listIPShardsStmt, err = db.PrepareContext(ctx, listIPShards); err != nil {
		return nil, fmt.Errorf("error preparing query ListIPShards: %w", err)
	}
	if q.listIPShardsForUserStmt, err = db.PrepareContext(ctx, listIPShardsForUser); err != nil {
		return nil, fmt.Errorf("error preparing query ListIPShardsForUser: %w", err)
	}
	if q.recordUserEventStmt, err = db.PrepareContext(ctx, recordUserEvent); err != nil {
		return nil, fmt.Errorf("error preparing query RecordUserEvent: %w", err)
	}
	if q.sSHKeyForBoxNamedStmt, err = db.PrepareContext(ctx, sSHKeyForBoxNamed); err != nil {
		return nil, fmt.Errorf("error preparing query SSHKeyForBoxNamed: %w", err)
	}
	if q.setBoxSupportAccessAllowedStmt, err = db.PrepareContext(ctx, setBoxSupportAccessAllowed); err != nil {
		return nil, fmt.Errorf("error preparing query SetBoxSupportAccessAllowed: %w", err)
	}
	if q.setLoginCreationDisabledStmt, err = db.PrepareContext(ctx, setLoginCreationDisabled); err != nil {
		return nil, fmt.Errorf("error preparing query SetLoginCreationDisabled: %w", err)
	}
	if q.setNewThrottleEmailPatternsStmt, err = db.PrepareContext(ctx, setNewThrottleEmailPatterns); err != nil {
		return nil, fmt.Errorf("error preparing query SetNewThrottleEmailPatterns: %w", err)
	}
	if q.setNewThrottleEnabledStmt, err = db.PrepareContext(ctx, setNewThrottleEnabled); err != nil {
		return nil, fmt.Errorf("error preparing query SetNewThrottleEnabled: %w", err)
	}
	if q.setNewThrottleMessageStmt, err = db.PrepareContext(ctx, setNewThrottleMessage); err != nil {
		return nil, fmt.Errorf("error preparing query SetNewThrottleMessage: %w", err)
	}
	if q.setPreferredExeletStmt, err = db.PrepareContext(ctx, setPreferredExelet); err != nil {
		return nil, fmt.Errorf("error preparing query SetPreferredExelet: %w", err)
	}
	if q.setUserNewVMCreationDisabledStmt, err = db.PrepareContext(ctx, setUserNewVMCreationDisabled); err != nil {
		return nil, fmt.Errorf("error preparing query SetUserNewVMCreationDisabled: %w", err)
	}
	if q.setUserRootSupportStmt, err = db.PrepareContext(ctx, setUserRootSupport); err != nil {
		return nil, fmt.Errorf("error preparing query SetUserRootSupport: %w", err)
	}
	if q.updateAuthCookieLastUsedStmt, err = db.PrepareContext(ctx, updateAuthCookieLastUsed); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAuthCookieLastUsed: %w", err)
	}
	if q.updateAuthTokenUsedAtStmt, err = db.PrepareContext(ctx, updateAuthTokenUsedAt); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAuthTokenUsedAt: %w", err)
	}
	if q.updateBoxContainerAndStatusStmt, err = db.PrepareContext(ctx, updateBoxContainerAndStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateBoxContainerAndStatus: %w", err)
	}
	if q.updateBoxContainerIDAndStatusStmt, err = db.PrepareContext(ctx, updateBoxContainerIDAndStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateBoxContainerIDAndStatus: %w", err)
	}
	if q.updateBoxRoutesStmt, err = db.PrepareContext(ctx, updateBoxRoutes); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateBoxRoutes: %w", err)
	}
	if q.updateBoxSSHDetailsStmt, err = db.PrepareContext(ctx, updateBoxSSHDetails); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateBoxSSHDetails: %w", err)
	}
	if q.updateBoxStatusStmt, err = db.PrepareContext(ctx, updateBoxStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateBoxStatus: %w", err)
	}
	if q.updatePasskeySignCountStmt, err = db.PrepareContext(ctx, updatePasskeySignCount); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePasskeySignCount: %w", err)
	}
	if q.updateProxyBearerTokenLastUsedStmt, err = db.PrepareContext(ctx, updateProxyBearerTokenLastUsed); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateProxyBearerTokenLastUsed: %w", err)
	}
	if q.updateTagResolutionCheckedStmt, err = db.PrepareContext(ctx, updateTagResolutionChecked); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateTagResolutionChecked: %w", err)
	}
	if q.updateTagResolutionDigestStmt, err = db.PrepareContext(ctx, updateTagResolutionDigest); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateTagResolutionDigest: %w", err)
	}
	if q.upsertHLLSketchStmt, err = db.PrepareContext(ctx, upsertHLLSketch); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertHLLSketch: %w", err)
	}
	if q.upsertIPShardStmt, err = db.PrepareContext(ctx, upsertIPShard); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertIPShard: %w", err)
	}
	if q.upsertSSHHostKeyStmt, err = db.PrepareContext(ctx, upsertSSHHostKey); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertSSHHostKey: %w", err)
	}
	if q.upsertSSHKeyForUserStmt, err = db.PrepareContext(ctx, upsertSSHKeyForUser); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertSSHKeyForUser: %w", err)
	}
	if q.upsertTagResolutionStmt, err = db.PrepareContext(ctx, upsertTagResolution); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertTagResolution: %w", err)
	}
	if q.userHasAuthCookieStmt, err = db.PrepareContext(ctx, userHasAuthCookie); err != nil {
		return nil, fmt.Errorf("error preparing query UserHasAuthCookie: %w", err)
	}
	if q.userIsPayingStmt, err = db.PrepareContext(ctx, userIsPaying); err != nil {
		return nil, fmt.Errorf("error preparing query UserIsPaying: %w", err)
	}
	if q.userNeedsBillingStmt, err = db.PrepareContext(ctx, userNeedsBilling); err != nil {
		return nil, fmt.Errorf("error preparing query UserNeedsBilling: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.activateAccountStmt != nil {
		if cerr := q.activateAccountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing activateAccountStmt: %w", cerr)
		}
	}
	if q.boxNamedStmt != nil {
		if cerr := q.boxNamedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing boxNamedStmt: %w", cerr)
		}
	}
	if q.boxWithNameExistsStmt != nil {
		if cerr := q.boxWithNameExistsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing boxWithNameExistsStmt: %w", cerr)
		}
	}
	if q.boxWithOwnerNamedStmt != nil {
		if cerr := q.boxWithOwnerNamedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing boxWithOwnerNamedStmt: %w", cerr)
		}
	}
	if q.boxesForUserStmt != nil {
		if cerr := q.boxesForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing boxesForUserStmt: %w", cerr)
		}
	}
	if q.cleanupExpiredPasskeyChallengesStmt != nil {
		if cerr := q.cleanupExpiredPasskeyChallengesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing cleanupExpiredPasskeyChallengesStmt: %w", cerr)
		}
	}
	if q.clearPreferredExeletStmt != nil {
		if cerr := q.clearPreferredExeletStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearPreferredExeletStmt: %w", cerr)
		}
	}
	if q.countBoxShareLinksStmt != nil {
		if cerr := q.countBoxShareLinksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countBoxShareLinksStmt: %w", cerr)
		}
	}
	if q.countBoxSharesStmt != nil {
		if cerr := q.countBoxSharesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countBoxSharesStmt: %w", cerr)
		}
	}
	if q.countBoxesStmt != nil {
		if cerr := q.countBoxesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countBoxesStmt: %w", cerr)
		}
	}
	if q.countBoxesForUserStmt != nil {
		if cerr := q.countBoxesForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countBoxesForUserStmt: %w", cerr)
		}
	}
	if q.countDevUsersStmt != nil {
		if cerr := q.countDevUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countDevUsersStmt: %w", cerr)
		}
	}
	if q.countIPShardsStmt != nil {
		if cerr := q.countIPShardsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countIPShardsStmt: %w", cerr)
		}
	}
	if q.countLoginUsersStmt != nil {
		if cerr := q.countLoginUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countLoginUsersStmt: %w", cerr)
		}
	}
	if q.countPendingBoxSharesStmt != nil {
		if cerr := q.countPendingBoxSharesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countPendingBoxSharesStmt: %w", cerr)
		}
	}
	if q.countUsersWithBoxesStmt != nil {
		if cerr := q.countUsersWithBoxesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countUsersWithBoxesStmt: %w", cerr)
		}
	}
	if q.createBoxShareStmt != nil {
		if cerr := q.createBoxShareStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createBoxShareStmt: %w", cerr)
		}
	}
	if q.createBoxShareLinkStmt != nil {
		if cerr := q.createBoxShareLinkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createBoxShareLinkStmt: %w", cerr)
		}
	}
	if q.createPendingBoxShareStmt != nil {
		if cerr := q.createPendingBoxShareStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createPendingBoxShareStmt: %w", cerr)
		}
	}
	if q.deleteAuthCookieStmt != nil {
		if cerr := q.deleteAuthCookieStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAuthCookieStmt: %w", cerr)
		}
	}
	if q.deleteAuthCookieByValueStmt != nil {
		if cerr := q.deleteAuthCookieByValueStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAuthCookieByValueStmt: %w", cerr)
		}
	}
	if q.deleteAuthCookiesByUserIDStmt != nil {
		if cerr := q.deleteAuthCookiesByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAuthCookiesByUserIDStmt: %w", cerr)
		}
	}
	if q.deleteBoxStmt != nil {
		if cerr := q.deleteBoxStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBoxStmt: %w", cerr)
		}
	}
	if q.deleteBoxIPShardStmt != nil {
		if cerr := q.deleteBoxIPShardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBoxIPShardStmt: %w", cerr)
		}
	}
	if q.deleteBoxShareByBoxAndUserStmt != nil {
		if cerr := q.deleteBoxShareByBoxAndUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBoxShareByBoxAndUserStmt: %w", cerr)
		}
	}
	if q.deleteBoxShareLinkByBoxAndTokenStmt != nil {
		if cerr := q.deleteBoxShareLinkByBoxAndTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBoxShareLinkByBoxAndTokenStmt: %w", cerr)
		}
	}
	if q.deleteEmailVerificationByTokenStmt != nil {
		if cerr := q.deleteEmailVerificationByTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteEmailVerificationByTokenStmt: %w", cerr)
		}
	}
	if q.deletePasskeyStmt != nil {
		if cerr := q.deletePasskeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deletePasskeyStmt: %w", cerr)
		}
	}
	if q.deletePasskeyChallengeStmt != nil {
		if cerr := q.deletePasskeyChallengeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deletePasskeyChallengeStmt: %w", cerr)
		}
	}
	if q.deletePendingBoxShareByBoxAndEmailStmt != nil {
		if cerr := q.deletePendingBoxShareByBoxAndEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deletePendingBoxShareByBoxAndEmailStmt: %w", cerr)
		}
	}
	if q.deletePendingSSHKeyByTokenStmt != nil {
		if cerr := q.deletePendingSSHKeyByTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deletePendingSSHKeyByTokenStmt: %w", cerr)
		}
	}
	if q.deleteSSHKeyForUserStmt != nil {
		if cerr := q.deleteSSHKeyForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSSHKeyForUserStmt: %w", cerr)
		}
	}
	if q.deleteTagResolutionStmt != nil {
		if cerr := q.deleteTagResolutionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteTagResolutionStmt: %w", cerr)
		}
	}
	if q.getAccountStmt != nil {
		if cerr := q.getAccountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAccountStmt: %w", cerr)
		}
	}
	if q.getAccountByUserIDStmt != nil {
		if cerr := q.getAccountByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAccountByUserIDStmt: %w", cerr)
		}
	}
	if q.getAllBoxShareLinksByBoxIDStmt != nil {
		if cerr := q.getAllBoxShareLinksByBoxIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllBoxShareLinksByBoxIDStmt: %w", cerr)
		}
	}
	if q.getAllUserEventsStmt != nil {
		if cerr := q.getAllUserEventsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllUserEventsStmt: %w", cerr)
		}
	}
	if q.getAuthCookieInfoStmt != nil {
		if cerr := q.getAuthCookieInfoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAuthCookieInfoStmt: %w", cerr)
		}
	}
	if q.getAuthTokenInfoStmt != nil {
		if cerr := q.getAuthTokenInfoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAuthTokenInfoStmt: %w", cerr)
		}
	}
	if q.getBoxByNameAndAllocStmt != nil {
		if cerr := q.getBoxByNameAndAllocStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBoxByNameAndAllocStmt: %w", cerr)
		}
	}
	if q.getBoxByNameWithSupportAccessStmt != nil {
		if cerr := q.getBoxByNameWithSupportAccessStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBoxByNameWithSupportAccessStmt: %w", cerr)
		}
	}
	if q.getBoxByUserAndShardStmt != nil {
		if cerr := q.getBoxByUserAndShardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBoxByUserAndShardStmt: %w", cerr)
		}
	}
	if q.getBoxDetailsForSetupStmt != nil {
		if cerr := q.getBoxDetailsForSetupStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBoxDetailsForSetupStmt: %w", cerr)
		}
	}
	if q.getBoxIPShardStmt != nil {
		if cerr := q.getBoxIPShardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBoxIPShardStmt: %w", cerr)
		}
	}
	if q.getBoxOwnerEmailByContainerIDStmt != nil {
		if cerr := q.getBoxOwnerEmailByContainerIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBoxOwnerEmailByContainerIDStmt: %w", cerr)
		}
	}
	if q.getBoxSSHDetailsStmt != nil {
		if cerr := q.getBoxSSHDetailsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBoxSSHDetailsStmt: %w", cerr)
		}
	}
	if q.getBoxShareLinkByTokenAndBoxIDStmt != nil {
		if cerr := q.getBoxShareLinkByTokenAndBoxIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBoxShareLinkByTokenAndBoxIDStmt: %w", cerr)
		}
	}
	if q.getBoxShareLinksByBoxIDStmt != nil {
		if cerr := q.getBoxShareLinksByBoxIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBoxShareLinksByBoxIDStmt: %w", cerr)
		}
	}
	if q.getBoxSharesByBoxIDStmt != nil {
		if cerr := q.getBoxSharesByBoxIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBoxSharesByBoxIDStmt: %w", cerr)
		}
	}
	if q.getBoxSupportAccessAllowedStmt != nil {
		if cerr := q.getBoxSupportAccessAllowedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBoxSupportAccessAllowedStmt: %w", cerr)
		}
	}
	if q.getBoxesByHostStmt != nil {
		if cerr := q.getBoxesByHostStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBoxesByHostStmt: %w", cerr)
		}
	}
	if q.getBoxesForUserDashboardStmt != nil {
		if cerr := q.getBoxesForUserDashboardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBoxesForUserDashboardStmt: %w", cerr)
		}
	}
	if q.getBoxesSharedWithUserStmt != nil {
		if cerr := q.getBoxesSharedWithUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBoxesSharedWithUserStmt: %w", cerr)
		}
	}
	if q.getEmailAddressQualityByEmailStmt != nil {
		if cerr := q.getEmailAddressQualityByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getEmailAddressQualityByEmailStmt: %w", cerr)
		}
	}
	if q.getEmailBySSHKeyStmt != nil {
		if cerr := q.getEmailBySSHKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getEmailBySSHKeyStmt: %w", cerr)
		}
	}
	if q.getEmailByUserIDStmt != nil {
		if cerr := q.getEmailByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getEmailByUserIDStmt: %w", cerr)
		}
	}
	if q.getEmailVerificationByPartialTokenStmt != nil {
		if cerr := q.getEmailVerificationByPartialTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getEmailVerificationByPartialTokenStmt: %w", cerr)
		}
	}
	if q.getEmailVerificationByTokenStmt != nil {
		if cerr := q.getEmailVerificationByTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getEmailVerificationByTokenStmt: %w", cerr)
		}
	}
	if q.getHLLSketchStmt != nil {
		if cerr := q.getHLLSketchStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getHLLSketchStmt: %w", cerr)
		}
	}
	if q.getIPShardByBoxNameStmt != nil {
		if cerr := q.getIPShardByBoxNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getIPShardByBoxNameStmt: %w", cerr)
		}
	}
	if q.getLoginCreationDisabledStmt != nil {
		if cerr := q.getLoginCreationDisabledStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLoginCreationDisabledStmt: %w", cerr)
		}
	}
	if q.getNewThrottleEmailPatternsStmt != nil {
		if cerr := q.getNewThrottleEmailPatternsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNewThrottleEmailPatternsStmt: %w", cerr)
		}
	}
	if q.getNewThrottleEnabledStmt != nil {
		if cerr := q.getNewThrottleEnabledStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNewThrottleEnabledStmt: %w", cerr)
		}
	}
	if q.getNewThrottleMessageStmt != nil {
		if cerr := q.getNewThrottleMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNewThrottleMessageStmt: %w", cerr)
		}
	}
	if q.getPasskeyByCredentialIDStmt != nil {
		if cerr := q.getPasskeyByCredentialIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPasskeyByCredentialIDStmt: %w", cerr)
		}
	}
	if q.getPasskeyChallengeStmt != nil {
		if cerr := q.getPasskeyChallengeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPasskeyChallengeStmt: %w", cerr)
		}
	}
	if q.getPasskeysByUserIDStmt != nil {
		if cerr := q.getPasskeysByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPasskeysByUserIDStmt: %w", cerr)
		}
	}
	if q.getPendingBoxSharesByBoxIDStmt != nil {
		if cerr := q.getPendingBoxSharesByBoxIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPendingBoxSharesByBoxIDStmt: %w", cerr)
		}
	}
	if q.getPendingBoxSharesByEmailStmt != nil {
		if cerr := q.getPendingBoxSharesByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPendingBoxSharesByEmailStmt: %w", cerr)
		}
	}
	if q.getPendingSSHKeyByTokenStmt != nil {
		if cerr := q.getPendingSSHKeyByTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPendingSSHKeyByTokenStmt: %w", cerr)
		}
	}
	if q.getPendingSSHKeyEmailByPublicKeyStmt != nil {
		if cerr := q.getPendingSSHKeyEmailByPublicKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPendingSSHKeyEmailByPublicKeyStmt: %w", cerr)
		}
	}
	if q.getPreferredExeletStmt != nil {
		if cerr := q.getPreferredExeletStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPreferredExeletStmt: %w", cerr)
		}
	}
	if q.getProxyBearerTokenStmt != nil {
		if cerr := q.getProxyBearerTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProxyBearerTokenStmt: %w", cerr)
		}
	}
	if q.getSSHHostKeyStmt != nil {
		if cerr := q.getSSHHostKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSSHHostKeyStmt: %w", cerr)
		}
	}
	if q.getSSHKeysForUserStmt != nil {
		if cerr := q.getSSHKeysForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSSHKeysForUserStmt: %w", cerr)
		}
	}
	if q.getSSHKeysForUserByEmailStmt != nil {
		if cerr := q.getSSHKeysForUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSSHKeysForUserByEmailStmt: %w", cerr)
		}
	}
	if q.getShardPublicIPStmt != nil {
		if cerr := q.getShardPublicIPStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getShardPublicIPStmt: %w", cerr)
		}
	}
	if q.getSiteCookiesForUserStmt != nil {
		if cerr := q.getSiteCookiesForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSiteCookiesForUserStmt: %w", cerr)
		}
	}
	if q.getTagResolutionStmt != nil {
		if cerr := q.getTagResolutionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTagResolutionStmt: %w", cerr)
		}
	}
	if q.getTagsNeedingRefreshStmt != nil {
		if cerr := q.getTagsNeedingRefreshStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTagsNeedingRefreshStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserEmailCountForDateStmt != nil {
		if cerr := q.getUserEmailCountForDateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserEmailCountForDateStmt: %w", cerr)
		}
	}
	if q.getUserIDByEmailStmt != nil {
		if cerr := q.getUserIDByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserIDByEmailStmt: %w", cerr)
		}
	}
	if q.getUserIDBySSHKeyStmt != nil {
		if cerr := q.getUserIDBySSHKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserIDBySSHKeyStmt: %w", cerr)
		}
	}
	if q.getUserNewVMCreationDisabledStmt != nil {
		if cerr := q.getUserNewVMCreationDisabledStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserNewVMCreationDisabledStmt: %w", cerr)
		}
	}
	if q.getUserRootSupportStmt != nil {
		if cerr := q.getUserRootSupportStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserRootSupportStmt: %w", cerr)
		}
	}
	if q.getUserWithDetailsStmt != nil {
		if cerr := q.getUserWithDetailsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserWithDetailsStmt: %w", cerr)
		}
	}
	if q.getUserWithSSHKeyStmt != nil {
		if cerr := q.getUserWithSSHKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserWithSSHKeyStmt: %w", cerr)
		}
	}
	if q.hasUserAccessToBoxStmt != nil {
		if cerr := q.hasUserAccessToBoxStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing hasUserAccessToBoxStmt: %w", cerr)
		}
	}
	if q.incrementSeenOnHostsStmt != nil {
		if cerr := q.incrementSeenOnHostsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing incrementSeenOnHostsStmt: %w", cerr)
		}
	}
	if q.incrementShareLinkUsageStmt != nil {
		if cerr := q.incrementShareLinkUsageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing incrementShareLinkUsageStmt: %w", cerr)
		}
	}
	if q.incrementUserEmailCountStmt != nil {
		if cerr := q.incrementUserEmailCountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing incrementUserEmailCountStmt: %w", cerr)
		}
	}
	if q.insertAccountStmt != nil {
		if cerr := q.insertAccountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertAccountStmt: %w", cerr)
		}
	}
	if q.insertAuthCookieStmt != nil {
		if cerr := q.insertAuthCookieStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertAuthCookieStmt: %w", cerr)
		}
	}
	if q.insertBoxStmt != nil {
		if cerr := q.insertBoxStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertBoxStmt: %w", cerr)
		}
	}
	if q.insertBoxIPShardStmt != nil {
		if cerr := q.insertBoxIPShardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertBoxIPShardStmt: %w", cerr)
		}
	}
	if q.insertDeletedBoxStmt != nil {
		if cerr := q.insertDeletedBoxStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertDeletedBoxStmt: %w", cerr)
		}
	}
	if q.insertEmailAddressQualityStmt != nil {
		if cerr := q.insertEmailAddressQualityStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertEmailAddressQualityStmt: %w", cerr)
		}
	}
	if q.insertEmailVerificationStmt != nil {
		if cerr := q.insertEmailVerificationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertEmailVerificationStmt: %w", cerr)
		}
	}
	if q.insertOrReplaceEmailVerificationStmt != nil {
		if cerr := q.insertOrReplaceEmailVerificationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertOrReplaceEmailVerificationStmt: %w", cerr)
		}
	}
	if q.insertPasskeyStmt != nil {
		if cerr := q.insertPasskeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertPasskeyStmt: %w", cerr)
		}
	}
	if q.insertPasskeyChallengeStmt != nil {
		if cerr := q.insertPasskeyChallengeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertPasskeyChallengeStmt: %w", cerr)
		}
	}
	if q.insertPendingSSHKeyStmt != nil {
		if cerr := q.insertPendingSSHKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertPendingSSHKeyStmt: %w", cerr)
		}
	}
	if q.insertProxyBearerTokenStmt != nil {
		if cerr := q.insertProxyBearerTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertProxyBearerTokenStmt: %w", cerr)
		}
	}
	if q.insertSSHKeyStmt != nil {
		if cerr := q.insertSSHKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertSSHKeyStmt: %w", cerr)
		}
	}
	if q.insertSSHKeyForEmailUserStmt != nil {
		if cerr := q.insertSSHKeyForEmailUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertSSHKeyForEmailUserStmt: %w", cerr)
		}
	}
	if q.insertTagResolutionHistoryStmt != nil {
		if cerr := q.insertTagResolutionHistoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertTagResolutionHistoryStmt: %w", cerr)
		}
	}
	if q.insertUserStmt != nil {
		if cerr := q.insertUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertUserStmt: %w", cerr)
		}
	}
	if q.listAllAccountsStmt != nil {
		if cerr := q.listAllAccountsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllAccountsStmt: %w", cerr)
		}
	}
	if q.listAllUsersStmt != nil {
		if cerr := q.listAllUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllUsersStmt: %w", cerr)
		}
	}
	if q.listIPShardsStmt != nil {
		if cerr := q.listIPShardsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listIPShardsStmt: %w", cerr)
		}
	}
	if q.listIPShardsForUserStmt != nil {
		if cerr := q.listIPShardsForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listIPShardsForUserStmt: %w", cerr)
		}
	}
	if q.recordUserEventStmt != nil {
		if cerr := q.recordUserEventStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing recordUserEventStmt: %w", cerr)
		}
	}
	if q.sSHKeyForBoxNamedStmt != nil {
		if cerr := q.sSHKeyForBoxNamedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing sSHKeyForBoxNamedStmt: %w", cerr)
		}
	}
	if q.setBoxSupportAccessAllowedStmt != nil {
		if cerr := q.setBoxSupportAccessAllowedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setBoxSupportAccessAllowedStmt: %w", cerr)
		}
	}
	if q.setLoginCreationDisabledStmt != nil {
		if cerr := q.setLoginCreationDisabledStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setLoginCreationDisabledStmt: %w", cerr)
		}
	}
	if q.setNewThrottleEmailPatternsStmt != nil {
		if cerr := q.setNewThrottleEmailPatternsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setNewThrottleEmailPatternsStmt: %w", cerr)
		}
	}
	if q.setNewThrottleEnabledStmt != nil {
		if cerr := q.setNewThrottleEnabledStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setNewThrottleEnabledStmt: %w", cerr)
		}
	}
	if q.setNewThrottleMessageStmt != nil {
		if cerr := q.setNewThrottleMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setNewThrottleMessageStmt: %w", cerr)
		}
	}
	if q.setPreferredExeletStmt != nil {
		if cerr := q.setPreferredExeletStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setPreferredExeletStmt: %w", cerr)
		}
	}
	if q.setUserNewVMCreationDisabledStmt != nil {
		if cerr := q.setUserNewVMCreationDisabledStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setUserNewVMCreationDisabledStmt: %w", cerr)
		}
	}
	if q.setUserRootSupportStmt != nil {
		if cerr := q.setUserRootSupportStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setUserRootSupportStmt: %w", cerr)
		}
	}
	if q.updateAuthCookieLastUsedStmt != nil {
		if cerr := q.updateAuthCookieLastUsedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAuthCookieLastUsedStmt: %w", cerr)
		}
	}
	if q.updateAuthTokenUsedAtStmt != nil {
		if cerr := q.updateAuthTokenUsedAtStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAuthTokenUsedAtStmt: %w", cerr)
		}
	}
	if q.updateBoxContainerAndStatusStmt != nil {
		if cerr := q.updateBoxContainerAndStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateBoxContainerAndStatusStmt: %w", cerr)
		}
	}
	if q.updateBoxContainerIDAndStatusStmt != nil {
		if cerr := q.updateBoxContainerIDAndStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateBoxContainerIDAndStatusStmt: %w", cerr)
		}
	}
	if q.updateBoxRoutesStmt != nil {
		if cerr := q.updateBoxRoutesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateBoxRoutesStmt: %w", cerr)
		}
	}
	if q.updateBoxSSHDetailsStmt != nil {
		if cerr := q.updateBoxSSHDetailsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateBoxSSHDetailsStmt: %w", cerr)
		}
	}
	if q.updateBoxStatusStmt != nil {
		if cerr := q.updateBoxStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateBoxStatusStmt: %w", cerr)
		}
	}
	if q.updatePasskeySignCountStmt != nil {
		if cerr := q.updatePasskeySignCountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePasskeySignCountStmt: %w", cerr)
		}
	}
	if q.updateProxyBearerTokenLastUsedStmt != nil {
		if cerr := q.updateProxyBearerTokenLastUsedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateProxyBearerTokenLastUsedStmt: %w", cerr)
		}
	}
	if q.updateTagResolutionCheckedStmt != nil {
		if cerr := q.updateTagResolutionCheckedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateTagResolutionCheckedStmt: %w", cerr)
		}
	}
	if q.updateTagResolutionDigestStmt != nil {
		if cerr := q.updateTagResolutionDigestStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateTagResolutionDigestStmt: %w", cerr)
		}
	}
	if q.upsertHLLSketchStmt != nil {
		if cerr := q.upsertHLLSketchStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertHLLSketchStmt: %w", cerr)
		}
	}
	if q.upsertIPShardStmt != nil {
		if cerr := q.upsertIPShardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertIPShardStmt: %w", cerr)
		}
	}
	if q.upsertSSHHostKeyStmt != nil {
		if cerr := q.upsertSSHHostKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertSSHHostKeyStmt: %w", cerr)
		}
	}
	if q.upsertSSHKeyForUserStmt != nil {
		if cerr := q.upsertSSHKeyForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertSSHKeyForUserStmt: %w", cerr)
		}
	}
	if q.upsertTagResolutionStmt != nil {
		if cerr := q.upsertTagResolutionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertTagResolutionStmt: %w", cerr)
		}
	}
	if q.userHasAuthCookieStmt != nil {
		if cerr := q.userHasAuthCookieStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing userHasAuthCookieStmt: %w", cerr)
		}
	}
	if q.userIsPayingStmt != nil {
		if cerr := q.userIsPayingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing userIsPayingStmt: %w", cerr)
		}
	}
	if q.userNeedsBillingStmt != nil {
		if cerr := q.userNeedsBillingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing userNeedsBillingStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                     DBTX
	tx                                     *sql.Tx
	activateAccountStmt                    *sql.Stmt
	boxNamedStmt                           *sql.Stmt
	boxWithNameExistsStmt                  *sql.Stmt
	boxWithOwnerNamedStmt                  *sql.Stmt
	boxesForUserStmt                       *sql.Stmt
	cleanupExpiredPasskeyChallengesStmt    *sql.Stmt
	clearPreferredExeletStmt               *sql.Stmt
	countBoxShareLinksStmt                 *sql.Stmt
	countBoxSharesStmt                     *sql.Stmt
	countBoxesStmt                         *sql.Stmt
	countBoxesForUserStmt                  *sql.Stmt
	countDevUsersStmt                      *sql.Stmt
	countIPShardsStmt                      *sql.Stmt
	countLoginUsersStmt                    *sql.Stmt
	countPendingBoxSharesStmt              *sql.Stmt
	countUsersWithBoxesStmt                *sql.Stmt
	createBoxShareStmt                     *sql.Stmt
	createBoxShareLinkStmt                 *sql.Stmt
	createPendingBoxShareStmt              *sql.Stmt
	deleteAuthCookieStmt                   *sql.Stmt
	deleteAuthCookieByValueStmt            *sql.Stmt
	deleteAuthCookiesByUserIDStmt          *sql.Stmt
	deleteBoxStmt                          *sql.Stmt
	deleteBoxIPShardStmt                   *sql.Stmt
	deleteBoxShareByBoxAndUserStmt         *sql.Stmt
	deleteBoxShareLinkByBoxAndTokenStmt    *sql.Stmt
	deleteEmailVerificationByTokenStmt     *sql.Stmt
	deletePasskeyStmt                      *sql.Stmt
	deletePasskeyChallengeStmt             *sql.Stmt
	deletePendingBoxShareByBoxAndEmailStmt *sql.Stmt
	deletePendingSSHKeyByTokenStmt         *sql.Stmt
	deleteSSHKeyForUserStmt                *sql.Stmt
	deleteTagResolutionStmt                *sql.Stmt
	getAccountStmt                         *sql.Stmt
	getAccountByUserIDStmt                 *sql.Stmt
	getAllBoxShareLinksByBoxIDStmt         *sql.Stmt
	getAllUserEventsStmt                   *sql.Stmt
	getAuthCookieInfoStmt                  *sql.Stmt
	getAuthTokenInfoStmt                   *sql.Stmt
	getBoxByNameAndAllocStmt               *sql.Stmt
	getBoxByNameWithSupportAccessStmt      *sql.Stmt
	getBoxByUserAndShardStmt               *sql.Stmt
	getBoxDetailsForSetupStmt              *sql.Stmt
	getBoxIPShardStmt                      *sql.Stmt
	getBoxOwnerEmailByContainerIDStmt      *sql.Stmt
	getBoxSSHDetailsStmt                   *sql.Stmt
	getBoxShareLinkByTokenAndBoxIDStmt     *sql.Stmt
	getBoxShareLinksByBoxIDStmt            *sql.Stmt
	getBoxSharesByBoxIDStmt                *sql.Stmt
	getBoxSupportAccessAllowedStmt         *sql.Stmt
	getBoxesByHostStmt                     *sql.Stmt
	getBoxesForUserDashboardStmt           *sql.Stmt
	getBoxesSharedWithUserStmt             *sql.Stmt
	getEmailAddressQualityByEmailStmt      *sql.Stmt
	getEmailBySSHKeyStmt                   *sql.Stmt
	getEmailByUserIDStmt                   *sql.Stmt
	getEmailVerificationByPartialTokenStmt *sql.Stmt
	getEmailVerificationByTokenStmt        *sql.Stmt
	getHLLSketchStmt                       *sql.Stmt
	getIPShardByBoxNameStmt                *sql.Stmt
	getLoginCreationDisabledStmt           *sql.Stmt
	getNewThrottleEmailPatternsStmt        *sql.Stmt
	getNewThrottleEnabledStmt              *sql.Stmt
	getNewThrottleMessageStmt              *sql.Stmt
	getPasskeyByCredentialIDStmt           *sql.Stmt
	getPasskeyChallengeStmt                *sql.Stmt
	getPasskeysByUserIDStmt                *sql.Stmt
	getPendingBoxSharesByBoxIDStmt         *sql.Stmt
	getPendingBoxSharesByEmailStmt         *sql.Stmt
	getPendingSSHKeyByTokenStmt            *sql.Stmt
	getPendingSSHKeyEmailByPublicKeyStmt   *sql.Stmt
	getPreferredExeletStmt                 *sql.Stmt
	getProxyBearerTokenStmt                *sql.Stmt
	getSSHHostKeyStmt                      *sql.Stmt
	getSSHKeysForUserStmt                  *sql.Stmt
	getSSHKeysForUserByEmailStmt           *sql.Stmt
	getShardPublicIPStmt                   *sql.Stmt
	getSiteCookiesForUserStmt              *sql.Stmt
	getTagResolutionStmt                   *sql.Stmt
	getTagsNeedingRefreshStmt              *sql.Stmt
	getUserByEmailStmt                     *sql.Stmt
	getUserEmailCountForDateStmt           *sql.Stmt
	getUserIDByEmailStmt                   *sql.Stmt
	getUserIDBySSHKeyStmt                  *sql.Stmt
	getUserNewVMCreationDisabledStmt       *sql.Stmt
	getUserRootSupportStmt                 *sql.Stmt
	getUserWithDetailsStmt                 *sql.Stmt
	getUserWithSSHKeyStmt                  *sql.Stmt
	hasUserAccessToBoxStmt                 *sql.Stmt
	incrementSeenOnHostsStmt               *sql.Stmt
	incrementShareLinkUsageStmt            *sql.Stmt
	incrementUserEmailCountStmt            *sql.Stmt
	insertAccountStmt                      *sql.Stmt
	insertAuthCookieStmt                   *sql.Stmt
	insertBoxStmt                          *sql.Stmt
	insertBoxIPShardStmt                   *sql.Stmt
	insertDeletedBoxStmt                   *sql.Stmt
	insertEmailAddressQualityStmt          *sql.Stmt
	insertEmailVerificationStmt            *sql.Stmt
	insertOrReplaceEmailVerificationStmt   *sql.Stmt
	insertPasskeyStmt                      *sql.Stmt
	insertPasskeyChallengeStmt             *sql.Stmt
	insertPendingSSHKeyStmt                *sql.Stmt
	insertProxyBearerTokenStmt             *sql.Stmt
	insertSSHKeyStmt                       *sql.Stmt
	insertSSHKeyForEmailUserStmt           *sql.Stmt
	insertTagResolutionHistoryStmt         *sql.Stmt
	insertUserStmt                         *sql.Stmt
	listAllAccountsStmt                    *sql.Stmt
	listAllUsersStmt                       *sql.Stmt
	listIPShardsStmt                       *sql.Stmt
	listIPShardsForUserStmt                *sql.Stmt
	recordUserEventStmt                    *sql.Stmt
	sSHKeyForBoxNamedStmt                  *sql.Stmt
	setBoxSupportAccessAllowedStmt         *sql.Stmt
	setLoginCreationDisabledStmt           *sql.Stmt
	setNewThrottleEmailPatternsStmt        *sql.Stmt
	setNewThrottleEnabledStmt              *sql.Stmt
	setNewThrottleMessageStmt              *sql.Stmt
	setPreferredExeletStmt                 *sql.Stmt
	setUserNewVMCreationDisabledStmt       *sql.Stmt
	setUserRootSupportStmt                 *sql.Stmt
	updateAuthCookieLastUsedStmt           *sql.Stmt
	updateAuthTokenUsedAtStmt              *sql.Stmt
	updateBoxContainerAndStatusStmt        *sql.Stmt
	updateBoxContainerIDAndStatusStmt      *sql.Stmt
	updateBoxRoutesStmt                    *sql.Stmt
	updateBoxSSHDetailsStmt                *sql.Stmt
	updateBoxStatusStmt                    *sql.Stmt
	updatePasskeySignCountStmt             *sql.Stmt
	updateProxyBearerTokenLastUsedStmt     *sql.Stmt
	updateTagResolutionCheckedStmt         *sql.Stmt
	updateTagResolutionDigestStmt          *sql.Stmt
	upsertHLLSketchStmt                    *sql.Stmt
	upsertIPShardStmt                      *sql.Stmt
	upsertSSHHostKeyStmt                   *sql.Stmt
	upsertSSHKeyForUserStmt                *sql.Stmt
	upsertTagResolutionStmt                *sql.Stmt
	userHasAuthCookieStmt                  *sql.Stmt
	userIsPayingStmt                       *sql.Stmt
	userNeedsBillingStmt                   *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                     tx,
		tx:                                     tx,
		activateAccountStmt:                    q.activateAccountStmt,
		boxNamedStmt:                           q.boxNamedStmt,
		boxWithNameExistsStmt:                  q.boxWithNameExistsStmt,
		boxWithOwnerNamedStmt:                  q.boxWithOwnerNamedStmt,
		boxesForUserStmt:                       q.boxesForUserStmt,
		cleanupExpiredPasskeyChallengesStmt:    q.cleanupExpiredPasskeyChallengesStmt,
		clearPreferredExeletStmt:               q.clearPreferredExeletStmt,
		countBoxShareLinksStmt:                 q.countBoxShareLinksStmt,
		countBoxSharesStmt:                     q.countBoxSharesStmt,
		countBoxesStmt:                         q.countBoxesStmt,
		countBoxesForUserStmt:                  q.countBoxesForUserStmt,
		countDevUsersStmt:                      q.countDevUsersStmt,
		countIPShardsStmt:                      q.countIPShardsStmt,
		countLoginUsersStmt:                    q.countLoginUsersStmt,
		countPendingBoxSharesStmt:              q.countPendingBoxSharesStmt,
		countUsersWithBoxesStmt:                q.countUsersWithBoxesStmt,
		createBoxShareStmt:                     q.createBoxShareStmt,
		createBoxShareLinkStmt:                 q.createBoxShareLinkStmt,
		createPendingBoxShareStmt:              q.createPendingBoxShareStmt,
		deleteAuthCookieStmt:                   q.deleteAuthCookieStmt,
		deleteAuthCookieByValueStmt:            q.deleteAuthCookieByValueStmt,
		deleteAuthCookiesByUserIDStmt:          q.deleteAuthCookiesByUserIDStmt,
		deleteBoxStmt:                          q.deleteBoxStmt,
		deleteBoxIPShardStmt:                   q.deleteBoxIPShardStmt,
		deleteBoxShareByBoxAndUserStmt:         q.deleteBoxShareByBoxAndUserStmt,
		deleteBoxShareLinkByBoxAndTokenStmt:    q.deleteBoxShareLinkByBoxAndTokenStmt,
		deleteEmailVerificationByTokenStmt:     q.deleteEmailVerificationByTokenStmt,
		deletePasskeyStmt:                      q.deletePasskeyStmt,
		deletePasskeyChallengeStmt:             q.deletePasskeyChallengeStmt,
		deletePendingBoxShareByBoxAndEmailStmt: q.deletePendingBoxShareByBoxAndEmailStmt,
		deletePendingSSHKeyByTokenStmt:         q.deletePendingSSHKeyByTokenStmt,
		deleteSSHKeyForUserStmt:                q.deleteSSHKeyForUserStmt,
		deleteTagResolutionStmt:                q.deleteTagResolutionStmt,
		getAccountStmt:                         q.getAccountStmt,
		getAccountByUserIDStmt:                 q.getAccountByUserIDStmt,
		getAllBoxShareLinksByBoxIDStmt:         q.getAllBoxShareLinksByBoxIDStmt,
		getAllUserEventsStmt:                   q.getAllUserEventsStmt,
		getAuthCookieInfoStmt:                  q.getAuthCookieInfoStmt,
		getAuthTokenInfoStmt:                   q.getAuthTokenInfoStmt,
		getBoxByNameAndAllocStmt:               q.getBoxByNameAndAllocStmt,
		getBoxByNameWithSupportAccessStmt:      q.getBoxByNameWithSupportAccessStmt,
		getBoxByUserAndShardStmt:               q.getBoxByUserAndShardStmt,
		getBoxDetailsForSetupStmt:              q.getBoxDetailsForSetupStmt,
		getBoxIPShardStmt:                      q.getBoxIPShardStmt,
		getBoxOwnerEmailByContainerIDStmt:      q.getBoxOwnerEmailByContainerIDStmt,
		getBoxSSHDetailsStmt:                   q.getBoxSSHDetailsStmt,
		getBoxShareLinkByTokenAndBoxIDStmt:     q.getBoxShareLinkByTokenAndBoxIDStmt,
		getBoxShareLinksByBoxIDStmt:            q.getBoxShareLinksByBoxIDStmt,
		getBoxSharesByBoxIDStmt:                q.getBoxSharesByBoxIDStmt,
		getBoxSupportAccessAllowedStmt:         q.getBoxSupportAccessAllowedStmt,
		getBoxesByHostStmt:                     q.getBoxesByHostStmt,
		getBoxesForUserDashboardStmt:           q.getBoxesForUserDashboardStmt,
		getBoxesSharedWithUserStmt:             q.getBoxesSharedWithUserStmt,
		getEmailAddressQualityByEmailStmt:      q.getEmailAddressQualityByEmailStmt,
		getEmailBySSHKeyStmt:                   q.getEmailBySSHKeyStmt,
		getEmailByUserIDStmt:                   q.getEmailByUserIDStmt,
		getEmailVerificationByPartialTokenStmt: q.getEmailVerificationByPartialTokenStmt,
		getEmailVerificationByTokenStmt:        q.getEmailVerificationByTokenStmt,
		getHLLSketchStmt:                       q.getHLLSketchStmt,
		getIPShardByBoxNameStmt:                q.getIPShardByBoxNameStmt,
		getLoginCreationDisabledStmt:           q.getLoginCreationDisabledStmt,
		getNewThrottleEmailPatternsStmt:        q.getNewThrottleEmailPatternsStmt,
		getNewThrottleEnabledStmt:              q.getNewThrottleEnabledStmt,
		getNewThrottleMessageStmt:              q.getNewThrottleMessageStmt,
		getPasskeyByCredentialIDStmt:           q.getPasskeyByCredentialIDStmt,
		getPasskeyChallengeStmt:                q.getPasskeyChallengeStmt,
		getPasskeysByUserIDStmt:                q.getPasskeysByUserIDStmt,
		getPendingBoxSharesByBoxIDStmt:         q.getPendingBoxSharesByBoxIDStmt,
		getPendingBoxSharesByEmailStmt:         q.getPendingBoxSharesByEmailStmt,
		getPendingSSHKeyByTokenStmt:            q.getPendingSSHKeyByTokenStmt,
		getPendingSSHKeyEmailByPublicKeyStmt:   q.getPendingSSHKeyEmailByPublicKeyStmt,
		getPreferredExeletStmt:                 q.getPreferredExeletStmt,
		getProxyBearerTokenStmt:                q.getProxyBearerTokenStmt,
		getSSHHostKeyStmt:                      q.getSSHHostKeyStmt,
		getSSHKeysForUserStmt:                  q.getSSHKeysForUserStmt,
		getSSHKeysForUserByEmailStmt:           q.getSSHKeysForUserByEmailStmt,
		getShardPublicIPStmt:                   q.getShardPublicIPStmt,
		getSiteCookiesForUserStmt:              q.getSiteCookiesForUserStmt,
		getTagResolutionStmt:                   q.getTagResolutionStmt,
		getTagsNeedingRefreshStmt:              q.getTagsNeedingRefreshStmt,
		getUserByEmailStmt:                     q.getUserByEmailStmt,
		getUserEmailCountForDateStmt:           q.getUserEmailCountForDateStmt,
		getUserIDByEmailStmt:                   q.getUserIDByEmailStmt,
		getUserIDBySSHKeyStmt:                  q.getUserIDBySSHKeyStmt,
		getUserNewVMCreationDisabledStmt:       q.getUserNewVMCreationDisabledStmt,
		getUserRootSupportStmt:                 q.getUserRootSupportStmt,
		getUserWithDetailsStmt:                 q.getUserWithDetailsStmt,
		getUserWithSSHKeyStmt:                  q.getUserWithSSHKeyStmt,
		hasUserAccessToBoxStmt:                 q.hasUserAccessToBoxStmt,
		incrementSeenOnHostsStmt:               q.incrementSeenOnHostsStmt,
		incrementShareLinkUsageStmt:            q.incrementShareLinkUsageStmt,
		incrementUserEmailCountStmt:            q.incrementUserEmailCountStmt,
		insertAccountStmt:                      q.insertAccountStmt,
		insertAuthCookieStmt:                   q.insertAuthCookieStmt,
		insertBoxStmt:                          q.insertBoxStmt,
		insertBoxIPShardStmt:                   q.insertBoxIPShardStmt,
		insertDeletedBoxStmt:                   q.insertDeletedBoxStmt,
		insertEmailAddressQualityStmt:          q.insertEmailAddressQualityStmt,
		insertEmailVerificationStmt:            q.insertEmailVerificationStmt,
		insertOrReplaceEmailVerificationStmt:   q.insertOrReplaceEmailVerificationStmt,
		insertPasskeyStmt:                      q.insertPasskeyStmt,
		insertPasskeyChallengeStmt:             q.insertPasskeyChallengeStmt,
		insertPendingSSHKeyStmt:                q.insertPendingSSHKeyStmt,
		insertProxyBearerTokenStmt:             q.insertProxyBearerTokenStmt,
		insertSSHKeyStmt:                       q.insertSSHKeyStmt,
		insertSSHKeyForEmailUserStmt:           q.insertSSHKeyForEmailUserStmt,
		insertTagResolutionHistoryStmt:         q.insertTagResolutionHistoryStmt,
		insertUserStmt:                         q.insertUserStmt,
		listAllAccountsStmt:                    q.listAllAccountsStmt,
		listAllUsersStmt:                       q.listAllUsersStmt,
		listIPShardsStmt:                       q.listIPShardsStmt,
		listIPShardsForUserStmt:                q.listIPShardsForUserStmt,
		recordUserEventStmt:                    q.recordUserEventStmt,
		sSHKeyForBoxNamedStmt:                  q.sSHKeyForBoxNamedStmt,
		setBoxSupportAccessAllowedStmt:         q.setBoxSupportAccessAllowedStmt,
		setLoginCreationDisabledStmt:           q.setLoginCreationDisabledStmt,
		setNewThrottleEmailPatternsStmt:        q.setNewThrottleEmailPatternsStmt,
		setNewThrottleEnabledStmt:              q.setNewThrottleEnabledStmt,
		setNewThrottleMessageStmt:              q.setNewThrottleMessageStmt,
		setPreferredExeletStmt:                 q.setPreferredExeletStmt,
		setUserNewVMCreationDisabledStmt:       q.setUserNewVMCreationDisabledStmt,
		setUserRootSupportStmt:                 q.setUserRootSupportStmt,
		updateAuthCookieLastUsedStmt:           q.updateAuthCookieLastUsedStmt,
		updateAuthTokenUsedAtStmt:              q.updateAuthTokenUsedAtStmt,
		updateBoxContainerAndStatusStmt:        q.updateBoxContainerAndStatusStmt,
		updateBoxContainerIDAndStatusStmt:      q.updateBoxContainerIDAndStatusStmt,
		updateBoxRoutesStmt:                    q.updateBoxRoutesStmt,
		updateBoxSSHDetailsStmt:                q.updateBoxSSHDetailsStmt,
		updateBoxStatusStmt:                    q.updateBoxStatusStmt,
		updatePasskeySignCountStmt:             q.updatePasskeySignCountStmt,
		updateProxyBearerTokenLastUsedStmt:     q.updateProxyBearerTokenLastUsedStmt,
		updateTagResolutionCheckedStmt:         q.updateTagResolutionCheckedStmt,
		updateTagResolutionDigestStmt:          q.updateTagResolutionDigestStmt,
		upsertHLLSketchStmt:                    q.upsertHLLSketchStmt,
		upsertIPShardStmt:                      q.upsertIPShardStmt,
		upsertSSHHostKeyStmt:                   q.upsertSSHHostKeyStmt,
		upsertSSHKeyForUserStmt:                q.upsertSSHKeyForUserStmt,
		upsertTagResolutionStmt:                q.upsertTagResolutionStmt,
		userHasAuthCookieStmt:                  q.userHasAuthCookieStmt,
		userIsPayingStmt:                       q.userIsPayingStmt,
		userNeedsBillingStmt:                   q.userNeedsBillingStmt,
	}
}
