// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deleted_boxes.sql

package exedb

import (
	"context"
)

const insertDeletedBox = `-- name: InsertDeletedBox :exec
INSERT INTO deleted_boxes (id, alloc_id) VALUES (?, ?)
`

type InsertDeletedBoxParams struct {
	ID      int64  `db:"id" json:"id"`
	AllocID string `db:"alloc_id" json:"alloc_id"`
}

func (q *Queries) InsertDeletedBox(ctx context.Context, arg InsertDeletedBoxParams) error {
	_, err := q.exec(ctx, q.insertDeletedBoxStmt, insertDeletedBox, arg.ID, arg.AllocID)
	return err
}
