// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: drip_sends.sql

package exedb

import (
	"context"
	"time"
)

const countBoxesEverForUser = `-- name: CountBoxesEverForUser :one
SELECT
    (SELECT COUNT(*) FROM boxes WHERE created_by_user_id = ?1)
    + (SELECT COUNT(*) FROM deleted_boxes WHERE user_id = ?1)
AS total
`

// Count all boxes a user has ever had (current + deleted).
func (q *Queries) CountBoxesEverForUser(ctx context.Context, createdByUserID string) (int64, error) {
	row := q.queryRow(ctx, q.countBoxesEverForUserStmt, countBoxesEverForUser, createdByUserID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countDripSendsSince = `-- name: CountDripSendsSince :one
SELECT COUNT(*) FROM drip_sends
WHERE user_id = ? AND status = 'sent' AND created_at >= ?
`

type CountDripSendsSinceParams struct {
	UserID    string    `db:"user_id" json:"user_id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) CountDripSendsSince(ctx context.Context, arg CountDripSendsSinceParams) (int64, error) {
	row := q.queryRow(ctx, q.countDripSendsSinceStmt, countDripSendsSince, arg.UserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDripSendsForUser = `-- name: GetDripSendsForUser :many
SELECT id, user_id, campaign, step, status, skip_reason, email_to, email_subject, email_body, created_at FROM drip_sends
WHERE user_id = ? AND campaign = ?
ORDER BY created_at ASC
`

type GetDripSendsForUserParams struct {
	UserID   string `db:"user_id" json:"user_id"`
	Campaign string `db:"campaign" json:"campaign"`
}

func (q *Queries) GetDripSendsForUser(ctx context.Context, arg GetDripSendsForUserParams) ([]DripSend, error) {
	rows, err := q.query(ctx, q.getDripSendsForUserStmt, getDripSendsForUser, arg.UserID, arg.Campaign)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DripSend{}
	for rows.Next() {
		var i DripSend
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Campaign,
			&i.Step,
			&i.Status,
			&i.SkipReason,
			&i.EmailTo,
			&i.EmailSubject,
			&i.EmailBody,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasDripSend = `-- name: HasDripSend :one
SELECT EXISTS (
    SELECT 1 FROM drip_sends
    WHERE user_id = ? AND campaign = ? AND step = ?
) AS has_send
`

type HasDripSendParams struct {
	UserID   string `db:"user_id" json:"user_id"`
	Campaign string `db:"campaign" json:"campaign"`
	Step     string `db:"step" json:"step"`
}

func (q *Queries) HasDripSend(ctx context.Context, arg HasDripSendParams) (int64, error) {
	row := q.queryRow(ctx, q.hasDripSendStmt, hasDripSend, arg.UserID, arg.Campaign, arg.Step)
	var has_send int64
	err := row.Scan(&has_send)
	return has_send, err
}

const hasUserUsedShareLinks = `-- name: HasUserUsedShareLinks :one
SELECT EXISTS (
    SELECT 1 FROM box_share_links WHERE created_by_user_id = ?
) AS has_shared
`

func (q *Queries) HasUserUsedShareLinks(ctx context.Context, createdByUserID string) (int64, error) {
	row := q.queryRow(ctx, q.hasUserUsedShareLinksStmt, hasUserUsedShareLinks, createdByUserID)
	var has_shared int64
	err := row.Scan(&has_shared)
	return has_shared, err
}

const hasUserUsedShelley = `-- name: HasUserUsedShelley :one
SELECT EXISTS (
    SELECT 1 FROM user_events WHERE user_id = ? AND event = 'used_repl'
) AS has_used
`

// Check if user has used shelley (recorded as a user_event).
func (q *Queries) HasUserUsedShelley(ctx context.Context, userID string) (int64, error) {
	row := q.queryRow(ctx, q.hasUserUsedShelleyStmt, hasUserUsedShelley, userID)
	var has_used int64
	err := row.Scan(&has_used)
	return has_used, err
}

const insertDripSend = `-- name: InsertDripSend :exec
INSERT INTO drip_sends (user_id, campaign, step, status, skip_reason, email_to, email_subject, email_body)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertDripSendParams struct {
	UserID       string  `db:"user_id" json:"user_id"`
	Campaign     string  `db:"campaign" json:"campaign"`
	Step         string  `db:"step" json:"step"`
	Status       string  `db:"status" json:"status"`
	SkipReason   *string `db:"skip_reason" json:"skip_reason"`
	EmailTo      *string `db:"email_to" json:"email_to"`
	EmailSubject *string `db:"email_subject" json:"email_subject"`
	EmailBody    *string `db:"email_body" json:"email_body"`
}

func (q *Queries) InsertDripSend(ctx context.Context, arg InsertDripSendParams) error {
	_, err := q.exec(ctx, q.insertDripSendStmt, insertDripSend,
		arg.UserID,
		arg.Campaign,
		arg.Step,
		arg.Status,
		arg.SkipReason,
		arg.EmailTo,
		arg.EmailSubject,
		arg.EmailBody,
	)
	return err
}

const listTrialUsersForDrip = `-- name: ListTrialUsersForDrip :many
SELECT
    u.user_id,
    u.email,
    u.region,
    ap.started_at AS trial_started_at,
    ap.trial_expires_at,
    CASE WHEN ap.ended_at IS NULL AND ap.plan_id LIKE 'trial:%' THEN 1 ELSE 0 END AS still_on_trial
FROM users u
JOIN accounts a ON a.created_by = u.user_id
JOIN account_plans ap ON ap.account_id = a.id
WHERE ap.plan_id LIKE 'trial:%'
  AND ap.started_at >= datetime('now', '-21 days')
  -- Only target users created after drip campaign deployment.
  AND u.created_at >= '2026-04-14'
  -- Exclude users who have upgraded: they have an active non-trial, non-basic plan.
  AND NOT EXISTS (
      SELECT 1 FROM account_plans ap2
      WHERE ap2.account_id = a.id
        AND ap2.ended_at IS NULL
        AND ap2.plan_id NOT LIKE 'trial:%'
        AND ap2.plan_id NOT LIKE 'basic:%'
        AND ap2.plan_id != 'restricted'
  )
  -- Exclude users who have active billing (i.e. paid/subscribed).
  AND NOT EXISTS (
      SELECT 1 FROM billing_events be
      WHERE be.account_id = a.id
        AND be.event_type = 'active'
        AND be.id = (
            SELECT be2.id FROM billing_events be2
            WHERE be2.account_id = a.id
            ORDER BY be2.event_at DESC, be2.id DESC
            LIMIT 1
        )
  )
ORDER BY ap.started_at ASC
`

type ListTrialUsersForDripRow struct {
	UserID         string     `db:"user_id" json:"user_id"`
	Email          string     `db:"email" json:"email"`
	Region         string     `db:"region" json:"region"`
	TrialStartedAt time.Time  `db:"trial_started_at" json:"trial_started_at"`
	TrialExpiresAt *time.Time `db:"trial_expires_at" json:"trial_expires_at"`
	StillOnTrial   int64      `db:"still_on_trial" json:"still_on_trial"`
}

// Returns users who are on a trial or were recently on a trial (for post-trial emails).
// Includes active trial users and users whose trial started within the last 21 days
// (to cover the day14 final email). Excludes users who have upgraded to a paid plan.
func (q *Queries) ListTrialUsersForDrip(ctx context.Context) ([]ListTrialUsersForDripRow, error) {
	rows, err := q.query(ctx, q.listTrialUsersForDripStmt, listTrialUsersForDrip)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrialUsersForDripRow{}
	for rows.Next() {
		var i ListTrialUsersForDripRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.Region,
			&i.TrialStartedAt,
			&i.TrialExpiresAt,
			&i.StillOnTrial,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
