// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_address_quality.sql

package exedb

import (
	"context"
)

const getEmailAddressQualityByEmail = `-- name: GetEmailAddressQualityByEmail :one
SELECT id, email, queried_at, response_json, disposable FROM email_address_quality WHERE email = ? ORDER BY queried_at DESC LIMIT 1
`

func (q *Queries) GetEmailAddressQualityByEmail(ctx context.Context, email string) (EmailAddressQuality, error) {
	row := q.queryRow(ctx, q.getEmailAddressQualityByEmailStmt, getEmailAddressQualityByEmail, email)
	var i EmailAddressQuality
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.QueriedAt,
		&i.ResponseJson,
		&i.Disposable,
	)
	return i, err
}

const insertEmailAddressQuality = `-- name: InsertEmailAddressQuality :exec
INSERT INTO email_address_quality (email, response_json) VALUES (?, ?)
`

type InsertEmailAddressQualityParams struct {
	Email        string `db:"email" json:"email"`
	ResponseJson string `db:"response_json" json:"response_json"`
}

func (q *Queries) InsertEmailAddressQuality(ctx context.Context, arg InsertEmailAddressQualityParams) error {
	_, err := q.exec(ctx, q.insertEmailAddressQualityStmt, insertEmailAddressQuality, arg.Email, arg.ResponseJson)
	return err
}
