// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_verifications.sql

package exedb

import (
	"context"
	"time"
)

const deleteEmailVerificationByToken = `-- name: DeleteEmailVerificationByToken :exec
DELETE FROM email_verifications WHERE token = ?
`

func (q *Queries) DeleteEmailVerificationByToken(ctx context.Context, token string) error {
	_, err := q.exec(ctx, q.deleteEmailVerificationByTokenStmt, deleteEmailVerificationByToken, token)
	return err
}

const getEmailVerificationByPartialToken = `-- name: GetEmailVerificationByPartialToken :one
SELECT user_id
FROM email_verifications
WHERE token = ? AND expires_at > datetime('now')
LIMIT 1
`

func (q *Queries) GetEmailVerificationByPartialToken(ctx context.Context, token string) (string, error) {
	row := q.queryRow(ctx, q.getEmailVerificationByPartialTokenStmt, getEmailVerificationByPartialToken, token)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const getEmailVerificationByToken = `-- name: GetEmailVerificationByToken :one
SELECT token, email, user_id, expires_at, created_at, verification_code, invite_code_id FROM email_verifications
WHERE token = ?
`

func (q *Queries) GetEmailVerificationByToken(ctx context.Context, token string) (EmailVerification, error) {
	row := q.queryRow(ctx, q.getEmailVerificationByTokenStmt, getEmailVerificationByToken, token)
	var i EmailVerification
	err := row.Scan(
		&i.Token,
		&i.Email,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.VerificationCode,
		&i.InviteCodeID,
	)
	return i, err
}

const insertEmailVerification = `-- name: InsertEmailVerification :exec
INSERT INTO email_verifications (token, email, user_id, expires_at, verification_code, invite_code_id)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertEmailVerificationParams struct {
	Token            string    `db:"token" json:"token"`
	Email            string    `db:"email" json:"email"`
	UserID           string    `db:"user_id" json:"user_id"`
	ExpiresAt        time.Time `db:"expires_at" json:"expires_at"`
	VerificationCode *string   `db:"verification_code" json:"verification_code"`
	InviteCodeID     *int64    `db:"invite_code_id" json:"invite_code_id"`
}

func (q *Queries) InsertEmailVerification(ctx context.Context, arg InsertEmailVerificationParams) error {
	_, err := q.exec(ctx, q.insertEmailVerificationStmt, insertEmailVerification,
		arg.Token,
		arg.Email,
		arg.UserID,
		arg.ExpiresAt,
		arg.VerificationCode,
		arg.InviteCodeID,
	)
	return err
}

const insertOrReplaceEmailVerification = `-- name: InsertOrReplaceEmailVerification :exec
INSERT OR REPLACE INTO email_verifications (token, user_id, email, expires_at, verification_code, invite_code_id)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertOrReplaceEmailVerificationParams struct {
	Token            string    `db:"token" json:"token"`
	UserID           string    `db:"user_id" json:"user_id"`
	Email            string    `db:"email" json:"email"`
	ExpiresAt        time.Time `db:"expires_at" json:"expires_at"`
	VerificationCode *string   `db:"verification_code" json:"verification_code"`
	InviteCodeID     *int64    `db:"invite_code_id" json:"invite_code_id"`
}

func (q *Queries) InsertOrReplaceEmailVerification(ctx context.Context, arg InsertOrReplaceEmailVerificationParams) error {
	_, err := q.exec(ctx, q.insertOrReplaceEmailVerificationStmt, insertOrReplaceEmailVerification,
		arg.Token,
		arg.UserID,
		arg.Email,
		arg.ExpiresAt,
		arg.VerificationCode,
		arg.InviteCodeID,
	)
	return err
}
