// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_quality_bypass.sql

package exedb

import (
	"context"
)

const deleteEmailQualityBypass = `-- name: DeleteEmailQualityBypass :exec
DELETE FROM email_quality_bypass WHERE email = ?
`

func (q *Queries) DeleteEmailQualityBypass(ctx context.Context, email string) error {
	_, err := q.exec(ctx, q.deleteEmailQualityBypassStmt, deleteEmailQualityBypass, email)
	return err
}

const insertEmailQualityBypass = `-- name: InsertEmailQualityBypass :exec
INSERT INTO email_quality_bypass (email, reason, added_by) VALUES (?, ?, ?)
`

type InsertEmailQualityBypassParams struct {
	Email   string `db:"email" json:"email"`
	Reason  string `db:"reason" json:"reason"`
	AddedBy string `db:"added_by" json:"added_by"`
}

func (q *Queries) InsertEmailQualityBypass(ctx context.Context, arg InsertEmailQualityBypassParams) error {
	_, err := q.exec(ctx, q.insertEmailQualityBypassStmt, insertEmailQualityBypass, arg.Email, arg.Reason, arg.AddedBy)
	return err
}

const isEmailQualityBypassed = `-- name: IsEmailQualityBypassed :one
SELECT EXISTS(SELECT 1 FROM email_quality_bypass WHERE email = ?) AS bypassed
`

func (q *Queries) IsEmailQualityBypassed(ctx context.Context, email string) (int64, error) {
	row := q.queryRow(ctx, q.isEmailQualityBypassedStmt, isEmailQualityBypassed, email)
	var bypassed int64
	err := row.Scan(&bypassed)
	return bypassed, err
}

const listEmailQualityBypass = `-- name: ListEmailQualityBypass :many
SELECT email, reason, added_at, added_by FROM email_quality_bypass ORDER BY added_at DESC
`

func (q *Queries) ListEmailQualityBypass(ctx context.Context) ([]EmailQualityBypass, error) {
	rows, err := q.query(ctx, q.listEmailQualityBypassStmt, listEmailQualityBypass)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailQualityBypass{}
	for rows.Next() {
		var i EmailQualityBypass
		if err := rows.Scan(
			&i.Email,
			&i.Reason,
			&i.AddedAt,
			&i.AddedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
