// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hll_sketches.sql

package exedb

import (
	"context"
)

const getHLLSketch = `-- name: GetHLLSketch :one
SELECT "key", data, updated_at FROM hll_sketches WHERE key = ?
`

func (q *Queries) GetHLLSketch(ctx context.Context, key string) (HllSketch, error) {
	row := q.queryRow(ctx, q.getHLLSketchStmt, getHLLSketch, key)
	var i HllSketch
	err := row.Scan(&i.Key, &i.Data, &i.UpdatedAt)
	return i, err
}

const upsertHLLSketch = `-- name: UpsertHLLSketch :exec
INSERT INTO hll_sketches (key, data, updated_at) VALUES (?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(key) DO UPDATE SET data = excluded.data, updated_at = CURRENT_TIMESTAMP
`

type UpsertHLLSketchParams struct {
	Key  string `db:"key" json:"key"`
	Data []byte `db:"data" json:"data"`
}

func (q *Queries) UpsertHLLSketch(ctx context.Context, arg UpsertHLLSketchParams) error {
	_, err := q.exec(ctx, q.upsertHLLSketchStmt, upsertHLLSketch, arg.Key, arg.Data)
	return err
}
