// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: integration_attachments.sql

package exedb

import (
	"context"
)

const deleteIntegrationAttachment = `-- name: DeleteIntegrationAttachment :exec
DELETE FROM integration_attachments WHERE integration_id = ? AND box_id = ?
`

type DeleteIntegrationAttachmentParams struct {
	IntegrationID string `db:"integration_id" json:"integration_id"`
	BoxID         int64  `db:"box_id" json:"box_id"`
}

func (q *Queries) DeleteIntegrationAttachment(ctx context.Context, arg DeleteIntegrationAttachmentParams) error {
	_, err := q.exec(ctx, q.deleteIntegrationAttachmentStmt, deleteIntegrationAttachment, arg.IntegrationID, arg.BoxID)
	return err
}

const deleteIntegrationAttachmentsByBoxID = `-- name: DeleteIntegrationAttachmentsByBoxID :exec
DELETE FROM integration_attachments WHERE box_id = ?
`

func (q *Queries) DeleteIntegrationAttachmentsByBoxID(ctx context.Context, boxID int64) error {
	_, err := q.exec(ctx, q.deleteIntegrationAttachmentsByBoxIDStmt, deleteIntegrationAttachmentsByBoxID, boxID)
	return err
}

const insertIntegrationAttachment = `-- name: InsertIntegrationAttachment :exec
INSERT INTO integration_attachments (integration_id, box_id)
VALUES (?, ?)
`

type InsertIntegrationAttachmentParams struct {
	IntegrationID string `db:"integration_id" json:"integration_id"`
	BoxID         int64  `db:"box_id" json:"box_id"`
}

func (q *Queries) InsertIntegrationAttachment(ctx context.Context, arg InsertIntegrationAttachmentParams) error {
	_, err := q.exec(ctx, q.insertIntegrationAttachmentStmt, insertIntegrationAttachment, arg.IntegrationID, arg.BoxID)
	return err
}

const listIntegrationAttachments = `-- name: ListIntegrationAttachments :many
SELECT integration_id, box_id, created_at
FROM integration_attachments
WHERE integration_id = ?
ORDER BY created_at DESC, rowid DESC
`

func (q *Queries) ListIntegrationAttachments(ctx context.Context, integrationID string) ([]IntegrationAttachment, error) {
	rows, err := q.query(ctx, q.listIntegrationAttachmentsStmt, listIntegrationAttachments, integrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IntegrationAttachment{}
	for rows.Next() {
		var i IntegrationAttachment
		if err := rows.Scan(&i.IntegrationID, &i.BoxID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
