// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ip_shards.sql

package exedb

import (
	"context"
)

const countIPShards = `-- name: CountIPShards :one
SELECT COUNT(*) FROM ip_shards
`

func (q *Queries) CountIPShards(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countIPShardsStmt, countIPShards)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getShardPublicIP = `-- name: GetShardPublicIP :one
SELECT public_ip
FROM ip_shards
WHERE shard = ?
`

func (q *Queries) GetShardPublicIP(ctx context.Context, shard int64) (string, error) {
	row := q.queryRow(ctx, q.getShardPublicIPStmt, getShardPublicIP, shard)
	var public_ip string
	err := row.Scan(&public_ip)
	return public_ip, err
}

const listIPShards = `-- name: ListIPShards :many
SELECT shard, public_ip
FROM ip_shards
ORDER BY shard
`

type ListIPShardsRow struct {
	Shard    int64  `db:"shard" json:"shard"`
	PublicIp string `db:"public_ip" json:"public_ip"`
}

func (q *Queries) ListIPShards(ctx context.Context) ([]ListIPShardsRow, error) {
	rows, err := q.query(ctx, q.listIPShardsStmt, listIPShards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIPShardsRow{}
	for rows.Next() {
		var i ListIPShardsRow
		if err := rows.Scan(&i.Shard, &i.PublicIp); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertIPShard = `-- name: UpsertIPShard :exec
INSERT INTO ip_shards (shard, public_ip, updated_at)
VALUES (?, ?, CURRENT_TIMESTAMP)
ON CONFLICT (shard) DO UPDATE SET
    public_ip = excluded.public_ip,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertIPShardParams struct {
	Shard    int64  `db:"shard" json:"shard"`
	PublicIp string `db:"public_ip" json:"public_ip"`
}

func (q *Queries) UpsertIPShard(ctx context.Context, arg UpsertIPShardParams) error {
	_, err := q.exec(ctx, q.upsertIPShardStmt, upsertIPShard, arg.Shard, arg.PublicIp)
	return err
}
