// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mobile_pending_vm.sql

package exedb

import (
	"context"
)

const deleteMobilePendingVMByToken = `-- name: DeleteMobilePendingVMByToken :exec
DELETE FROM mobile_pending_vm WHERE token = ?
`

func (q *Queries) DeleteMobilePendingVMByToken(ctx context.Context, token string) error {
	_, err := q.exec(ctx, q.deleteMobilePendingVMByTokenStmt, deleteMobilePendingVMByToken, token)
	return err
}

const deleteMobilePendingVMByUserAndHostname = `-- name: DeleteMobilePendingVMByUserAndHostname :exec
DELETE FROM mobile_pending_vm WHERE user_id = ? AND hostname = ?
`

type DeleteMobilePendingVMByUserAndHostnameParams struct {
	UserID   string `db:"user_id" json:"user_id"`
	Hostname string `db:"hostname" json:"hostname"`
}

func (q *Queries) DeleteMobilePendingVMByUserAndHostname(ctx context.Context, arg DeleteMobilePendingVMByUserAndHostnameParams) error {
	_, err := q.exec(ctx, q.deleteMobilePendingVMByUserAndHostnameStmt, deleteMobilePendingVMByUserAndHostname, arg.UserID, arg.Hostname)
	return err
}

const getLatestMobilePendingVMByUser = `-- name: GetLatestMobilePendingVMByUser :one
SELECT hostname, prompt FROM mobile_pending_vm WHERE user_id = ? ORDER BY created_at DESC LIMIT 1
`

type GetLatestMobilePendingVMByUserRow struct {
	Hostname string  `db:"hostname" json:"hostname"`
	Prompt   *string `db:"prompt" json:"prompt"`
}

func (q *Queries) GetLatestMobilePendingVMByUser(ctx context.Context, userID string) (GetLatestMobilePendingVMByUserRow, error) {
	row := q.queryRow(ctx, q.getLatestMobilePendingVMByUserStmt, getLatestMobilePendingVMByUser, userID)
	var i GetLatestMobilePendingVMByUserRow
	err := row.Scan(&i.Hostname, &i.Prompt)
	return i, err
}

const getMobilePendingVMByToken = `-- name: GetMobilePendingVMByToken :one
SELECT hostname, prompt FROM mobile_pending_vm WHERE token = ?
`

type GetMobilePendingVMByTokenRow struct {
	Hostname string  `db:"hostname" json:"hostname"`
	Prompt   *string `db:"prompt" json:"prompt"`
}

func (q *Queries) GetMobilePendingVMByToken(ctx context.Context, token string) (GetMobilePendingVMByTokenRow, error) {
	row := q.queryRow(ctx, q.getMobilePendingVMByTokenStmt, getMobilePendingVMByToken, token)
	var i GetMobilePendingVMByTokenRow
	err := row.Scan(&i.Hostname, &i.Prompt)
	return i, err
}

const upsertMobilePendingVM = `-- name: UpsertMobilePendingVM :exec
INSERT OR REPLACE INTO mobile_pending_vm (token, user_id, hostname, prompt) VALUES (?, ?, ?, ?)
`

type UpsertMobilePendingVMParams struct {
	Token    string  `db:"token" json:"token"`
	UserID   string  `db:"user_id" json:"user_id"`
	Hostname string  `db:"hostname" json:"hostname"`
	Prompt   *string `db:"prompt" json:"prompt"`
}

func (q *Queries) UpsertMobilePendingVM(ctx context.Context, arg UpsertMobilePendingVMParams) error {
	_, err := q.exec(ctx, q.upsertMobilePendingVMStmt, upsertMobilePendingVM,
		arg.Token,
		arg.UserID,
		arg.Hostname,
		arg.Prompt,
	)
	return err
}
