// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package exedb

import (
	"time"
)

type Alloc struct {
	AllocID   string     `db:"alloc_id" json:"alloc_id"`
	UserID    string     `db:"user_id" json:"user_id"`
	AllocType string     `db:"alloc_type" json:"alloc_type"`
	Region    string     `db:"region" json:"region"`
	Ctrhost   string     `db:"ctrhost" json:"ctrhost"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
}

type AuthCookie struct {
	CookieValue string     `db:"cookie_value" json:"cookie_value"`
	UserID      string     `db:"user_id" json:"user_id"`
	Domain      string     `db:"domain" json:"domain"`
	ExpiresAt   time.Time  `db:"expires_at" json:"expires_at"`
	CreatedAt   *time.Time `db:"created_at" json:"created_at"`
	LastUsedAt  *time.Time `db:"last_used_at" json:"last_used_at"`
}

type AuthToken struct {
	Token       string     `db:"token" json:"token"`
	UserID      string     `db:"user_id" json:"user_id"`
	MachineName *string    `db:"machine_name" json:"machine_name"`
	ExpiresAt   time.Time  `db:"expires_at" json:"expires_at"`
	UsedAt      *time.Time `db:"used_at" json:"used_at"`
	CreatedAt   *time.Time `db:"created_at" json:"created_at"`
}

type Box struct {
	ID                   int        `db:"id" json:"id"`
	AllocID              string     `db:"alloc_id" json:"alloc_id"`
	Name                 string     `db:"name" json:"name"`
	Status               string     `db:"status" json:"status"`
	Image                string     `db:"image" json:"image"`
	ContainerID          *string    `db:"container_id" json:"container_id"`
	CreatedByUserID      string     `db:"created_by_user_id" json:"created_by_user_id"`
	CreatedAt            *time.Time `db:"created_at" json:"created_at"`
	UpdatedAt            *time.Time `db:"updated_at" json:"updated_at"`
	LastStartedAt        *time.Time `db:"last_started_at" json:"last_started_at"`
	Routes               *string    `db:"routes" json:"routes"`
	SSHServerIdentityKey []byte     `db:"ssh_server_identity_key" json:"ssh_server_identity_key"`
	SSHAuthorizedKeys    *string    `db:"ssh_authorized_keys" json:"ssh_authorized_keys"`
	SSHClientPrivateKey  []byte     `db:"ssh_client_private_key" json:"ssh_client_private_key"`
	SSHPort              *int64     `db:"ssh_port" json:"ssh_port"`
	SSHUser              *string    `db:"ssh_user" json:"ssh_user"`
	CreationLog          *string    `db:"creation_log" json:"creation_log"`
}

type BoxShare struct {
	ID               int64      `db:"id" json:"id"`
	BoxID            int64      `db:"box_id" json:"box_id"`
	SharedWithUserID string     `db:"shared_with_user_id" json:"shared_with_user_id"`
	SharedByUserID   string     `db:"shared_by_user_id" json:"shared_by_user_id"`
	Message          *string    `db:"message" json:"message"`
	CreatedAt        *time.Time `db:"created_at" json:"created_at"`
}

type BoxShareLink struct {
	ID              int64      `db:"id" json:"id"`
	BoxID           int64      `db:"box_id" json:"box_id"`
	ShareToken      string     `db:"share_token" json:"share_token"`
	CreatedByUserID string     `db:"created_by_user_id" json:"created_by_user_id"`
	CreatedAt       *time.Time `db:"created_at" json:"created_at"`
	LastUsedAt      *time.Time `db:"last_used_at" json:"last_used_at"`
	UseCount        *int64     `db:"use_count" json:"use_count"`
}

type DeletedBox struct {
	ID        int64   `db:"id" json:"id"`
	AllocID   string  `db:"alloc_id" json:"alloc_id"`
	DeletedAt *string `db:"deleted_at" json:"deleted_at"`
}

type EmailVerification struct {
	Token            string     `db:"token" json:"token"`
	Email            string     `db:"email" json:"email"`
	UserID           string     `db:"user_id" json:"user_id"`
	ExpiresAt        time.Time  `db:"expires_at" json:"expires_at"`
	CreatedAt        *time.Time `db:"created_at" json:"created_at"`
	VerificationCode *string    `db:"verification_code" json:"verification_code"`
}

type Migration struct {
	MigrationNumber int64      `db:"migration_number" json:"migration_number"`
	MigrationName   string     `db:"migration_name" json:"migration_name"`
	ExecutedAt      *time.Time `db:"executed_at" json:"executed_at"`
}

type MobilePendingVm struct {
	Token     string     `db:"token" json:"token"`
	UserID    string     `db:"user_id" json:"user_id"`
	Hostname  string     `db:"hostname" json:"hostname"`
	Prompt    *string    `db:"prompt" json:"prompt"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
}

type PendingBoxShare struct {
	ID              int64      `db:"id" json:"id"`
	BoxID           int64      `db:"box_id" json:"box_id"`
	SharedWithEmail string     `db:"shared_with_email" json:"shared_with_email"`
	SharedByUserID  string     `db:"shared_by_user_id" json:"shared_by_user_id"`
	Message         *string    `db:"message" json:"message"`
	CreatedAt       *time.Time `db:"created_at" json:"created_at"`
}

type PendingSSHKey struct {
	Token     string     `db:"token" json:"token"`
	PublicKey string     `db:"public_key" json:"public_key"`
	UserEmail string     `db:"user_email" json:"user_email"`
	ExpiresAt time.Time  `db:"expires_at" json:"expires_at"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
}

type ServerMetum struct {
	Key       string     `db:"key" json:"key"`
	Value     string     `db:"value" json:"value"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
	UpdatedAt *time.Time `db:"updated_at" json:"updated_at"`
}

type SshHostKey struct {
	ID          int64      `db:"id" json:"id"`
	PrivateKey  string     `db:"private_key" json:"private_key"`
	PublicKey   string     `db:"public_key" json:"public_key"`
	Fingerprint string     `db:"fingerprint" json:"fingerprint"`
	CreatedAt   *time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   *time.Time `db:"updated_at" json:"updated_at"`
}

type SshKey struct {
	ID         int64      `db:"id" json:"id"`
	UserID     string     `db:"user_id" json:"user_id"`
	PublicKey  string     `db:"public_key" json:"public_key"`
	AddedAt    *time.Time `db:"added_at" json:"added_at"`
	LastUsedAt *time.Time `db:"last_used_at" json:"last_used_at"`
}

type TagResolution struct {
	Registry          string  `db:"registry" json:"registry"`
	Repository        string  `db:"repository" json:"repository"`
	Tag               string  `db:"tag" json:"tag"`
	IndexDigest       *string `db:"index_digest" json:"index_digest"`
	PlatformDigest    *string `db:"platform_digest" json:"platform_digest"`
	Platform          string  `db:"platform" json:"platform"`
	LastCheckedAt     int64   `db:"last_checked_at" json:"last_checked_at"`
	LastChangedAt     int64   `db:"last_changed_at" json:"last_changed_at"`
	TtlSeconds        int64   `db:"ttl_seconds" json:"ttl_seconds"`
	SeenOnHosts       *int64  `db:"seen_on_hosts" json:"seen_on_hosts"`
	ImageSize         *int64  `db:"image_size" json:"image_size"`
	CreatedAt         int64   `db:"created_at" json:"created_at"`
	UpdatedAt         int64   `db:"updated_at" json:"updated_at"`
	ImageUser         *string `db:"image_user" json:"image_user"`
	ImageEntrypoint   *string `db:"image_entrypoint" json:"image_entrypoint"`
	ImageCmd          *string `db:"image_cmd" json:"image_cmd"`
	ImageLoginUser    *string `db:"image_login_user" json:"image_login_user"`
	ImageLabels       *string `db:"image_labels" json:"image_labels"`
	ImageExposedPorts *string `db:"image_exposed_ports" json:"image_exposed_ports"`
}

type TagResolutionHistory struct {
	ID         int64   `db:"id" json:"id"`
	Registry   string  `db:"registry" json:"registry"`
	Repository string  `db:"repository" json:"repository"`
	Tag        string  `db:"tag" json:"tag"`
	Platform   string  `db:"platform" json:"platform"`
	OldDigest  *string `db:"old_digest" json:"old_digest"`
	NewDigest  string  `db:"new_digest" json:"new_digest"`
	ChangedAt  int64   `db:"changed_at" json:"changed_at"`
}

type User struct {
	UserID    string     `db:"user_id" json:"user_id"`
	Email     string     `db:"email" json:"email"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
}

type UserDailyEmailCount struct {
	UserID     string `db:"user_id" json:"user_id"`
	Date       string `db:"date" json:"date"`
	EmailCount int64  `db:"email_count" json:"email_count"`
}

type UserEvent struct {
	UserID          string     `db:"user_id" json:"user_id"`
	Event           string     `db:"event" json:"event"`
	Count           int64      `db:"count" json:"count"`
	FirstOccurredAt *time.Time `db:"first_occurred_at" json:"first_occurred_at"`
	LastOccurredAt  *time.Time `db:"last_occurred_at" json:"last_occurred_at"`
}

type Waitlist struct {
	ID        int64      `db:"id" json:"id"`
	Email     string     `db:"email" json:"email"`
	RemoteIp  *string    `db:"remote_ip" json:"remote_ip"`
	Json      *string    `db:"json" json:"json"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
}
