// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package exedb

import (
	"time"
)

type AWSIPShard struct {
	Shard     int64     `db:"shard" json:"shard"`
	PublicIP  string    `db:"public_ip" json:"public_ip"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type Account struct {
	ID        string    `db:"id" json:"id"`
	CreatedBy string    `db:"created_by" json:"created_by"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type AccountCreditLedger struct {
	ID            int64     `db:"id" json:"id"`
	AccountID     string    `db:"account_id" json:"account_id"`
	Amount        int64     `db:"amount" json:"amount"`
	StripeEventID *string   `db:"stripe_event_id" json:"stripe_event_id"`
	CreatedAt     time.Time `db:"created_at" json:"created_at"`
}

type AuthCookie struct {
	CookieValue string     `db:"cookie_value" json:"cookie_value"`
	UserID      string     `db:"user_id" json:"user_id"`
	Domain      string     `db:"domain" json:"domain"`
	ExpiresAt   time.Time  `db:"expires_at" json:"expires_at"`
	CreatedAt   *time.Time `db:"created_at" json:"created_at"`
	LastUsedAt  *time.Time `db:"last_used_at" json:"last_used_at"`
}

type AuthToken struct {
	Token       string     `db:"token" json:"token"`
	UserID      string     `db:"user_id" json:"user_id"`
	MachineName *string    `db:"machine_name" json:"machine_name"`
	ExpiresAt   time.Time  `db:"expires_at" json:"expires_at"`
	UsedAt      *time.Time `db:"used_at" json:"used_at"`
	CreatedAt   *time.Time `db:"created_at" json:"created_at"`
}

type BillingEvent struct {
	ID        int64     `db:"id" json:"id"`
	AccountID string    `db:"account_id" json:"account_id"`
	EventType string    `db:"event_type" json:"event_type"`
	EventAt   time.Time `db:"event_at" json:"event_at"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type Box struct {
	ID                   int        `db:"id" json:"id"`
	Name                 string     `db:"name" json:"name"`
	Status               string     `db:"status" json:"status"`
	Image                string     `db:"image" json:"image"`
	Ctrhost              string     `db:"ctrhost" json:"ctrhost"`
	ContainerID          *string    `db:"container_id" json:"container_id"`
	CreatedByUserID      string     `db:"created_by_user_id" json:"created_by_user_id"`
	CreatedAt            *time.Time `db:"created_at" json:"created_at"`
	UpdatedAt            *time.Time `db:"updated_at" json:"updated_at"`
	LastStartedAt        *time.Time `db:"last_started_at" json:"last_started_at"`
	Routes               *string    `db:"routes" json:"routes"`
	SSHServerIdentityKey []byte     `db:"ssh_server_identity_key" json:"ssh_server_identity_key"`
	SSHAuthorizedKeys    *string    `db:"ssh_authorized_keys" json:"ssh_authorized_keys"`
	SSHClientPrivateKey  []byte     `db:"ssh_client_private_key" json:"ssh_client_private_key"`
	SSHPort              *int64     `db:"ssh_port" json:"ssh_port"`
	SSHUser              *string    `db:"ssh_user" json:"ssh_user"`
	CreationLog          *string    `db:"creation_log" json:"creation_log"`
	SupportAccessAllowed int64      `db:"support_access_allowed" json:"support_access_allowed"`
	Region               string     `db:"region" json:"region"`
	EmailReceiveEnabled  int64      `db:"email_receive_enabled" json:"email_receive_enabled"`
	EmailMaildirPath     string     `db:"email_maildir_path" json:"email_maildir_path"`
}

type BoxEmailCredit struct {
	BoxID           int64      `db:"box_id" json:"box_id"`
	AvailableCredit float64    `db:"available_credit" json:"available_credit"`
	LastRefreshAt   time.Time  `db:"last_refresh_at" json:"last_refresh_at"`
	TotalSent       int64      `db:"total_sent" json:"total_sent"`
	CreatedAt       *time.Time `db:"created_at" json:"created_at"`
}

type BoxIPShard struct {
	BoxID   int    `db:"box_id" json:"box_id"`
	UserID  string `db:"user_id" json:"user_id"`
	IPShard int64  `db:"ip_shard" json:"ip_shard"`
}

type BoxShare struct {
	ID               int64      `db:"id" json:"id"`
	BoxID            int64      `db:"box_id" json:"box_id"`
	SharedWithUserID string     `db:"shared_with_user_id" json:"shared_with_user_id"`
	SharedByUserID   string     `db:"shared_by_user_id" json:"shared_by_user_id"`
	Message          *string    `db:"message" json:"message"`
	CreatedAt        *time.Time `db:"created_at" json:"created_at"`
}

type BoxShareLink struct {
	ID              int64      `db:"id" json:"id"`
	BoxID           int64      `db:"box_id" json:"box_id"`
	ShareToken      string     `db:"share_token" json:"share_token"`
	CreatedByUserID string     `db:"created_by_user_id" json:"created_by_user_id"`
	CreatedAt       *time.Time `db:"created_at" json:"created_at"`
	LastUsedAt      *time.Time `db:"last_used_at" json:"last_used_at"`
	UseCount        *int64     `db:"use_count" json:"use_count"`
}

type DeletedBox struct {
	ID        int64      `db:"id" json:"id"`
	UserID    string     `db:"user_id" json:"user_id"`
	DeletedAt *time.Time `db:"deleted_at" json:"deleted_at"`
}

type EmailAddressQuality struct {
	ID           int64      `db:"id" json:"id"`
	Email        string     `db:"email" json:"email"`
	QueriedAt    *time.Time `db:"queried_at" json:"queried_at"`
	ResponseJson string     `db:"response_json" json:"response_json"`
	Disposable   *int64     `db:"disposable" json:"disposable"`
}

type EmailBounce struct {
	Email     string     `db:"email" json:"email"`
	Reason    string     `db:"reason" json:"reason"`
	BouncedAt *time.Time `db:"bounced_at" json:"bounced_at"`
}

type EmailQualityBypass struct {
	Email   string     `db:"email" json:"email"`
	Reason  string     `db:"reason" json:"reason"`
	AddedAt *time.Time `db:"added_at" json:"added_at"`
	AddedBy string     `db:"added_by" json:"added_by"`
}

type EmailVerification struct {
	Token            string     `db:"token" json:"token"`
	Email            string     `db:"email" json:"email"`
	UserID           string     `db:"user_id" json:"user_id"`
	ExpiresAt        time.Time  `db:"expires_at" json:"expires_at"`
	CreatedAt        *time.Time `db:"created_at" json:"created_at"`
	VerificationCode *string    `db:"verification_code" json:"verification_code"`
	InviteCodeID     *int64     `db:"invite_code_id" json:"invite_code_id"`
	IsNewUser        bool       `db:"is_new_user" json:"is_new_user"`
	RedirectUrl      *string    `db:"redirect_url" json:"redirect_url"`
	ReturnHost       *string    `db:"return_host" json:"return_host"`
}

type HllSketch struct {
	Key       string     `db:"key" json:"key"`
	Data      []byte     `db:"data" json:"data"`
	UpdatedAt *time.Time `db:"updated_at" json:"updated_at"`
}

type IPShard struct {
	Shard     int64     `db:"shard" json:"shard"`
	PublicIP  string    `db:"public_ip" json:"public_ip"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type InviteCode struct {
	ID               int64      `db:"id" json:"id"`
	Code             string     `db:"code" json:"code"`
	PlanType         string     `db:"plan_type" json:"plan_type"`
	AssignedToUserID *string    `db:"assigned_to_user_id" json:"assigned_to_user_id"`
	AssignedAt       *time.Time `db:"assigned_at" json:"assigned_at"`
	AssignedBy       string     `db:"assigned_by" json:"assigned_by"`
	AssignedFor      *string    `db:"assigned_for" json:"assigned_for"`
	UsedByUserID     *string    `db:"used_by_user_id" json:"used_by_user_id"`
	UsedAt           *time.Time `db:"used_at" json:"used_at"`
	AllocatedAt      *time.Time `db:"allocated_at" json:"allocated_at"`
}

type InviteCodePool struct {
	Code      string     `db:"code" json:"code"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
}

type LatitudeIPShard struct {
	Shard     int64     `db:"shard" json:"shard"`
	PublicIP  string    `db:"public_ip" json:"public_ip"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type Migration struct {
	MigrationNumber int64      `db:"migration_number" json:"migration_number"`
	MigrationName   string     `db:"migration_name" json:"migration_name"`
	ExecutedAt      *time.Time `db:"executed_at" json:"executed_at"`
}

type MobilePendingVm struct {
	Token     string     `db:"token" json:"token"`
	UserID    string     `db:"user_id" json:"user_id"`
	Hostname  string     `db:"hostname" json:"hostname"`
	Prompt    *string    `db:"prompt" json:"prompt"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
}

type Passkey struct {
	ID           int64      `db:"id" json:"id"`
	UserID       string     `db:"user_id" json:"user_id"`
	CredentialID []byte     `db:"credential_id" json:"credential_id"`
	PublicKey    []byte     `db:"public_key" json:"public_key"`
	SignCount    int64      `db:"sign_count" json:"sign_count"`
	Aaguid       []byte     `db:"aaguid" json:"aaguid"`
	Name         string     `db:"name" json:"name"`
	Flags        int64      `db:"flags" json:"flags"`
	CreatedAt    *time.Time `db:"created_at" json:"created_at"`
	LastUsedAt   *time.Time `db:"last_used_at" json:"last_used_at"`
}

type PasskeyChallenge struct {
	Challenge   string     `db:"challenge" json:"challenge"`
	SessionData []byte     `db:"session_data" json:"session_data"`
	UserID      *string    `db:"user_id" json:"user_id"`
	ExpiresAt   time.Time  `db:"expires_at" json:"expires_at"`
	CreatedAt   *time.Time `db:"created_at" json:"created_at"`
}

type PendingBoxShare struct {
	ID              int64      `db:"id" json:"id"`
	BoxID           int64      `db:"box_id" json:"box_id"`
	SharedWithEmail string     `db:"shared_with_email" json:"shared_with_email"`
	SharedByUserID  string     `db:"shared_by_user_id" json:"shared_by_user_id"`
	Message         *string    `db:"message" json:"message"`
	CreatedAt       *time.Time `db:"created_at" json:"created_at"`
}

type PendingRegistration struct {
	Token        string    `db:"token" json:"token"`
	Email        string    `db:"email" json:"email"`
	InviteCodeID *int64    `db:"invite_code_id" json:"invite_code_id"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
	ExpiresAt    time.Time `db:"expires_at" json:"expires_at"`
}

type PendingSSHKey struct {
	Token     string     `db:"token" json:"token"`
	PublicKey string     `db:"public_key" json:"public_key"`
	UserEmail string     `db:"user_email" json:"user_email"`
	ExpiresAt time.Time  `db:"expires_at" json:"expires_at"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
}

type SSHKey struct {
	ID          int64      `db:"id" json:"id"`
	UserID      string     `db:"user_id" json:"user_id"`
	PublicKey   string     `db:"public_key" json:"public_key"`
	AddedAt     *time.Time `db:"added_at" json:"added_at"`
	LastUsedAt  *time.Time `db:"last_used_at" json:"last_used_at"`
	Comment     string     `db:"comment" json:"comment"`
	Fingerprint string     `db:"fingerprint" json:"fingerprint"`
}

type ServerMetum struct {
	Key       string     `db:"key" json:"key"`
	Value     string     `db:"value" json:"value"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
	UpdatedAt *time.Time `db:"updated_at" json:"updated_at"`
}

type ShellHistory struct {
	ID        int64      `db:"id" json:"id"`
	UserID    string     `db:"user_id" json:"user_id"`
	Command   string     `db:"command" json:"command"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
}

type SignupRejection struct {
	ID               int64      `db:"id" json:"id"`
	Email            string     `db:"email" json:"email"`
	Ip               string     `db:"ip" json:"ip"`
	Reason           string     `db:"reason" json:"reason"`
	Source           string     `db:"source" json:"source"`
	RejectedAt       *time.Time `db:"rejected_at" json:"rejected_at"`
	IpqsResponseJson *string    `db:"ipqs_response_json" json:"ipqs_response_json"`
}

type SshHostKey struct {
	ID          int64      `db:"id" json:"id"`
	PrivateKey  string     `db:"private_key" json:"private_key"`
	PublicKey   string     `db:"public_key" json:"public_key"`
	Fingerprint string     `db:"fingerprint" json:"fingerprint"`
	CreatedAt   *time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   *time.Time `db:"updated_at" json:"updated_at"`
	CertSig     *string    `db:"cert_sig" json:"cert_sig"`
}

type TagResolution struct {
	Registry       string  `db:"registry" json:"registry"`
	Repository     string  `db:"repository" json:"repository"`
	Tag            string  `db:"tag" json:"tag"`
	IndexDigest    *string `db:"index_digest" json:"index_digest"`
	PlatformDigest *string `db:"platform_digest" json:"platform_digest"`
	Platform       string  `db:"platform" json:"platform"`
	LastCheckedAt  int64   `db:"last_checked_at" json:"last_checked_at"`
	LastChangedAt  int64   `db:"last_changed_at" json:"last_changed_at"`
	TtlSeconds     int64   `db:"ttl_seconds" json:"ttl_seconds"`
	SeenOnHosts    *int64  `db:"seen_on_hosts" json:"seen_on_hosts"`
	ImageSize      *int64  `db:"image_size" json:"image_size"`
	CreatedAt      int64   `db:"created_at" json:"created_at"`
	UpdatedAt      int64   `db:"updated_at" json:"updated_at"`
}

type TagResolutionHistory struct {
	ID         int64   `db:"id" json:"id"`
	Registry   string  `db:"registry" json:"registry"`
	Repository string  `db:"repository" json:"repository"`
	Tag        string  `db:"tag" json:"tag"`
	Platform   string  `db:"platform" json:"platform"`
	OldDigest  *string `db:"old_digest" json:"old_digest"`
	NewDigest  string  `db:"new_digest" json:"new_digest"`
	ChangedAt  int64   `db:"changed_at" json:"changed_at"`
}

type User struct {
	UserID                 string     `db:"user_id" json:"user_id"`
	Email                  string     `db:"email" json:"email"`
	CreatedAt              *time.Time `db:"created_at" json:"created_at"`
	RootSupport            int64      `db:"root_support" json:"root_support"`
	CreatedForLoginWithExe bool       `db:"created_for_login_with_exe" json:"created_for_login_with_exe"`
	NewVmCreationDisabled  bool       `db:"new_vm_creation_disabled" json:"new_vm_creation_disabled"`
	DiscordID              *string    `db:"discord_id" json:"discord_id"`
	DiscordUsername        *string    `db:"discord_username" json:"discord_username"`
	BillingExemption       *string    `db:"billing_exemption" json:"billing_exemption"`
	BillingTrialEndsAt     *time.Time `db:"billing_trial_ends_at" json:"billing_trial_ends_at"`
	SignedUpWithInviteID   *int64     `db:"signed_up_with_invite_id" json:"signed_up_with_invite_id"`
	NextSSHKeyNumber       int64      `db:"next_ssh_key_number" json:"next_ssh_key_number"`
	Region                 string     `db:"region" json:"region"`
	CanonicalEmail         *string    `db:"canonical_email" json:"canonical_email"`
	IsLockedOut            bool       `db:"is_locked_out" json:"is_locked_out"`
	Limits                 *string    `db:"limits" json:"limits"`
}

type UserDailyEmailCount struct {
	UserID     string `db:"user_id" json:"user_id"`
	Date       string `db:"date" json:"date"`
	EmailCount int64  `db:"email_count" json:"email_count"`
}

type UserDefault struct {
	UserID     string     `db:"user_id" json:"user_id"`
	NewVMEmail *int64     `db:"new_vm_email" json:"new_vm_email"`
	CreatedAt  *time.Time `db:"created_at" json:"created_at"`
	UpdatedAt  *time.Time `db:"updated_at" json:"updated_at"`
}

type UserEvent struct {
	UserID          string     `db:"user_id" json:"user_id"`
	Event           string     `db:"event" json:"event"`
	Count           int64      `db:"count" json:"count"`
	FirstOccurredAt *time.Time `db:"first_occurred_at" json:"first_occurred_at"`
	LastOccurredAt  *time.Time `db:"last_occurred_at" json:"last_occurred_at"`
}

type UserLlmCredit struct {
	UserID          string     `db:"user_id" json:"user_id"`
	AvailableCredit float64    `db:"available_credit" json:"available_credit"`
	MaxCredit       *float64   `db:"max_credit" json:"max_credit"`
	RefreshPerHour  *float64   `db:"refresh_per_hour" json:"refresh_per_hour"`
	TotalUsed       float64    `db:"total_used" json:"total_used"`
	LastRefreshAt   time.Time  `db:"last_refresh_at" json:"last_refresh_at"`
	CreatedAt       *time.Time `db:"created_at" json:"created_at"`
	UpdatedAt       *time.Time `db:"updated_at" json:"updated_at"`
}

type Waitlist struct {
	ID        int64      `db:"id" json:"id"`
	Email     string     `db:"email" json:"email"`
	RemoteIp  *string    `db:"remote_ip" json:"remote_ip"`
	Json      *string    `db:"json" json:"json"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
}
