// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_states.sql

package exedb

import (
	"context"
	"time"
)

const cleanupExpiredOAuthStates = `-- name: CleanupExpiredOAuthStates :exec
DELETE FROM oauth_states WHERE expires_at < ?
`

func (q *Queries) CleanupExpiredOAuthStates(ctx context.Context, expiresAt time.Time) error {
	_, err := q.exec(ctx, q.cleanupExpiredOAuthStatesStmt, cleanupExpiredOAuthStates, expiresAt)
	return err
}

const consumeOAuthState = `-- name: ConsumeOAuthState :one
DELETE FROM oauth_states WHERE state = ? AND expires_at > CURRENT_TIMESTAMP RETURNING state, provider, email, user_id, is_new_user, invite_code_id, team_invite_token, redirect_url, return_host, login_with_exe, ssh_verification_token, hostname, prompt, image, created_at, expires_at
`

func (q *Queries) ConsumeOAuthState(ctx context.Context, state string) (OauthState, error) {
	row := q.queryRow(ctx, q.consumeOAuthStateStmt, consumeOAuthState, state)
	var i OauthState
	err := row.Scan(
		&i.State,
		&i.Provider,
		&i.Email,
		&i.UserID,
		&i.IsNewUser,
		&i.InviteCodeID,
		&i.TeamInviteToken,
		&i.RedirectUrl,
		&i.ReturnHost,
		&i.LoginWithExe,
		&i.SshVerificationToken,
		&i.Hostname,
		&i.Prompt,
		&i.Image,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertOAuthState = `-- name: InsertOAuthState :exec
INSERT INTO oauth_states (state, provider, email, user_id, is_new_user, invite_code_id, team_invite_token, redirect_url, return_host, login_with_exe, ssh_verification_token, hostname, prompt, image, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertOAuthStateParams struct {
	State                string    `db:"state" json:"state"`
	Provider             string    `db:"provider" json:"provider"`
	Email                string    `db:"email" json:"email"`
	UserID               *string   `db:"user_id" json:"user_id"`
	IsNewUser            bool      `db:"is_new_user" json:"is_new_user"`
	InviteCodeID         *int64    `db:"invite_code_id" json:"invite_code_id"`
	TeamInviteToken      *string   `db:"team_invite_token" json:"team_invite_token"`
	RedirectUrl          *string   `db:"redirect_url" json:"redirect_url"`
	ReturnHost           *string   `db:"return_host" json:"return_host"`
	LoginWithExe         bool      `db:"login_with_exe" json:"login_with_exe"`
	SshVerificationToken *string   `db:"ssh_verification_token" json:"ssh_verification_token"`
	Hostname             *string   `db:"hostname" json:"hostname"`
	Prompt               *string   `db:"prompt" json:"prompt"`
	Image                *string   `db:"image" json:"image"`
	ExpiresAt            time.Time `db:"expires_at" json:"expires_at"`
}

func (q *Queries) InsertOAuthState(ctx context.Context, arg InsertOAuthStateParams) error {
	_, err := q.exec(ctx, q.insertOAuthStateStmt, insertOAuthState,
		arg.State,
		arg.Provider,
		arg.Email,
		arg.UserID,
		arg.IsNewUser,
		arg.InviteCodeID,
		arg.TeamInviteToken,
		arg.RedirectUrl,
		arg.ReturnHost,
		arg.LoginWithExe,
		arg.SshVerificationToken,
		arg.Hostname,
		arg.Prompt,
		arg.Image,
		arg.ExpiresAt,
	)
	return err
}
