// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pending_ssh_keys.sql

package exedb

import (
	"context"
	"time"
)

const deletePendingSSHKeyByToken = `-- name: DeletePendingSSHKeyByToken :exec
DELETE FROM pending_ssh_keys WHERE token = ?
`

func (q *Queries) DeletePendingSSHKeyByToken(ctx context.Context, token string) error {
	_, err := q.exec(ctx, q.deletePendingSSHKeyByTokenStmt, deletePendingSSHKeyByToken, token)
	return err
}

const getPendingSSHKeyByToken = `-- name: GetPendingSSHKeyByToken :one
SELECT token, public_key, user_email, expires_at, created_at
FROM pending_ssh_keys
WHERE token = ?
`

func (q *Queries) GetPendingSSHKeyByToken(ctx context.Context, token string) (PendingSSHKey, error) {
	row := q.queryRow(ctx, q.getPendingSSHKeyByTokenStmt, getPendingSSHKeyByToken, token)
	var i PendingSSHKey
	err := row.Scan(
		&i.Token,
		&i.PublicKey,
		&i.UserEmail,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingSSHKeyEmailByPublicKey = `-- name: GetPendingSSHKeyEmailByPublicKey :one
SELECT user_email FROM pending_ssh_keys WHERE public_key = ?
`

func (q *Queries) GetPendingSSHKeyEmailByPublicKey(ctx context.Context, publicKey string) (string, error) {
	row := q.queryRow(ctx, q.getPendingSSHKeyEmailByPublicKeyStmt, getPendingSSHKeyEmailByPublicKey, publicKey)
	var user_email string
	err := row.Scan(&user_email)
	return user_email, err
}

const insertPendingSSHKey = `-- name: InsertPendingSSHKey :exec
INSERT INTO pending_ssh_keys (token, public_key, user_email, expires_at)
VALUES (?, ?, ?, ?)
`

type InsertPendingSSHKeyParams struct {
	Token     string    `db:"token" json:"token"`
	PublicKey string    `db:"public_key" json:"public_key"`
	UserEmail string    `db:"user_email" json:"user_email"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
}

func (q *Queries) InsertPendingSSHKey(ctx context.Context, arg InsertPendingSSHKeyParams) error {
	_, err := q.exec(ctx, q.insertPendingSSHKeyStmt, insertPendingSSHKey,
		arg.Token,
		arg.PublicKey,
		arg.UserEmail,
		arg.ExpiresAt,
	)
	return err
}
