// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: released_box_names.sql

package exedb

import (
	"context"
)

const cleanupExpiredReleasedBoxNames = `-- name: CleanupExpiredReleasedBoxNames :exec
DELETE FROM released_box_names WHERE released_at <= datetime('now', '-24 hours')
`

func (q *Queries) CleanupExpiredReleasedBoxNames(ctx context.Context) error {
	_, err := q.exec(ctx, q.cleanupExpiredReleasedBoxNamesStmt, cleanupExpiredReleasedBoxNames)
	return err
}

const deleteReleasedBoxName = `-- name: DeleteReleasedBoxName :exec
DELETE FROM released_box_names WHERE name = ?
`

func (q *Queries) DeleteReleasedBoxName(ctx context.Context, name string) error {
	_, err := q.exec(ctx, q.deleteReleasedBoxNameStmt, deleteReleasedBoxName, name)
	return err
}

const getReleasedBoxName = `-- name: GetReleasedBoxName :one
SELECT name, box_id, user_id, released_at FROM released_box_names WHERE name = ? AND released_at > datetime('now', '-24 hours')
`

func (q *Queries) GetReleasedBoxName(ctx context.Context, name string) (ReleasedBoxName, error) {
	row := q.queryRow(ctx, q.getReleasedBoxNameStmt, getReleasedBoxName, name)
	var i ReleasedBoxName
	err := row.Scan(
		&i.Name,
		&i.BoxID,
		&i.UserID,
		&i.ReleasedAt,
	)
	return i, err
}

const insertReleasedBoxName = `-- name: InsertReleasedBoxName :exec
INSERT OR REPLACE INTO released_box_names (name, box_id, user_id, released_at) VALUES (?, ?, ?, CURRENT_TIMESTAMP)
`

type InsertReleasedBoxNameParams struct {
	Name   string `db:"name" json:"name"`
	BoxID  int64  `db:"box_id" json:"box_id"`
	UserID string `db:"user_id" json:"user_id"`
}

func (q *Queries) InsertReleasedBoxName(ctx context.Context, arg InsertReleasedBoxNameParams) error {
	_, err := q.exec(ctx, q.insertReleasedBoxNameStmt, insertReleasedBoxName, arg.Name, arg.BoxID, arg.UserID)
	return err
}
