// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: signup_ip_checks.sql

package exedb

import (
	"context"
)

const insertSignupIPCheck = `-- name: InsertSignupIPCheck :exec
INSERT INTO signup_ip_checks (email, ip, source, ipqs_response_json, error, flagged) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertSignupIPCheckParams struct {
	Email            string  `db:"email" json:"email"`
	Ip               string  `db:"ip" json:"ip"`
	Source           string  `db:"source" json:"source"`
	IpqsResponseJson *string `db:"ipqs_response_json" json:"ipqs_response_json"`
	Error            *string `db:"error" json:"error"`
	Flagged          int64   `db:"flagged" json:"flagged"`
}

func (q *Queries) InsertSignupIPCheck(ctx context.Context, arg InsertSignupIPCheckParams) error {
	_, err := q.exec(ctx, q.insertSignupIPCheckStmt, insertSignupIPCheck,
		arg.Email,
		arg.Ip,
		arg.Source,
		arg.IpqsResponseJson,
		arg.Error,
		arg.Flagged,
	)
	return err
}
