// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: signup_rejections.sql

package exedb

import (
	"context"
)

const getRecentSignupRejections = `-- name: GetRecentSignupRejections :many
SELECT id, email, ip, reason, source, rejected_at, ipqs_response_json FROM signup_rejections ORDER BY rejected_at DESC LIMIT ?
`

func (q *Queries) GetRecentSignupRejections(ctx context.Context, limit int64) ([]SignupRejection, error) {
	rows, err := q.query(ctx, q.getRecentSignupRejectionsStmt, getRecentSignupRejections, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SignupRejection{}
	for rows.Next() {
		var i SignupRejection
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Ip,
			&i.Reason,
			&i.Source,
			&i.RejectedAt,
			&i.IpqsResponseJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSignupRejection = `-- name: InsertSignupRejection :exec
INSERT INTO signup_rejections (email, ip, reason, source, ipqs_response_json) VALUES (?, ?, ?, ?, ?)
`

type InsertSignupRejectionParams struct {
	Email            string  `db:"email" json:"email"`
	Ip               string  `db:"ip" json:"ip"`
	Reason           string  `db:"reason" json:"reason"`
	Source           string  `db:"source" json:"source"`
	IpqsResponseJson *string `db:"ipqs_response_json" json:"ipqs_response_json"`
}

func (q *Queries) InsertSignupRejection(ctx context.Context, arg InsertSignupRejectionParams) error {
	_, err := q.exec(ctx, q.insertSignupRejectionStmt, insertSignupRejection,
		arg.Email,
		arg.Ip,
		arg.Reason,
		arg.Source,
		arg.IpqsResponseJson,
	)
	return err
}
