// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: signup_rejections.sql

package exedb

import (
	"context"
)

const getSignupRejectionsByEmail = `-- name: GetSignupRejectionsByEmail :many
SELECT id, email, ip, reason, source, rejected_at FROM signup_rejections WHERE email = ? ORDER BY rejected_at DESC
`

func (q *Queries) GetSignupRejectionsByEmail(ctx context.Context, email string) ([]SignupRejection, error) {
	rows, err := q.query(ctx, q.getSignupRejectionsByEmailStmt, getSignupRejectionsByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SignupRejection{}
	for rows.Next() {
		var i SignupRejection
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Ip,
			&i.Reason,
			&i.Source,
			&i.RejectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSignupRejectionsByIP = `-- name: GetSignupRejectionsByIP :many
SELECT id, email, ip, reason, source, rejected_at FROM signup_rejections WHERE ip = ? ORDER BY rejected_at DESC
`

func (q *Queries) GetSignupRejectionsByIP(ctx context.Context, ip string) ([]SignupRejection, error) {
	rows, err := q.query(ctx, q.getSignupRejectionsByIPStmt, getSignupRejectionsByIP, ip)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SignupRejection{}
	for rows.Next() {
		var i SignupRejection
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Ip,
			&i.Reason,
			&i.Source,
			&i.RejectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSignupRejection = `-- name: InsertSignupRejection :exec
INSERT INTO signup_rejections (email, ip, reason, source) VALUES (?, ?, ?, ?)
`

type InsertSignupRejectionParams struct {
	Email  string `db:"email" json:"email"`
	Ip     string `db:"ip" json:"ip"`
	Reason string `db:"reason" json:"reason"`
	Source string `db:"source" json:"source"`
}

func (q *Queries) InsertSignupRejection(ctx context.Context, arg InsertSignupRejectionParams) error {
	_, err := q.exec(ctx, q.insertSignupRejectionStmt, insertSignupRejection,
		arg.Email,
		arg.Ip,
		arg.Reason,
		arg.Source,
	)
	return err
}
