// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: signup_ip_checks.sql

package exedb

import (
	"context"
)

const getSignupIPChecksByEmail = `-- name: GetSignupIPChecksByEmail :many
SELECT id, email, ip, source, ipqs_response_json, flagged, checked_at FROM signup_ip_checks WHERE email = ? ORDER BY checked_at DESC
`

func (q *Queries) GetSignupIPChecksByEmail(ctx context.Context, email string) ([]SignupIPCheck, error) {
	rows, err := q.query(ctx, q.getSignupIPChecksByEmailStmt, getSignupIPChecksByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SignupIPCheck{}
	for rows.Next() {
		var i SignupIPCheck
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Ip,
			&i.Source,
			&i.IpqsResponseJson,
			&i.Flagged,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSignupIPChecksByIP = `-- name: GetSignupIPChecksByIP :many
SELECT id, email, ip, source, ipqs_response_json, flagged, checked_at FROM signup_ip_checks WHERE ip = ? ORDER BY checked_at DESC
`

func (q *Queries) GetSignupIPChecksByIP(ctx context.Context, ip string) ([]SignupIPCheck, error) {
	rows, err := q.query(ctx, q.getSignupIPChecksByIPStmt, getSignupIPChecksByIP, ip)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SignupIPCheck{}
	for rows.Next() {
		var i SignupIPCheck
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Ip,
			&i.Source,
			&i.IpqsResponseJson,
			&i.Flagged,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSignupIPCheck = `-- name: InsertSignupIPCheck :exec
INSERT INTO signup_ip_checks (email, ip, source, ipqs_response_json, flagged) VALUES (?, ?, ?, ?, ?)
`

type InsertSignupIPCheckParams struct {
	Email            string  `db:"email" json:"email"`
	Ip               string  `db:"ip" json:"ip"`
	Source           string  `db:"source" json:"source"`
	IpqsResponseJson *string `db:"ipqs_response_json" json:"ipqs_response_json"`
	Flagged          int64   `db:"flagged" json:"flagged"`
}

func (q *Queries) InsertSignupIPCheck(ctx context.Context, arg InsertSignupIPCheckParams) error {
	_, err := q.exec(ctx, q.insertSignupIPCheckStmt, insertSignupIPCheck,
		arg.Email,
		arg.Ip,
		arg.Source,
		arg.IpqsResponseJson,
		arg.Flagged,
	)
	return err
}
