// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ssh_host_keys.sql

package exedb

import (
	"context"
)

const getSSHHostKey = `-- name: GetSSHHostKey :one
SELECT private_key, public_key FROM ssh_host_key WHERE id = 1
`

type GetSSHHostKeyRow struct {
	PrivateKey string `db:"private_key" json:"private_key"`
	PublicKey  string `db:"public_key" json:"public_key"`
}

func (q *Queries) GetSSHHostKey(ctx context.Context) (GetSSHHostKeyRow, error) {
	row := q.queryRow(ctx, q.getSSHHostKeyStmt, getSSHHostKey)
	var i GetSSHHostKeyRow
	err := row.Scan(&i.PrivateKey, &i.PublicKey)
	return i, err
}
