// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usage_debits.sql

package exedb

import (
	"context"
)

const getDebitBalanceForBillingAccount = `-- name: GetDebitBalanceForBillingAccount :one
SELECT COALESCE(SUM(cost_usd), 0.0)
FROM usage_debits
WHERE billing_account_id = ?
`

func (q *Queries) GetDebitBalanceForBillingAccount(ctx context.Context, billingAccountID string) (interface{}, error) {
	row := q.queryRow(ctx, q.getDebitBalanceForBillingAccountStmt, getDebitBalanceForBillingAccount, billingAccountID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getUsageDebit = `-- name: GetUsageDebit :one
SELECT id, billing_account_id, model, message_id, input_tokens, cache_creation_input_tokens, cache_read_input_tokens, output_tokens, cost_usd, created_at
FROM usage_debits
WHERE id = ?
`

func (q *Queries) GetUsageDebit(ctx context.Context, id int64) (UsageDebit, error) {
	row := q.queryRow(ctx, q.getUsageDebitStmt, getUsageDebit, id)
	var i UsageDebit
	err := row.Scan(
		&i.ID,
		&i.BillingAccountID,
		&i.Model,
		&i.MessageID,
		&i.InputTokens,
		&i.CacheCreationInputTokens,
		&i.CacheReadInputTokens,
		&i.OutputTokens,
		&i.CostUsd,
		&i.CreatedAt,
	)
	return i, err
}

const getUsageDebitByMessageID = `-- name: GetUsageDebitByMessageID :one
SELECT id, billing_account_id, model, message_id, input_tokens, cache_creation_input_tokens, cache_read_input_tokens, output_tokens, cost_usd, created_at
FROM usage_debits
WHERE message_id = ?
`

func (q *Queries) GetUsageDebitByMessageID(ctx context.Context, messageID string) (UsageDebit, error) {
	row := q.queryRow(ctx, q.getUsageDebitByMessageIDStmt, getUsageDebitByMessageID, messageID)
	var i UsageDebit
	err := row.Scan(
		&i.ID,
		&i.BillingAccountID,
		&i.Model,
		&i.MessageID,
		&i.InputTokens,
		&i.CacheCreationInputTokens,
		&i.CacheReadInputTokens,
		&i.OutputTokens,
		&i.CostUsd,
		&i.CreatedAt,
	)
	return i, err
}

const getUsageDebitsByBillingAccount = `-- name: GetUsageDebitsByBillingAccount :many
SELECT id, billing_account_id, model, message_id, input_tokens, cache_creation_input_tokens, cache_read_input_tokens, output_tokens, cost_usd, created_at
FROM usage_debits
WHERE billing_account_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetUsageDebitsByBillingAccount(ctx context.Context, billingAccountID string) ([]UsageDebit, error) {
	rows, err := q.query(ctx, q.getUsageDebitsByBillingAccountStmt, getUsageDebitsByBillingAccount, billingAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageDebit{}
	for rows.Next() {
		var i UsageDebit
		if err := rows.Scan(
			&i.ID,
			&i.BillingAccountID,
			&i.Model,
			&i.MessageID,
			&i.InputTokens,
			&i.CacheCreationInputTokens,
			&i.CacheReadInputTokens,
			&i.OutputTokens,
			&i.CostUsd,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUsageDebit = `-- name: InsertUsageDebit :exec
INSERT INTO usage_debits (billing_account_id, model, message_id, input_tokens, cache_creation_input_tokens, cache_read_input_tokens, output_tokens, cost_usd)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertUsageDebitParams struct {
	BillingAccountID         string  `db:"billing_account_id" json:"billing_account_id"`
	Model                    string  `db:"model" json:"model"`
	MessageID                string  `db:"message_id" json:"message_id"`
	InputTokens              int64   `db:"input_tokens" json:"input_tokens"`
	CacheCreationInputTokens int64   `db:"cache_creation_input_tokens" json:"cache_creation_input_tokens"`
	CacheReadInputTokens     int64   `db:"cache_read_input_tokens" json:"cache_read_input_tokens"`
	OutputTokens             int64   `db:"output_tokens" json:"output_tokens"`
	CostUsd                  float64 `db:"cost_usd" json:"cost_usd"`
}

func (q *Queries) InsertUsageDebit(ctx context.Context, arg InsertUsageDebitParams) error {
	_, err := q.exec(ctx, q.insertUsageDebitStmt, insertUsageDebit,
		arg.BillingAccountID,
		arg.Model,
		arg.MessageID,
		arg.InputTokens,
		arg.CacheCreationInputTokens,
		arg.CacheReadInputTokens,
		arg.OutputTokens,
		arg.CostUsd,
	)
	return err
}
