// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usage_credits.sql

package exedb

import (
	"context"
)

const getCreditBalanceForBillingAccount = `-- name: GetCreditBalanceForBillingAccount :one
SELECT COALESCE(SUM(amount), 0.0)
FROM usage_credits
WHERE billing_account_id = ? AND status = 'completed'
`

func (q *Queries) GetCreditBalanceForBillingAccount(ctx context.Context, billingAccountID string) (interface{}, error) {
	row := q.queryRow(ctx, q.getCreditBalanceForBillingAccountStmt, getCreditBalanceForBillingAccount, billingAccountID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getUsageCredit = `-- name: GetUsageCredit :one
SELECT id, billing_account_id, amount, payment_method, payment_id, status, data, created_at
FROM usage_credits
WHERE id = ?
`

func (q *Queries) GetUsageCredit(ctx context.Context, id int64) (UsageCredit, error) {
	row := q.queryRow(ctx, q.getUsageCreditStmt, getUsageCredit, id)
	var i UsageCredit
	err := row.Scan(
		&i.ID,
		&i.BillingAccountID,
		&i.Amount,
		&i.PaymentMethod,
		&i.PaymentID,
		&i.Status,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const getUsageCreditsByBillingAccount = `-- name: GetUsageCreditsByBillingAccount :many
SELECT id, billing_account_id, amount, payment_method, payment_id, status, data, created_at
FROM usage_credits
WHERE billing_account_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetUsageCreditsByBillingAccount(ctx context.Context, billingAccountID string) ([]UsageCredit, error) {
	rows, err := q.query(ctx, q.getUsageCreditsByBillingAccountStmt, getUsageCreditsByBillingAccount, billingAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageCredit{}
	for rows.Next() {
		var i UsageCredit
		if err := rows.Scan(
			&i.ID,
			&i.BillingAccountID,
			&i.Amount,
			&i.PaymentMethod,
			&i.PaymentID,
			&i.Status,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUsageCredit = `-- name: InsertUsageCredit :exec
INSERT INTO usage_credits (billing_account_id, amount, payment_method, payment_id, status, data)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertUsageCreditParams struct {
	BillingAccountID string  `db:"billing_account_id" json:"billing_account_id"`
	Amount           float64 `db:"amount" json:"amount"`
	PaymentMethod    string  `db:"payment_method" json:"payment_method"`
	PaymentID        string  `db:"payment_id" json:"payment_id"`
	Status           string  `db:"status" json:"status"`
	Data             *string `db:"data" json:"data"`
}

func (q *Queries) InsertUsageCredit(ctx context.Context, arg InsertUsageCreditParams) error {
	_, err := q.exec(ctx, q.insertUsageCreditStmt, insertUsageCredit,
		arg.BillingAccountID,
		arg.Amount,
		arg.PaymentMethod,
		arg.PaymentID,
		arg.Status,
		arg.Data,
	)
	return err
}

const updateUsageCreditStatus = `-- name: UpdateUsageCreditStatus :exec
UPDATE usage_credits
SET status = ?
WHERE id = ?
`

type UpdateUsageCreditStatusParams struct {
	Status string `db:"status" json:"status"`
	ID     int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateUsageCreditStatus(ctx context.Context, arg UpdateUsageCreditStatusParams) error {
	_, err := q.exec(ctx, q.updateUsageCreditStatusStmt, updateUsageCreditStatus, arg.Status, arg.ID)
	return err
}
