// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_defaults.sql

package exedb

import (
	"context"
)

const deleteUserDefaultGitHubIntegration = `-- name: DeleteUserDefaultGitHubIntegration :exec
UPDATE user_defaults SET github_integration = NULL, updated_at = CURRENT_TIMESTAMP WHERE user_id = ?
`

func (q *Queries) DeleteUserDefaultGitHubIntegration(ctx context.Context, userID string) error {
	_, err := q.exec(ctx, q.deleteUserDefaultGitHubIntegrationStmt, deleteUserDefaultGitHubIntegration, userID)
	return err
}

const deleteUserDefaultNewSetupScript = `-- name: DeleteUserDefaultNewSetupScript :exec
UPDATE user_defaults SET new_setup_script = NULL, updated_at = CURRENT_TIMESTAMP WHERE user_id = ?
`

func (q *Queries) DeleteUserDefaultNewSetupScript(ctx context.Context, userID string) error {
	_, err := q.exec(ctx, q.deleteUserDefaultNewSetupScriptStmt, deleteUserDefaultNewSetupScript, userID)
	return err
}

const deleteUserDefaultNewVMEmail = `-- name: DeleteUserDefaultNewVMEmail :exec
UPDATE user_defaults SET new_vm_email = NULL, updated_at = CURRENT_TIMESTAMP WHERE user_id = ?
`

func (q *Queries) DeleteUserDefaultNewVMEmail(ctx context.Context, userID string) error {
	_, err := q.exec(ctx, q.deleteUserDefaultNewVMEmailStmt, deleteUserDefaultNewVMEmail, userID)
	return err
}

const getUserDefaults = `-- name: GetUserDefaults :one
SELECT user_id, new_vm_email, created_at, updated_at, global_load_balancer, anycast_network, github_integration, new_setup_script FROM user_defaults WHERE user_id = ?
`

func (q *Queries) GetUserDefaults(ctx context.Context, userID string) (UserDefault, error) {
	row := q.queryRow(ctx, q.getUserDefaultsStmt, getUserDefaults, userID)
	var i UserDefault
	err := row.Scan(
		&i.UserID,
		&i.NewVMEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GlobalLoadBalancer,
		&i.AnycastNetwork,
		&i.GitHubIntegration,
		&i.NewSetupScript,
	)
	return i, err
}

const upsertUserDefaultGitHubIntegration = `-- name: UpsertUserDefaultGitHubIntegration :exec
INSERT INTO user_defaults (user_id, github_integration, updated_at)
VALUES (?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(user_id) DO UPDATE SET
    github_integration = excluded.github_integration,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertUserDefaultGitHubIntegrationParams struct {
	UserID            string `db:"user_id" json:"user_id"`
	GitHubIntegration *int64 `db:"github_integration" json:"github_integration"`
}

func (q *Queries) UpsertUserDefaultGitHubIntegration(ctx context.Context, arg UpsertUserDefaultGitHubIntegrationParams) error {
	_, err := q.exec(ctx, q.upsertUserDefaultGitHubIntegrationStmt, upsertUserDefaultGitHubIntegration, arg.UserID, arg.GitHubIntegration)
	return err
}

const upsertUserDefaultNewSetupScript = `-- name: UpsertUserDefaultNewSetupScript :exec
INSERT INTO user_defaults (user_id, new_setup_script, updated_at)
VALUES (?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(user_id) DO UPDATE SET
    new_setup_script = excluded.new_setup_script,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertUserDefaultNewSetupScriptParams struct {
	UserID         string  `db:"user_id" json:"user_id"`
	NewSetupScript *string `db:"new_setup_script" json:"new_setup_script"`
}

func (q *Queries) UpsertUserDefaultNewSetupScript(ctx context.Context, arg UpsertUserDefaultNewSetupScriptParams) error {
	_, err := q.exec(ctx, q.upsertUserDefaultNewSetupScriptStmt, upsertUserDefaultNewSetupScript, arg.UserID, arg.NewSetupScript)
	return err
}

const upsertUserDefaultNewVMEmail = `-- name: UpsertUserDefaultNewVMEmail :exec
INSERT INTO user_defaults (user_id, new_vm_email, updated_at)
VALUES (?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(user_id) DO UPDATE SET
    new_vm_email = excluded.new_vm_email,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertUserDefaultNewVMEmailParams struct {
	UserID     string `db:"user_id" json:"user_id"`
	NewVMEmail *int64 `db:"new_vm_email" json:"new_vm_email"`
}

func (q *Queries) UpsertUserDefaultNewVMEmail(ctx context.Context, arg UpsertUserDefaultNewVMEmailParams) error {
	_, err := q.exec(ctx, q.upsertUserDefaultNewVMEmailStmt, upsertUserDefaultNewVMEmail, arg.UserID, arg.NewVMEmail)
	return err
}
