// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package welcomedb

import (
	"time"
)

type Visitor struct {
	ID        string    `json:"id"`
	Email     *string   `json:"email"`
	ViewCount int64     `json:"view_count"`
	CreatedAt time.Time `json:"created_at"`
	LastSeen  time.Time `json:"last_seen"`
}
