[Manager]
LogLevel=warning
LogTarget=console
SystemCallArchitectures=native
CapabilityBoundingSet=
DefaultStandardOutput=journal
DefaultStandardError=journal
RuntimeWatchdogSec=0
ShutdownWatchdogSec=10min
WatchdogDevice=
