// A command line tool for generating typescript type declarations from go
// struct types.
//
// Example:
//
//	go run ./cmd/go2ts -o ui/src/generated-types.ts
package main

import (
	"flag"
	"fmt"
	"os"

	"go.skia.org/infra/go/go2ts"
	"shelley.exe.dev/db"
	"shelley.exe.dev/db/generated"
	"sketch.dev/llm"
)

func main() {
	outputPath := flag.String("o", "", "Path to the output TypeScript file.")
	flag.Parse()

	if *outputPath == "" {
		fmt.Println("Usage: go run ./cmd/go2ts -o <output-file>")
		os.Exit(1)
	}

	generator := TS()

	w, err := os.Create(*outputPath)
	if err != nil {
		fmt.Printf("error: %v\n", err)
		os.Exit(1)
	}
	defer w.Close()

	fmt.Fprintf(w, "// Auto-generated by shelley.exe.dev/cmd/go2ts.go\n")
	fmt.Fprintf(w, "// Do not edit manually - regenerate with: go run ./cmd/go2ts -o ui/src/generated-types.ts\n\n")
	generator.Render(w)
}

// TS returns a Go2TS generator for go types we want to use in TypeScript.
func TS() *go2ts.Go2TS {
	generator := go2ts.New()

	// Database message types enum
	generator.AddMultipleUnion(
		[]db.MessageType{
			db.MessageTypeUser,
			db.MessageTypeAgent,
			db.MessageTypeTool,
		},
	)

	// Database struct types
	generator.AddMultiple(
		generated.Conversation{},
		generated.Message{},
		llm.Usage{},
	)

	// Generate clean nominal types
	generator.GenerateNominalTypes = true

	return generator
}