- label: ":shipit: rebase, push, and notify"
  key: push-to-main
  depends_on: __ALL_DEPS__
  command: python3 .buildkite/steps/rebase-and-push.py
  timeout_in_minutes: 10
  retry:
    automatic:
      - exit_status: 1
        limit: 1
