name: CI

on:
  push:
    branches: [ main, david/ci, philip/ci, philip/test-refactor ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/_tests.yml
